apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 10m
  chart:
    spec:
      chart: base
      version: 1.24.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 10m
