---
# Source: pihole/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    labels:
        app: pihole
        chart: pihole-2.27.0
        heritage: Helm
        release: pihole
type: Opaque
data:
    password: 'YWRtaW4='
---
# Source: pihole/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: pihole-custom-dnsmasq
    labels:
        app: pihole
        chart: pihole-2.27.0
        release: pihole
        heritage: Helm
data:
    02-custom.conf: |
        addn-hosts=/etc/addn-hosts
    addn-hosts: |
    05-pihole-custom-cname.conf: |
---
# Source: pihole/templates/service-dhcp.yaml
apiVersion: v1
kind: Service
metadata:
    name: pihole-dhcp
    labels:
        app: pihole
        app.kubernetes.io/name: pihole
        chart: pihole-2.27.0
        release: pihole
        heritage: Helm
spec:
    type: NodePort
    externalTrafficPolicy: Local
    ports:
        - port: 67
          targetPort: client-udp
          protocol: UDP
          name: client-udp
    selector:
        app: pihole
        release: pihole
