// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlcgen

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (id, name, created_at) VALUES (?, ?, ?) RETURNING id, name, created_at
`

type CreateItemParams struct {
	ID        string
	Name      string
	CreatedAt string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem, arg.ID, arg.Name, arg.CreatedAt)
	var i Item
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteItem = `-- name: DeleteItem :execrows
DELETE FROM items WHERE id = ?
`

func (q *Queries) DeleteItem(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listItems = `-- name: ListItems :many
SELECT id, name, created_at FROM items ORDER BY created_at ASC
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
