// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	"errors"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// GroupList is a list of Group
type GroupList struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// List of groups. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items GroupTypeArrayOutput `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaOutput `pulumi:"metadata"`
}

// NewGroupList registers a new resource with the given unique name, arguments, and options.
func NewGroupList(ctx *pulumi.Context,
	name string, args *GroupListArgs, opts ...pulumi.ResourceOption) (*GroupList, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Items == nil {
		return nil, errors.New("invalid value for required argument 'Items'")
	}
	args.ApiVersion = pulumi.StringPtr("lights.homelab.internal/v1alpha1")
	args.Kind = pulumi.StringPtr("GroupList")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource GroupList
	err := ctx.RegisterResource("kubernetes:lights.homelab.internal/v1alpha1:GroupList", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGroupList gets an existing GroupList resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGroupList(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GroupListState, opts ...pulumi.ResourceOption) (*GroupList, error) {
	var resource GroupList
	err := ctx.ReadResource("kubernetes:lights.homelab.internal/v1alpha1:GroupList", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GroupList resources.
type groupListState struct {
}

type GroupListState struct {
}

func (GroupListState) ElementType() reflect.Type {
	return reflect.TypeOf((*groupListState)(nil)).Elem()
}

type groupListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// List of groups. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items []GroupType `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `pulumi:"metadata"`
}

// The set of arguments for constructing a GroupList resource.
type GroupListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// List of groups. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items GroupTypeArrayInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaPtrInput
}

func (GroupListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*groupListArgs)(nil)).Elem()
}

type GroupListInput interface {
	pulumi.Input

	ToGroupListOutput() GroupListOutput
	ToGroupListOutputWithContext(ctx context.Context) GroupListOutput
}

func (*GroupList) ElementType() reflect.Type {
	return reflect.TypeOf((**GroupList)(nil)).Elem()
}

func (i *GroupList) ToGroupListOutput() GroupListOutput {
	return i.ToGroupListOutputWithContext(context.Background())
}

func (i *GroupList) ToGroupListOutputWithContext(ctx context.Context) GroupListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GroupListOutput)
}

// GroupListArrayInput is an input type that accepts GroupListArray and GroupListArrayOutput values.
// You can construct a concrete instance of `GroupListArrayInput` via:
//
//	GroupListArray{ GroupListArgs{...} }
type GroupListArrayInput interface {
	pulumi.Input

	ToGroupListArrayOutput() GroupListArrayOutput
	ToGroupListArrayOutputWithContext(context.Context) GroupListArrayOutput
}

type GroupListArray []GroupListInput

func (GroupListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GroupList)(nil)).Elem()
}

func (i GroupListArray) ToGroupListArrayOutput() GroupListArrayOutput {
	return i.ToGroupListArrayOutputWithContext(context.Background())
}

func (i GroupListArray) ToGroupListArrayOutputWithContext(ctx context.Context) GroupListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GroupListArrayOutput)
}

// GroupListMapInput is an input type that accepts GroupListMap and GroupListMapOutput values.
// You can construct a concrete instance of `GroupListMapInput` via:
//
//	GroupListMap{ "key": GroupListArgs{...} }
type GroupListMapInput interface {
	pulumi.Input

	ToGroupListMapOutput() GroupListMapOutput
	ToGroupListMapOutputWithContext(context.Context) GroupListMapOutput
}

type GroupListMap map[string]GroupListInput

func (GroupListMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GroupList)(nil)).Elem()
}

func (i GroupListMap) ToGroupListMapOutput() GroupListMapOutput {
	return i.ToGroupListMapOutputWithContext(context.Background())
}

func (i GroupListMap) ToGroupListMapOutputWithContext(ctx context.Context) GroupListMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GroupListMapOutput)
}

type GroupListOutput struct{ *pulumi.OutputState }

func (GroupListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GroupList)(nil)).Elem()
}

func (o GroupListOutput) ToGroupListOutput() GroupListOutput {
	return o
}

func (o GroupListOutput) ToGroupListOutputWithContext(ctx context.Context) GroupListOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o GroupListOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *GroupList) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// List of groups. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
func (o GroupListOutput) Items() GroupTypeArrayOutput {
	return o.ApplyT(func(v *GroupList) GroupTypeArrayOutput { return v.Items }).(GroupTypeArrayOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o GroupListOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *GroupList) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o GroupListOutput) Metadata() metav1.ListMetaOutput {
	return o.ApplyT(func(v *GroupList) metav1.ListMetaOutput { return v.Metadata }).(metav1.ListMetaOutput)
}

type GroupListArrayOutput struct{ *pulumi.OutputState }

func (GroupListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GroupList)(nil)).Elem()
}

func (o GroupListArrayOutput) ToGroupListArrayOutput() GroupListArrayOutput {
	return o
}

func (o GroupListArrayOutput) ToGroupListArrayOutputWithContext(ctx context.Context) GroupListArrayOutput {
	return o
}

func (o GroupListArrayOutput) Index(i pulumi.IntInput) GroupListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GroupList {
		return vs[0].([]*GroupList)[vs[1].(int)]
	}).(GroupListOutput)
}

type GroupListMapOutput struct{ *pulumi.OutputState }

func (GroupListMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GroupList)(nil)).Elem()
}

func (o GroupListMapOutput) ToGroupListMapOutput() GroupListMapOutput {
	return o
}

func (o GroupListMapOutput) ToGroupListMapOutputWithContext(ctx context.Context) GroupListMapOutput {
	return o
}

func (o GroupListMapOutput) MapIndex(k pulumi.StringInput) GroupListOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GroupList {
		return vs[0].(map[string]*GroupList)[vs[1].(string)]
	}).(GroupListOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GroupListInput)(nil)).Elem(), &GroupList{})
	pulumi.RegisterInputType(reflect.TypeOf((*GroupListArrayInput)(nil)).Elem(), GroupListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GroupListMapInput)(nil)).Elem(), GroupListMap{})
	pulumi.RegisterOutputType(GroupListOutput{})
	pulumi.RegisterOutputType(GroupListArrayOutput{})
	pulumi.RegisterOutputType(GroupListMapOutput{})
}
