// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Patch resources are used to modify existing Kubernetes resources by using
// Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
// one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
// Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
// [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
// additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
// Group is a user-named collection of Lights, for other resources (switch
// bindings, future circadian schedules) to target instead of enumerating
// individual Lights each time. Cluster scoped like Light/Switch/HueBridge,
// but metadata.name is user-chosen (e.g. "living-room") rather than a
// stable Hue UUID - a Group has no Hue-side identity at all.
type GroupPatch struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrOutput `pulumi:"metadata"`
	Spec     GroupSpecPatchPtrOutput         `pulumi:"spec"`
	Status   GroupStatusPatchPtrOutput       `pulumi:"status"`
}

// NewGroupPatch registers a new resource with the given unique name, arguments, and options.
func NewGroupPatch(ctx *pulumi.Context,
	name string, args *GroupPatchArgs, opts ...pulumi.ResourceOption) (*GroupPatch, error) {
	if args == nil {
		args = &GroupPatchArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("lights.homelab.internal/v1alpha1")
	args.Kind = pulumi.StringPtr("Group")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource GroupPatch
	err := ctx.RegisterResource("kubernetes:lights.homelab.internal/v1alpha1:GroupPatch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGroupPatch gets an existing GroupPatch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGroupPatch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GroupPatchState, opts ...pulumi.ResourceOption) (*GroupPatch, error) {
	var resource GroupPatch
	err := ctx.ReadResource("kubernetes:lights.homelab.internal/v1alpha1:GroupPatch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GroupPatch resources.
type groupPatchState struct {
}

type GroupPatchState struct {
}

func (GroupPatchState) ElementType() reflect.Type {
	return reflect.TypeOf((*groupPatchState)(nil)).Elem()
}

type groupPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMetaPatch `pulumi:"metadata"`
	Spec     *GroupSpecPatch         `pulumi:"spec"`
}

// The set of arguments for constructing a GroupPatch resource.
type GroupPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrInput
	Spec     GroupSpecPatchPtrInput
}

func (GroupPatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*groupPatchArgs)(nil)).Elem()
}

type GroupPatchInput interface {
	pulumi.Input

	ToGroupPatchOutput() GroupPatchOutput
	ToGroupPatchOutputWithContext(ctx context.Context) GroupPatchOutput
}

func (*GroupPatch) ElementType() reflect.Type {
	return reflect.TypeOf((**GroupPatch)(nil)).Elem()
}

func (i *GroupPatch) ToGroupPatchOutput() GroupPatchOutput {
	return i.ToGroupPatchOutputWithContext(context.Background())
}

func (i *GroupPatch) ToGroupPatchOutputWithContext(ctx context.Context) GroupPatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GroupPatchOutput)
}

// GroupPatchArrayInput is an input type that accepts GroupPatchArray and GroupPatchArrayOutput values.
// You can construct a concrete instance of `GroupPatchArrayInput` via:
//
//	GroupPatchArray{ GroupPatchArgs{...} }
type GroupPatchArrayInput interface {
	pulumi.Input

	ToGroupPatchArrayOutput() GroupPatchArrayOutput
	ToGroupPatchArrayOutputWithContext(context.Context) GroupPatchArrayOutput
}

type GroupPatchArray []GroupPatchInput

func (GroupPatchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GroupPatch)(nil)).Elem()
}

func (i GroupPatchArray) ToGroupPatchArrayOutput() GroupPatchArrayOutput {
	return i.ToGroupPatchArrayOutputWithContext(context.Background())
}

func (i GroupPatchArray) ToGroupPatchArrayOutputWithContext(ctx context.Context) GroupPatchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GroupPatchArrayOutput)
}

// GroupPatchMapInput is an input type that accepts GroupPatchMap and GroupPatchMapOutput values.
// You can construct a concrete instance of `GroupPatchMapInput` via:
//
//	GroupPatchMap{ "key": GroupPatchArgs{...} }
type GroupPatchMapInput interface {
	pulumi.Input

	ToGroupPatchMapOutput() GroupPatchMapOutput
	ToGroupPatchMapOutputWithContext(context.Context) GroupPatchMapOutput
}

type GroupPatchMap map[string]GroupPatchInput

func (GroupPatchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GroupPatch)(nil)).Elem()
}

func (i GroupPatchMap) ToGroupPatchMapOutput() GroupPatchMapOutput {
	return i.ToGroupPatchMapOutputWithContext(context.Background())
}

func (i GroupPatchMap) ToGroupPatchMapOutputWithContext(ctx context.Context) GroupPatchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GroupPatchMapOutput)
}

type GroupPatchOutput struct{ *pulumi.OutputState }

func (GroupPatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GroupPatch)(nil)).Elem()
}

func (o GroupPatchOutput) ToGroupPatchOutput() GroupPatchOutput {
	return o
}

func (o GroupPatchOutput) ToGroupPatchOutputWithContext(ctx context.Context) GroupPatchOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o GroupPatchOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GroupPatch) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o GroupPatchOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GroupPatch) pulumi.StringPtrOutput { return v.Kind }).(pulumi.StringPtrOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o GroupPatchOutput) Metadata() metav1.ObjectMetaPatchPtrOutput {
	return o.ApplyT(func(v *GroupPatch) metav1.ObjectMetaPatchPtrOutput { return v.Metadata }).(metav1.ObjectMetaPatchPtrOutput)
}

func (o GroupPatchOutput) Spec() GroupSpecPatchPtrOutput {
	return o.ApplyT(func(v *GroupPatch) GroupSpecPatchPtrOutput { return v.Spec }).(GroupSpecPatchPtrOutput)
}

func (o GroupPatchOutput) Status() GroupStatusPatchPtrOutput {
	return o.ApplyT(func(v *GroupPatch) GroupStatusPatchPtrOutput { return v.Status }).(GroupStatusPatchPtrOutput)
}

type GroupPatchArrayOutput struct{ *pulumi.OutputState }

func (GroupPatchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GroupPatch)(nil)).Elem()
}

func (o GroupPatchArrayOutput) ToGroupPatchArrayOutput() GroupPatchArrayOutput {
	return o
}

func (o GroupPatchArrayOutput) ToGroupPatchArrayOutputWithContext(ctx context.Context) GroupPatchArrayOutput {
	return o
}

func (o GroupPatchArrayOutput) Index(i pulumi.IntInput) GroupPatchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GroupPatch {
		return vs[0].([]*GroupPatch)[vs[1].(int)]
	}).(GroupPatchOutput)
}

type GroupPatchMapOutput struct{ *pulumi.OutputState }

func (GroupPatchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GroupPatch)(nil)).Elem()
}

func (o GroupPatchMapOutput) ToGroupPatchMapOutput() GroupPatchMapOutput {
	return o
}

func (o GroupPatchMapOutput) ToGroupPatchMapOutputWithContext(ctx context.Context) GroupPatchMapOutput {
	return o
}

func (o GroupPatchMapOutput) MapIndex(k pulumi.StringInput) GroupPatchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GroupPatch {
		return vs[0].(map[string]*GroupPatch)[vs[1].(string)]
	}).(GroupPatchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GroupPatchInput)(nil)).Elem(), &GroupPatch{})
	pulumi.RegisterInputType(reflect.TypeOf((*GroupPatchArrayInput)(nil)).Elem(), GroupPatchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GroupPatchMapInput)(nil)).Elem(), GroupPatchMap{})
	pulumi.RegisterOutputType(GroupPatchOutput{})
	pulumi.RegisterOutputType(GroupPatchArrayOutput{})
	pulumi.RegisterOutputType(GroupPatchMapOutput{})
}
