// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Patch resources are used to modify existing Kubernetes resources by using
// Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
// one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
// Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
// [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
// additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
// HueBridge represents a single Hue bridge's live-resolved network
// location, maintained by hub-controller (see
// applications/lights-controller/cmd/hub-controller) so lights-controller
// can reach it without doing its own discovery. Cluster scoped, same
// reasoning as Light. Named after the bridge's stable Hue ID (matches
// config.HueBridgeConfig.ID and Light.status.bridgeId values).
type HueBridgePatch struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrOutput `pulumi:"metadata"`
	// HueBridgeSpec is deliberately empty - see LightSpec's doc comment for
	// why.
	Spec   pulumi.StringMapOutput        `pulumi:"spec"`
	Status HueBridgeStatusPatchPtrOutput `pulumi:"status"`
}

// NewHueBridgePatch registers a new resource with the given unique name, arguments, and options.
func NewHueBridgePatch(ctx *pulumi.Context,
	name string, args *HueBridgePatchArgs, opts ...pulumi.ResourceOption) (*HueBridgePatch, error) {
	if args == nil {
		args = &HueBridgePatchArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("lights.homelab.internal/v1alpha1")
	args.Kind = pulumi.StringPtr("HueBridge")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource HueBridgePatch
	err := ctx.RegisterResource("kubernetes:lights.homelab.internal/v1alpha1:HueBridgePatch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetHueBridgePatch gets an existing HueBridgePatch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetHueBridgePatch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *HueBridgePatchState, opts ...pulumi.ResourceOption) (*HueBridgePatch, error) {
	var resource HueBridgePatch
	err := ctx.ReadResource("kubernetes:lights.homelab.internal/v1alpha1:HueBridgePatch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering HueBridgePatch resources.
type hueBridgePatchState struct {
}

type HueBridgePatchState struct {
}

func (HueBridgePatchState) ElementType() reflect.Type {
	return reflect.TypeOf((*hueBridgePatchState)(nil)).Elem()
}

type hueBridgePatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMetaPatch `pulumi:"metadata"`
	// HueBridgeSpec is deliberately empty - see LightSpec's doc comment for
	// why.
	Spec map[string]string `pulumi:"spec"`
}

// The set of arguments for constructing a HueBridgePatch resource.
type HueBridgePatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrInput
	// HueBridgeSpec is deliberately empty - see LightSpec's doc comment for
	// why.
	Spec pulumi.StringMapInput
}

func (HueBridgePatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*hueBridgePatchArgs)(nil)).Elem()
}

type HueBridgePatchInput interface {
	pulumi.Input

	ToHueBridgePatchOutput() HueBridgePatchOutput
	ToHueBridgePatchOutputWithContext(ctx context.Context) HueBridgePatchOutput
}

func (*HueBridgePatch) ElementType() reflect.Type {
	return reflect.TypeOf((**HueBridgePatch)(nil)).Elem()
}

func (i *HueBridgePatch) ToHueBridgePatchOutput() HueBridgePatchOutput {
	return i.ToHueBridgePatchOutputWithContext(context.Background())
}

func (i *HueBridgePatch) ToHueBridgePatchOutputWithContext(ctx context.Context) HueBridgePatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HueBridgePatchOutput)
}

// HueBridgePatchArrayInput is an input type that accepts HueBridgePatchArray and HueBridgePatchArrayOutput values.
// You can construct a concrete instance of `HueBridgePatchArrayInput` via:
//
//	HueBridgePatchArray{ HueBridgePatchArgs{...} }
type HueBridgePatchArrayInput interface {
	pulumi.Input

	ToHueBridgePatchArrayOutput() HueBridgePatchArrayOutput
	ToHueBridgePatchArrayOutputWithContext(context.Context) HueBridgePatchArrayOutput
}

type HueBridgePatchArray []HueBridgePatchInput

func (HueBridgePatchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*HueBridgePatch)(nil)).Elem()
}

func (i HueBridgePatchArray) ToHueBridgePatchArrayOutput() HueBridgePatchArrayOutput {
	return i.ToHueBridgePatchArrayOutputWithContext(context.Background())
}

func (i HueBridgePatchArray) ToHueBridgePatchArrayOutputWithContext(ctx context.Context) HueBridgePatchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HueBridgePatchArrayOutput)
}

// HueBridgePatchMapInput is an input type that accepts HueBridgePatchMap and HueBridgePatchMapOutput values.
// You can construct a concrete instance of `HueBridgePatchMapInput` via:
//
//	HueBridgePatchMap{ "key": HueBridgePatchArgs{...} }
type HueBridgePatchMapInput interface {
	pulumi.Input

	ToHueBridgePatchMapOutput() HueBridgePatchMapOutput
	ToHueBridgePatchMapOutputWithContext(context.Context) HueBridgePatchMapOutput
}

type HueBridgePatchMap map[string]HueBridgePatchInput

func (HueBridgePatchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*HueBridgePatch)(nil)).Elem()
}

func (i HueBridgePatchMap) ToHueBridgePatchMapOutput() HueBridgePatchMapOutput {
	return i.ToHueBridgePatchMapOutputWithContext(context.Background())
}

func (i HueBridgePatchMap) ToHueBridgePatchMapOutputWithContext(ctx context.Context) HueBridgePatchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HueBridgePatchMapOutput)
}

type HueBridgePatchOutput struct{ *pulumi.OutputState }

func (HueBridgePatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**HueBridgePatch)(nil)).Elem()
}

func (o HueBridgePatchOutput) ToHueBridgePatchOutput() HueBridgePatchOutput {
	return o
}

func (o HueBridgePatchOutput) ToHueBridgePatchOutputWithContext(ctx context.Context) HueBridgePatchOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o HueBridgePatchOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HueBridgePatch) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o HueBridgePatchOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HueBridgePatch) pulumi.StringPtrOutput { return v.Kind }).(pulumi.StringPtrOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o HueBridgePatchOutput) Metadata() metav1.ObjectMetaPatchPtrOutput {
	return o.ApplyT(func(v *HueBridgePatch) metav1.ObjectMetaPatchPtrOutput { return v.Metadata }).(metav1.ObjectMetaPatchPtrOutput)
}

// HueBridgeSpec is deliberately empty - see LightSpec's doc comment for
// why.
func (o HueBridgePatchOutput) Spec() pulumi.StringMapOutput {
	return o.ApplyT(func(v *HueBridgePatch) pulumi.StringMapOutput { return v.Spec }).(pulumi.StringMapOutput)
}

func (o HueBridgePatchOutput) Status() HueBridgeStatusPatchPtrOutput {
	return o.ApplyT(func(v *HueBridgePatch) HueBridgeStatusPatchPtrOutput { return v.Status }).(HueBridgeStatusPatchPtrOutput)
}

type HueBridgePatchArrayOutput struct{ *pulumi.OutputState }

func (HueBridgePatchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*HueBridgePatch)(nil)).Elem()
}

func (o HueBridgePatchArrayOutput) ToHueBridgePatchArrayOutput() HueBridgePatchArrayOutput {
	return o
}

func (o HueBridgePatchArrayOutput) ToHueBridgePatchArrayOutputWithContext(ctx context.Context) HueBridgePatchArrayOutput {
	return o
}

func (o HueBridgePatchArrayOutput) Index(i pulumi.IntInput) HueBridgePatchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *HueBridgePatch {
		return vs[0].([]*HueBridgePatch)[vs[1].(int)]
	}).(HueBridgePatchOutput)
}

type HueBridgePatchMapOutput struct{ *pulumi.OutputState }

func (HueBridgePatchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*HueBridgePatch)(nil)).Elem()
}

func (o HueBridgePatchMapOutput) ToHueBridgePatchMapOutput() HueBridgePatchMapOutput {
	return o
}

func (o HueBridgePatchMapOutput) ToHueBridgePatchMapOutputWithContext(ctx context.Context) HueBridgePatchMapOutput {
	return o
}

func (o HueBridgePatchMapOutput) MapIndex(k pulumi.StringInput) HueBridgePatchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *HueBridgePatch {
		return vs[0].(map[string]*HueBridgePatch)[vs[1].(string)]
	}).(HueBridgePatchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*HueBridgePatchInput)(nil)).Elem(), &HueBridgePatch{})
	pulumi.RegisterInputType(reflect.TypeOf((*HueBridgePatchArrayInput)(nil)).Elem(), HueBridgePatchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*HueBridgePatchMapInput)(nil)).Elem(), HueBridgePatchMap{})
	pulumi.RegisterOutputType(HueBridgePatchOutput{})
	pulumi.RegisterOutputType(HueBridgePatchArrayOutput{})
	pulumi.RegisterOutputType(HueBridgePatchMapOutput{})
}
