// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// HueBridge represents a single Hue bridge's live-resolved network
// location, maintained by hub-controller (see
// applications/lights-controller/cmd/hub-controller) so lights-controller
// can reach it without doing its own discovery. Cluster scoped, same
// reasoning as Light. Named after the bridge's stable Hue ID (matches
// config.HueBridgeConfig.ID and Light.status.bridgeId values).
type HueBridge struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaOutput `pulumi:"metadata"`
	// HueBridgeSpec is deliberately empty - see LightSpec's doc comment for
	// why.
	Spec   pulumi.StringMapOutput   `pulumi:"spec"`
	Status HueBridgeStatusPtrOutput `pulumi:"status"`
}

// NewHueBridge registers a new resource with the given unique name, arguments, and options.
func NewHueBridge(ctx *pulumi.Context,
	name string, args *HueBridgeArgs, opts ...pulumi.ResourceOption) (*HueBridge, error) {
	if args == nil {
		args = &HueBridgeArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("lights.homelab.internal/v1alpha1")
	args.Kind = pulumi.StringPtr("HueBridge")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource HueBridge
	err := ctx.RegisterResource("kubernetes:lights.homelab.internal/v1alpha1:HueBridge", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetHueBridge gets an existing HueBridge resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetHueBridge(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *HueBridgeState, opts ...pulumi.ResourceOption) (*HueBridge, error) {
	var resource HueBridge
	err := ctx.ReadResource("kubernetes:lights.homelab.internal/v1alpha1:HueBridge", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering HueBridge resources.
type hueBridgeState struct {
}

type HueBridgeState struct {
}

func (HueBridgeState) ElementType() reflect.Type {
	return reflect.TypeOf((*hueBridgeState)(nil)).Elem()
}

type hueBridgeArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `pulumi:"metadata"`
	// HueBridgeSpec is deliberately empty - see LightSpec's doc comment for
	// why.
	Spec map[string]string `pulumi:"spec"`
}

// The set of arguments for constructing a HueBridge resource.
type HueBridgeArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPtrInput
	// HueBridgeSpec is deliberately empty - see LightSpec's doc comment for
	// why.
	Spec pulumi.StringMapInput
}

func (HueBridgeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*hueBridgeArgs)(nil)).Elem()
}

type HueBridgeInput interface {
	pulumi.Input

	ToHueBridgeOutput() HueBridgeOutput
	ToHueBridgeOutputWithContext(ctx context.Context) HueBridgeOutput
}

func (*HueBridge) ElementType() reflect.Type {
	return reflect.TypeOf((**HueBridge)(nil)).Elem()
}

func (i *HueBridge) ToHueBridgeOutput() HueBridgeOutput {
	return i.ToHueBridgeOutputWithContext(context.Background())
}

func (i *HueBridge) ToHueBridgeOutputWithContext(ctx context.Context) HueBridgeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HueBridgeOutput)
}

// HueBridgeArrayInput is an input type that accepts HueBridgeArray and HueBridgeArrayOutput values.
// You can construct a concrete instance of `HueBridgeArrayInput` via:
//
//	HueBridgeArray{ HueBridgeArgs{...} }
type HueBridgeArrayInput interface {
	pulumi.Input

	ToHueBridgeArrayOutput() HueBridgeArrayOutput
	ToHueBridgeArrayOutputWithContext(context.Context) HueBridgeArrayOutput
}

type HueBridgeArray []HueBridgeInput

func (HueBridgeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*HueBridge)(nil)).Elem()
}

func (i HueBridgeArray) ToHueBridgeArrayOutput() HueBridgeArrayOutput {
	return i.ToHueBridgeArrayOutputWithContext(context.Background())
}

func (i HueBridgeArray) ToHueBridgeArrayOutputWithContext(ctx context.Context) HueBridgeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HueBridgeArrayOutput)
}

// HueBridgeMapInput is an input type that accepts HueBridgeMap and HueBridgeMapOutput values.
// You can construct a concrete instance of `HueBridgeMapInput` via:
//
//	HueBridgeMap{ "key": HueBridgeArgs{...} }
type HueBridgeMapInput interface {
	pulumi.Input

	ToHueBridgeMapOutput() HueBridgeMapOutput
	ToHueBridgeMapOutputWithContext(context.Context) HueBridgeMapOutput
}

type HueBridgeMap map[string]HueBridgeInput

func (HueBridgeMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*HueBridge)(nil)).Elem()
}

func (i HueBridgeMap) ToHueBridgeMapOutput() HueBridgeMapOutput {
	return i.ToHueBridgeMapOutputWithContext(context.Background())
}

func (i HueBridgeMap) ToHueBridgeMapOutputWithContext(ctx context.Context) HueBridgeMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HueBridgeMapOutput)
}

type HueBridgeOutput struct{ *pulumi.OutputState }

func (HueBridgeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**HueBridge)(nil)).Elem()
}

func (o HueBridgeOutput) ToHueBridgeOutput() HueBridgeOutput {
	return o
}

func (o HueBridgeOutput) ToHueBridgeOutputWithContext(ctx context.Context) HueBridgeOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o HueBridgeOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *HueBridge) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o HueBridgeOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *HueBridge) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o HueBridgeOutput) Metadata() metav1.ObjectMetaOutput {
	return o.ApplyT(func(v *HueBridge) metav1.ObjectMetaOutput { return v.Metadata }).(metav1.ObjectMetaOutput)
}

// HueBridgeSpec is deliberately empty - see LightSpec's doc comment for
// why.
func (o HueBridgeOutput) Spec() pulumi.StringMapOutput {
	return o.ApplyT(func(v *HueBridge) pulumi.StringMapOutput { return v.Spec }).(pulumi.StringMapOutput)
}

func (o HueBridgeOutput) Status() HueBridgeStatusPtrOutput {
	return o.ApplyT(func(v *HueBridge) HueBridgeStatusPtrOutput { return v.Status }).(HueBridgeStatusPtrOutput)
}

type HueBridgeArrayOutput struct{ *pulumi.OutputState }

func (HueBridgeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*HueBridge)(nil)).Elem()
}

func (o HueBridgeArrayOutput) ToHueBridgeArrayOutput() HueBridgeArrayOutput {
	return o
}

func (o HueBridgeArrayOutput) ToHueBridgeArrayOutputWithContext(ctx context.Context) HueBridgeArrayOutput {
	return o
}

func (o HueBridgeArrayOutput) Index(i pulumi.IntInput) HueBridgeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *HueBridge {
		return vs[0].([]*HueBridge)[vs[1].(int)]
	}).(HueBridgeOutput)
}

type HueBridgeMapOutput struct{ *pulumi.OutputState }

func (HueBridgeMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*HueBridge)(nil)).Elem()
}

func (o HueBridgeMapOutput) ToHueBridgeMapOutput() HueBridgeMapOutput {
	return o
}

func (o HueBridgeMapOutput) ToHueBridgeMapOutputWithContext(ctx context.Context) HueBridgeMapOutput {
	return o
}

func (o HueBridgeMapOutput) MapIndex(k pulumi.StringInput) HueBridgeOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *HueBridge {
		return vs[0].(map[string]*HueBridge)[vs[1].(string)]
	}).(HueBridgeOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*HueBridgeInput)(nil)).Elem(), &HueBridge{})
	pulumi.RegisterInputType(reflect.TypeOf((*HueBridgeArrayInput)(nil)).Elem(), HueBridgeArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*HueBridgeMapInput)(nil)).Elem(), HueBridgeMap{})
	pulumi.RegisterOutputType(HueBridgeOutput{})
	pulumi.RegisterOutputType(HueBridgeArrayOutput{})
	pulumi.RegisterOutputType(HueBridgeMapOutput{})
}
