// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Light represents a single Hue light's live, observed state. Cluster
// scoped (like Node/PersistentVolume) since it represents a physical
// device, not a namespace-scoped app resource. Named after the light's own
// Hue UUID (stable, unique, valid as a Kubernetes object name).
type Light struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaOutput `pulumi:"metadata"`
	Spec     LightSpecOutput         `pulumi:"spec"`
	Status   LightStatusPtrOutput    `pulumi:"status"`
}

// NewLight registers a new resource with the given unique name, arguments, and options.
func NewLight(ctx *pulumi.Context,
	name string, args *LightArgs, opts ...pulumi.ResourceOption) (*Light, error) {
	if args == nil {
		args = &LightArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("lights.homelab.internal/v1alpha1")
	args.Kind = pulumi.StringPtr("Light")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource Light
	err := ctx.RegisterResource("kubernetes:lights.homelab.internal/v1alpha1:Light", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLight gets an existing Light resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLight(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LightState, opts ...pulumi.ResourceOption) (*Light, error) {
	var resource Light
	err := ctx.ReadResource("kubernetes:lights.homelab.internal/v1alpha1:Light", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Light resources.
type lightState struct {
}

type LightState struct {
}

func (LightState) ElementType() reflect.Type {
	return reflect.TypeOf((*lightState)(nil)).Elem()
}

type lightArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `pulumi:"metadata"`
	Spec     *LightSpec         `pulumi:"spec"`
}

// The set of arguments for constructing a Light resource.
type LightArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPtrInput
	Spec     LightSpecPtrInput
}

func (LightArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*lightArgs)(nil)).Elem()
}

type LightInput interface {
	pulumi.Input

	ToLightOutput() LightOutput
	ToLightOutputWithContext(ctx context.Context) LightOutput
}

func (*Light) ElementType() reflect.Type {
	return reflect.TypeOf((**Light)(nil)).Elem()
}

func (i *Light) ToLightOutput() LightOutput {
	return i.ToLightOutputWithContext(context.Background())
}

func (i *Light) ToLightOutputWithContext(ctx context.Context) LightOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LightOutput)
}

// LightArrayInput is an input type that accepts LightArray and LightArrayOutput values.
// You can construct a concrete instance of `LightArrayInput` via:
//
//	LightArray{ LightArgs{...} }
type LightArrayInput interface {
	pulumi.Input

	ToLightArrayOutput() LightArrayOutput
	ToLightArrayOutputWithContext(context.Context) LightArrayOutput
}

type LightArray []LightInput

func (LightArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Light)(nil)).Elem()
}

func (i LightArray) ToLightArrayOutput() LightArrayOutput {
	return i.ToLightArrayOutputWithContext(context.Background())
}

func (i LightArray) ToLightArrayOutputWithContext(ctx context.Context) LightArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LightArrayOutput)
}

// LightMapInput is an input type that accepts LightMap and LightMapOutput values.
// You can construct a concrete instance of `LightMapInput` via:
//
//	LightMap{ "key": LightArgs{...} }
type LightMapInput interface {
	pulumi.Input

	ToLightMapOutput() LightMapOutput
	ToLightMapOutputWithContext(context.Context) LightMapOutput
}

type LightMap map[string]LightInput

func (LightMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Light)(nil)).Elem()
}

func (i LightMap) ToLightMapOutput() LightMapOutput {
	return i.ToLightMapOutputWithContext(context.Background())
}

func (i LightMap) ToLightMapOutputWithContext(ctx context.Context) LightMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LightMapOutput)
}

type LightOutput struct{ *pulumi.OutputState }

func (LightOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Light)(nil)).Elem()
}

func (o LightOutput) ToLightOutput() LightOutput {
	return o
}

func (o LightOutput) ToLightOutputWithContext(ctx context.Context) LightOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o LightOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *Light) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o LightOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *Light) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o LightOutput) Metadata() metav1.ObjectMetaOutput {
	return o.ApplyT(func(v *Light) metav1.ObjectMetaOutput { return v.Metadata }).(metav1.ObjectMetaOutput)
}

func (o LightOutput) Spec() LightSpecOutput {
	return o.ApplyT(func(v *Light) LightSpecOutput { return v.Spec }).(LightSpecOutput)
}

func (o LightOutput) Status() LightStatusPtrOutput {
	return o.ApplyT(func(v *Light) LightStatusPtrOutput { return v.Status }).(LightStatusPtrOutput)
}

type LightArrayOutput struct{ *pulumi.OutputState }

func (LightArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Light)(nil)).Elem()
}

func (o LightArrayOutput) ToLightArrayOutput() LightArrayOutput {
	return o
}

func (o LightArrayOutput) ToLightArrayOutputWithContext(ctx context.Context) LightArrayOutput {
	return o
}

func (o LightArrayOutput) Index(i pulumi.IntInput) LightOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Light {
		return vs[0].([]*Light)[vs[1].(int)]
	}).(LightOutput)
}

type LightMapOutput struct{ *pulumi.OutputState }

func (LightMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Light)(nil)).Elem()
}

func (o LightMapOutput) ToLightMapOutput() LightMapOutput {
	return o
}

func (o LightMapOutput) ToLightMapOutputWithContext(ctx context.Context) LightMapOutput {
	return o
}

func (o LightMapOutput) MapIndex(k pulumi.StringInput) LightOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Light {
		return vs[0].(map[string]*Light)[vs[1].(string)]
	}).(LightOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LightInput)(nil)).Elem(), &Light{})
	pulumi.RegisterInputType(reflect.TypeOf((*LightArrayInput)(nil)).Elem(), LightArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*LightMapInput)(nil)).Elem(), LightMap{})
	pulumi.RegisterOutputType(LightOutput{})
	pulumi.RegisterOutputType(LightArrayOutput{})
	pulumi.RegisterOutputType(LightMapOutput{})
}
