// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	"errors"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// LightList is a list of Light
type LightList struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// List of lights. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items LightTypeArrayOutput `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaOutput `pulumi:"metadata"`
}

// NewLightList registers a new resource with the given unique name, arguments, and options.
func NewLightList(ctx *pulumi.Context,
	name string, args *LightListArgs, opts ...pulumi.ResourceOption) (*LightList, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Items == nil {
		return nil, errors.New("invalid value for required argument 'Items'")
	}
	args.ApiVersion = pulumi.StringPtr("lights.homelab.internal/v1alpha1")
	args.Kind = pulumi.StringPtr("LightList")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource LightList
	err := ctx.RegisterResource("kubernetes:lights.homelab.internal/v1alpha1:LightList", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLightList gets an existing LightList resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLightList(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LightListState, opts ...pulumi.ResourceOption) (*LightList, error) {
	var resource LightList
	err := ctx.ReadResource("kubernetes:lights.homelab.internal/v1alpha1:LightList", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LightList resources.
type lightListState struct {
}

type LightListState struct {
}

func (LightListState) ElementType() reflect.Type {
	return reflect.TypeOf((*lightListState)(nil)).Elem()
}

type lightListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// List of lights. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items []LightType `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `pulumi:"metadata"`
}

// The set of arguments for constructing a LightList resource.
type LightListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// List of lights. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items LightTypeArrayInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaPtrInput
}

func (LightListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*lightListArgs)(nil)).Elem()
}

type LightListInput interface {
	pulumi.Input

	ToLightListOutput() LightListOutput
	ToLightListOutputWithContext(ctx context.Context) LightListOutput
}

func (*LightList) ElementType() reflect.Type {
	return reflect.TypeOf((**LightList)(nil)).Elem()
}

func (i *LightList) ToLightListOutput() LightListOutput {
	return i.ToLightListOutputWithContext(context.Background())
}

func (i *LightList) ToLightListOutputWithContext(ctx context.Context) LightListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LightListOutput)
}

// LightListArrayInput is an input type that accepts LightListArray and LightListArrayOutput values.
// You can construct a concrete instance of `LightListArrayInput` via:
//
//	LightListArray{ LightListArgs{...} }
type LightListArrayInput interface {
	pulumi.Input

	ToLightListArrayOutput() LightListArrayOutput
	ToLightListArrayOutputWithContext(context.Context) LightListArrayOutput
}

type LightListArray []LightListInput

func (LightListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LightList)(nil)).Elem()
}

func (i LightListArray) ToLightListArrayOutput() LightListArrayOutput {
	return i.ToLightListArrayOutputWithContext(context.Background())
}

func (i LightListArray) ToLightListArrayOutputWithContext(ctx context.Context) LightListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LightListArrayOutput)
}

// LightListMapInput is an input type that accepts LightListMap and LightListMapOutput values.
// You can construct a concrete instance of `LightListMapInput` via:
//
//	LightListMap{ "key": LightListArgs{...} }
type LightListMapInput interface {
	pulumi.Input

	ToLightListMapOutput() LightListMapOutput
	ToLightListMapOutputWithContext(context.Context) LightListMapOutput
}

type LightListMap map[string]LightListInput

func (LightListMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LightList)(nil)).Elem()
}

func (i LightListMap) ToLightListMapOutput() LightListMapOutput {
	return i.ToLightListMapOutputWithContext(context.Background())
}

func (i LightListMap) ToLightListMapOutputWithContext(ctx context.Context) LightListMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LightListMapOutput)
}

type LightListOutput struct{ *pulumi.OutputState }

func (LightListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LightList)(nil)).Elem()
}

func (o LightListOutput) ToLightListOutput() LightListOutput {
	return o
}

func (o LightListOutput) ToLightListOutputWithContext(ctx context.Context) LightListOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o LightListOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *LightList) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// List of lights. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
func (o LightListOutput) Items() LightTypeArrayOutput {
	return o.ApplyT(func(v *LightList) LightTypeArrayOutput { return v.Items }).(LightTypeArrayOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o LightListOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *LightList) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o LightListOutput) Metadata() metav1.ListMetaOutput {
	return o.ApplyT(func(v *LightList) metav1.ListMetaOutput { return v.Metadata }).(metav1.ListMetaOutput)
}

type LightListArrayOutput struct{ *pulumi.OutputState }

func (LightListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LightList)(nil)).Elem()
}

func (o LightListArrayOutput) ToLightListArrayOutput() LightListArrayOutput {
	return o
}

func (o LightListArrayOutput) ToLightListArrayOutputWithContext(ctx context.Context) LightListArrayOutput {
	return o
}

func (o LightListArrayOutput) Index(i pulumi.IntInput) LightListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *LightList {
		return vs[0].([]*LightList)[vs[1].(int)]
	}).(LightListOutput)
}

type LightListMapOutput struct{ *pulumi.OutputState }

func (LightListMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LightList)(nil)).Elem()
}

func (o LightListMapOutput) ToLightListMapOutput() LightListMapOutput {
	return o
}

func (o LightListMapOutput) ToLightListMapOutputWithContext(ctx context.Context) LightListMapOutput {
	return o
}

func (o LightListMapOutput) MapIndex(k pulumi.StringInput) LightListOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *LightList {
		return vs[0].(map[string]*LightList)[vs[1].(string)]
	}).(LightListOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LightListInput)(nil)).Elem(), &LightList{})
	pulumi.RegisterInputType(reflect.TypeOf((*LightListArrayInput)(nil)).Elem(), LightListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*LightListMapInput)(nil)).Elem(), LightListMap{})
	pulumi.RegisterOutputType(LightListOutput{})
	pulumi.RegisterOutputType(LightListArrayOutput{})
	pulumi.RegisterOutputType(LightListMapOutput{})
}
