// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Switch represents a single physical button's live, observed state plus
// its user-declared bindings. Cluster scoped, same reasoning as Light.
// Named after the button resource's own Hue UUID (stable, unique, valid as
// a Kubernetes object name) - a multi-button device (e.g. a 4-button Hue
// Dimmer Switch) produces one Switch CR per button, sharing BridgeID/
// Name/Product/Model/Battery but with distinct names/ControlID.
type Switch struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaOutput `pulumi:"metadata"`
	Spec     SwitchSpecOutput        `pulumi:"spec"`
	Status   SwitchStatusPtrOutput   `pulumi:"status"`
}

// NewSwitch registers a new resource with the given unique name, arguments, and options.
func NewSwitch(ctx *pulumi.Context,
	name string, args *SwitchArgs, opts ...pulumi.ResourceOption) (*Switch, error) {
	if args == nil {
		args = &SwitchArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("lights.homelab.internal/v1alpha1")
	args.Kind = pulumi.StringPtr("Switch")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource Switch
	err := ctx.RegisterResource("kubernetes:lights.homelab.internal/v1alpha1:Switch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSwitch gets an existing Switch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSwitch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SwitchState, opts ...pulumi.ResourceOption) (*Switch, error) {
	var resource Switch
	err := ctx.ReadResource("kubernetes:lights.homelab.internal/v1alpha1:Switch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Switch resources.
type switchState struct {
}

type SwitchState struct {
}

func (SwitchState) ElementType() reflect.Type {
	return reflect.TypeOf((*switchState)(nil)).Elem()
}

type switchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `pulumi:"metadata"`
	Spec     *SwitchSpec        `pulumi:"spec"`
}

// The set of arguments for constructing a Switch resource.
type SwitchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPtrInput
	Spec     SwitchSpecPtrInput
}

func (SwitchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*switchArgs)(nil)).Elem()
}

type SwitchInput interface {
	pulumi.Input

	ToSwitchOutput() SwitchOutput
	ToSwitchOutputWithContext(ctx context.Context) SwitchOutput
}

func (*Switch) ElementType() reflect.Type {
	return reflect.TypeOf((**Switch)(nil)).Elem()
}

func (i *Switch) ToSwitchOutput() SwitchOutput {
	return i.ToSwitchOutputWithContext(context.Background())
}

func (i *Switch) ToSwitchOutputWithContext(ctx context.Context) SwitchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwitchOutput)
}

// SwitchArrayInput is an input type that accepts SwitchArray and SwitchArrayOutput values.
// You can construct a concrete instance of `SwitchArrayInput` via:
//
//	SwitchArray{ SwitchArgs{...} }
type SwitchArrayInput interface {
	pulumi.Input

	ToSwitchArrayOutput() SwitchArrayOutput
	ToSwitchArrayOutputWithContext(context.Context) SwitchArrayOutput
}

type SwitchArray []SwitchInput

func (SwitchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Switch)(nil)).Elem()
}

func (i SwitchArray) ToSwitchArrayOutput() SwitchArrayOutput {
	return i.ToSwitchArrayOutputWithContext(context.Background())
}

func (i SwitchArray) ToSwitchArrayOutputWithContext(ctx context.Context) SwitchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwitchArrayOutput)
}

// SwitchMapInput is an input type that accepts SwitchMap and SwitchMapOutput values.
// You can construct a concrete instance of `SwitchMapInput` via:
//
//	SwitchMap{ "key": SwitchArgs{...} }
type SwitchMapInput interface {
	pulumi.Input

	ToSwitchMapOutput() SwitchMapOutput
	ToSwitchMapOutputWithContext(context.Context) SwitchMapOutput
}

type SwitchMap map[string]SwitchInput

func (SwitchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Switch)(nil)).Elem()
}

func (i SwitchMap) ToSwitchMapOutput() SwitchMapOutput {
	return i.ToSwitchMapOutputWithContext(context.Background())
}

func (i SwitchMap) ToSwitchMapOutputWithContext(ctx context.Context) SwitchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwitchMapOutput)
}

type SwitchOutput struct{ *pulumi.OutputState }

func (SwitchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Switch)(nil)).Elem()
}

func (o SwitchOutput) ToSwitchOutput() SwitchOutput {
	return o
}

func (o SwitchOutput) ToSwitchOutputWithContext(ctx context.Context) SwitchOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o SwitchOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *Switch) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o SwitchOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *Switch) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o SwitchOutput) Metadata() metav1.ObjectMetaOutput {
	return o.ApplyT(func(v *Switch) metav1.ObjectMetaOutput { return v.Metadata }).(metav1.ObjectMetaOutput)
}

func (o SwitchOutput) Spec() SwitchSpecOutput {
	return o.ApplyT(func(v *Switch) SwitchSpecOutput { return v.Spec }).(SwitchSpecOutput)
}

func (o SwitchOutput) Status() SwitchStatusPtrOutput {
	return o.ApplyT(func(v *Switch) SwitchStatusPtrOutput { return v.Status }).(SwitchStatusPtrOutput)
}

type SwitchArrayOutput struct{ *pulumi.OutputState }

func (SwitchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Switch)(nil)).Elem()
}

func (o SwitchArrayOutput) ToSwitchArrayOutput() SwitchArrayOutput {
	return o
}

func (o SwitchArrayOutput) ToSwitchArrayOutputWithContext(ctx context.Context) SwitchArrayOutput {
	return o
}

func (o SwitchArrayOutput) Index(i pulumi.IntInput) SwitchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Switch {
		return vs[0].([]*Switch)[vs[1].(int)]
	}).(SwitchOutput)
}

type SwitchMapOutput struct{ *pulumi.OutputState }

func (SwitchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Switch)(nil)).Elem()
}

func (o SwitchMapOutput) ToSwitchMapOutput() SwitchMapOutput {
	return o
}

func (o SwitchMapOutput) ToSwitchMapOutputWithContext(ctx context.Context) SwitchMapOutput {
	return o
}

func (o SwitchMapOutput) MapIndex(k pulumi.StringInput) SwitchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Switch {
		return vs[0].(map[string]*Switch)[vs[1].(string)]
	}).(SwitchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SwitchInput)(nil)).Elem(), &Switch{})
	pulumi.RegisterInputType(reflect.TypeOf((*SwitchArrayInput)(nil)).Elem(), SwitchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SwitchMapInput)(nil)).Elem(), SwitchMap{})
	pulumi.RegisterOutputType(SwitchOutput{})
	pulumi.RegisterOutputType(SwitchArrayOutput{})
	pulumi.RegisterOutputType(SwitchMapOutput{})
}
