// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	"errors"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// SwitchList is a list of Switch
type SwitchList struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// List of switches. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items SwitchTypeArrayOutput `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaOutput `pulumi:"metadata"`
}

// NewSwitchList registers a new resource with the given unique name, arguments, and options.
func NewSwitchList(ctx *pulumi.Context,
	name string, args *SwitchListArgs, opts ...pulumi.ResourceOption) (*SwitchList, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Items == nil {
		return nil, errors.New("invalid value for required argument 'Items'")
	}
	args.ApiVersion = pulumi.StringPtr("lights.homelab.internal/v1alpha1")
	args.Kind = pulumi.StringPtr("SwitchList")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource SwitchList
	err := ctx.RegisterResource("kubernetes:lights.homelab.internal/v1alpha1:SwitchList", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSwitchList gets an existing SwitchList resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSwitchList(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SwitchListState, opts ...pulumi.ResourceOption) (*SwitchList, error) {
	var resource SwitchList
	err := ctx.ReadResource("kubernetes:lights.homelab.internal/v1alpha1:SwitchList", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SwitchList resources.
type switchListState struct {
}

type SwitchListState struct {
}

func (SwitchListState) ElementType() reflect.Type {
	return reflect.TypeOf((*switchListState)(nil)).Elem()
}

type switchListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// List of switches. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items []SwitchType `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `pulumi:"metadata"`
}

// The set of arguments for constructing a SwitchList resource.
type SwitchListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// List of switches. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items SwitchTypeArrayInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaPtrInput
}

func (SwitchListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*switchListArgs)(nil)).Elem()
}

type SwitchListInput interface {
	pulumi.Input

	ToSwitchListOutput() SwitchListOutput
	ToSwitchListOutputWithContext(ctx context.Context) SwitchListOutput
}

func (*SwitchList) ElementType() reflect.Type {
	return reflect.TypeOf((**SwitchList)(nil)).Elem()
}

func (i *SwitchList) ToSwitchListOutput() SwitchListOutput {
	return i.ToSwitchListOutputWithContext(context.Background())
}

func (i *SwitchList) ToSwitchListOutputWithContext(ctx context.Context) SwitchListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwitchListOutput)
}

// SwitchListArrayInput is an input type that accepts SwitchListArray and SwitchListArrayOutput values.
// You can construct a concrete instance of `SwitchListArrayInput` via:
//
//	SwitchListArray{ SwitchListArgs{...} }
type SwitchListArrayInput interface {
	pulumi.Input

	ToSwitchListArrayOutput() SwitchListArrayOutput
	ToSwitchListArrayOutputWithContext(context.Context) SwitchListArrayOutput
}

type SwitchListArray []SwitchListInput

func (SwitchListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SwitchList)(nil)).Elem()
}

func (i SwitchListArray) ToSwitchListArrayOutput() SwitchListArrayOutput {
	return i.ToSwitchListArrayOutputWithContext(context.Background())
}

func (i SwitchListArray) ToSwitchListArrayOutputWithContext(ctx context.Context) SwitchListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwitchListArrayOutput)
}

// SwitchListMapInput is an input type that accepts SwitchListMap and SwitchListMapOutput values.
// You can construct a concrete instance of `SwitchListMapInput` via:
//
//	SwitchListMap{ "key": SwitchListArgs{...} }
type SwitchListMapInput interface {
	pulumi.Input

	ToSwitchListMapOutput() SwitchListMapOutput
	ToSwitchListMapOutputWithContext(context.Context) SwitchListMapOutput
}

type SwitchListMap map[string]SwitchListInput

func (SwitchListMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SwitchList)(nil)).Elem()
}

func (i SwitchListMap) ToSwitchListMapOutput() SwitchListMapOutput {
	return i.ToSwitchListMapOutputWithContext(context.Background())
}

func (i SwitchListMap) ToSwitchListMapOutputWithContext(ctx context.Context) SwitchListMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwitchListMapOutput)
}

type SwitchListOutput struct{ *pulumi.OutputState }

func (SwitchListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SwitchList)(nil)).Elem()
}

func (o SwitchListOutput) ToSwitchListOutput() SwitchListOutput {
	return o
}

func (o SwitchListOutput) ToSwitchListOutputWithContext(ctx context.Context) SwitchListOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o SwitchListOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *SwitchList) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// List of switches. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
func (o SwitchListOutput) Items() SwitchTypeArrayOutput {
	return o.ApplyT(func(v *SwitchList) SwitchTypeArrayOutput { return v.Items }).(SwitchTypeArrayOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o SwitchListOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *SwitchList) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o SwitchListOutput) Metadata() metav1.ListMetaOutput {
	return o.ApplyT(func(v *SwitchList) metav1.ListMetaOutput { return v.Metadata }).(metav1.ListMetaOutput)
}

type SwitchListArrayOutput struct{ *pulumi.OutputState }

func (SwitchListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SwitchList)(nil)).Elem()
}

func (o SwitchListArrayOutput) ToSwitchListArrayOutput() SwitchListArrayOutput {
	return o
}

func (o SwitchListArrayOutput) ToSwitchListArrayOutputWithContext(ctx context.Context) SwitchListArrayOutput {
	return o
}

func (o SwitchListArrayOutput) Index(i pulumi.IntInput) SwitchListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SwitchList {
		return vs[0].([]*SwitchList)[vs[1].(int)]
	}).(SwitchListOutput)
}

type SwitchListMapOutput struct{ *pulumi.OutputState }

func (SwitchListMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SwitchList)(nil)).Elem()
}

func (o SwitchListMapOutput) ToSwitchListMapOutput() SwitchListMapOutput {
	return o
}

func (o SwitchListMapOutput) ToSwitchListMapOutputWithContext(ctx context.Context) SwitchListMapOutput {
	return o
}

func (o SwitchListMapOutput) MapIndex(k pulumi.StringInput) SwitchListOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SwitchList {
		return vs[0].(map[string]*SwitchList)[vs[1].(string)]
	}).(SwitchListOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SwitchListInput)(nil)).Elem(), &SwitchList{})
	pulumi.RegisterInputType(reflect.TypeOf((*SwitchListArrayInput)(nil)).Elem(), SwitchListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SwitchListMapInput)(nil)).Elem(), SwitchListMap{})
	pulumi.RegisterOutputType(SwitchListOutput{})
	pulumi.RegisterOutputType(SwitchListArrayOutput{})
	pulumi.RegisterOutputType(SwitchListMapOutput{})
}
