// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Patch resources are used to modify existing Kubernetes resources by using
// Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
// one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
// Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
// [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
// additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
// Switch represents a single physical button's live, observed state plus
// its user-declared bindings. Cluster scoped, same reasoning as Light.
// Named after the button resource's own Hue UUID (stable, unique, valid as
// a Kubernetes object name) - a multi-button device (e.g. a 4-button Hue
// Dimmer Switch) produces one Switch CR per button, sharing BridgeID/
// Name/Product/Model/Battery but with distinct names/ControlID.
type SwitchPatch struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrOutput `pulumi:"metadata"`
	Spec     SwitchSpecPatchPtrOutput        `pulumi:"spec"`
	Status   SwitchStatusPatchPtrOutput      `pulumi:"status"`
}

// NewSwitchPatch registers a new resource with the given unique name, arguments, and options.
func NewSwitchPatch(ctx *pulumi.Context,
	name string, args *SwitchPatchArgs, opts ...pulumi.ResourceOption) (*SwitchPatch, error) {
	if args == nil {
		args = &SwitchPatchArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("lights.homelab.internal/v1alpha1")
	args.Kind = pulumi.StringPtr("Switch")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource SwitchPatch
	err := ctx.RegisterResource("kubernetes:lights.homelab.internal/v1alpha1:SwitchPatch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSwitchPatch gets an existing SwitchPatch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSwitchPatch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SwitchPatchState, opts ...pulumi.ResourceOption) (*SwitchPatch, error) {
	var resource SwitchPatch
	err := ctx.ReadResource("kubernetes:lights.homelab.internal/v1alpha1:SwitchPatch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SwitchPatch resources.
type switchPatchState struct {
}

type SwitchPatchState struct {
}

func (SwitchPatchState) ElementType() reflect.Type {
	return reflect.TypeOf((*switchPatchState)(nil)).Elem()
}

type switchPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMetaPatch `pulumi:"metadata"`
	Spec     *SwitchSpecPatch        `pulumi:"spec"`
}

// The set of arguments for constructing a SwitchPatch resource.
type SwitchPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrInput
	Spec     SwitchSpecPatchPtrInput
}

func (SwitchPatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*switchPatchArgs)(nil)).Elem()
}

type SwitchPatchInput interface {
	pulumi.Input

	ToSwitchPatchOutput() SwitchPatchOutput
	ToSwitchPatchOutputWithContext(ctx context.Context) SwitchPatchOutput
}

func (*SwitchPatch) ElementType() reflect.Type {
	return reflect.TypeOf((**SwitchPatch)(nil)).Elem()
}

func (i *SwitchPatch) ToSwitchPatchOutput() SwitchPatchOutput {
	return i.ToSwitchPatchOutputWithContext(context.Background())
}

func (i *SwitchPatch) ToSwitchPatchOutputWithContext(ctx context.Context) SwitchPatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwitchPatchOutput)
}

// SwitchPatchArrayInput is an input type that accepts SwitchPatchArray and SwitchPatchArrayOutput values.
// You can construct a concrete instance of `SwitchPatchArrayInput` via:
//
//	SwitchPatchArray{ SwitchPatchArgs{...} }
type SwitchPatchArrayInput interface {
	pulumi.Input

	ToSwitchPatchArrayOutput() SwitchPatchArrayOutput
	ToSwitchPatchArrayOutputWithContext(context.Context) SwitchPatchArrayOutput
}

type SwitchPatchArray []SwitchPatchInput

func (SwitchPatchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SwitchPatch)(nil)).Elem()
}

func (i SwitchPatchArray) ToSwitchPatchArrayOutput() SwitchPatchArrayOutput {
	return i.ToSwitchPatchArrayOutputWithContext(context.Background())
}

func (i SwitchPatchArray) ToSwitchPatchArrayOutputWithContext(ctx context.Context) SwitchPatchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwitchPatchArrayOutput)
}

// SwitchPatchMapInput is an input type that accepts SwitchPatchMap and SwitchPatchMapOutput values.
// You can construct a concrete instance of `SwitchPatchMapInput` via:
//
//	SwitchPatchMap{ "key": SwitchPatchArgs{...} }
type SwitchPatchMapInput interface {
	pulumi.Input

	ToSwitchPatchMapOutput() SwitchPatchMapOutput
	ToSwitchPatchMapOutputWithContext(context.Context) SwitchPatchMapOutput
}

type SwitchPatchMap map[string]SwitchPatchInput

func (SwitchPatchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SwitchPatch)(nil)).Elem()
}

func (i SwitchPatchMap) ToSwitchPatchMapOutput() SwitchPatchMapOutput {
	return i.ToSwitchPatchMapOutputWithContext(context.Background())
}

func (i SwitchPatchMap) ToSwitchPatchMapOutputWithContext(ctx context.Context) SwitchPatchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwitchPatchMapOutput)
}

type SwitchPatchOutput struct{ *pulumi.OutputState }

func (SwitchPatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SwitchPatch)(nil)).Elem()
}

func (o SwitchPatchOutput) ToSwitchPatchOutput() SwitchPatchOutput {
	return o
}

func (o SwitchPatchOutput) ToSwitchPatchOutputWithContext(ctx context.Context) SwitchPatchOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o SwitchPatchOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SwitchPatch) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o SwitchPatchOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SwitchPatch) pulumi.StringPtrOutput { return v.Kind }).(pulumi.StringPtrOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o SwitchPatchOutput) Metadata() metav1.ObjectMetaPatchPtrOutput {
	return o.ApplyT(func(v *SwitchPatch) metav1.ObjectMetaPatchPtrOutput { return v.Metadata }).(metav1.ObjectMetaPatchPtrOutput)
}

func (o SwitchPatchOutput) Spec() SwitchSpecPatchPtrOutput {
	return o.ApplyT(func(v *SwitchPatch) SwitchSpecPatchPtrOutput { return v.Spec }).(SwitchSpecPatchPtrOutput)
}

func (o SwitchPatchOutput) Status() SwitchStatusPatchPtrOutput {
	return o.ApplyT(func(v *SwitchPatch) SwitchStatusPatchPtrOutput { return v.Status }).(SwitchStatusPatchPtrOutput)
}

type SwitchPatchArrayOutput struct{ *pulumi.OutputState }

func (SwitchPatchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SwitchPatch)(nil)).Elem()
}

func (o SwitchPatchArrayOutput) ToSwitchPatchArrayOutput() SwitchPatchArrayOutput {
	return o
}

func (o SwitchPatchArrayOutput) ToSwitchPatchArrayOutputWithContext(ctx context.Context) SwitchPatchArrayOutput {
	return o
}

func (o SwitchPatchArrayOutput) Index(i pulumi.IntInput) SwitchPatchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SwitchPatch {
		return vs[0].([]*SwitchPatch)[vs[1].(int)]
	}).(SwitchPatchOutput)
}

type SwitchPatchMapOutput struct{ *pulumi.OutputState }

func (SwitchPatchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SwitchPatch)(nil)).Elem()
}

func (o SwitchPatchMapOutput) ToSwitchPatchMapOutput() SwitchPatchMapOutput {
	return o
}

func (o SwitchPatchMapOutput) ToSwitchPatchMapOutputWithContext(ctx context.Context) SwitchPatchMapOutput {
	return o
}

func (o SwitchPatchMapOutput) MapIndex(k pulumi.StringInput) SwitchPatchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SwitchPatch {
		return vs[0].(map[string]*SwitchPatch)[vs[1].(string)]
	}).(SwitchPatchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SwitchPatchInput)(nil)).Elem(), &SwitchPatch{})
	pulumi.RegisterInputType(reflect.TypeOf((*SwitchPatchArrayInput)(nil)).Elem(), SwitchPatchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SwitchPatchMapInput)(nil)).Elem(), SwitchPatchMap{})
	pulumi.RegisterOutputType(SwitchPatchOutput{})
	pulumi.RegisterOutputType(SwitchPatchArrayOutput{})
	pulumi.RegisterOutputType(SwitchPatchMapOutput{})
}
