// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v2

import (
	"context"
	"reflect"

	"errors"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// CiliumClusterwideNetworkPolicyList is a list of CiliumClusterwideNetworkPolicy
type CiliumClusterwideNetworkPolicyList struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// List of ciliumclusterwidenetworkpolicies. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items CiliumClusterwideNetworkPolicyTypeArrayOutput `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaOutput `pulumi:"metadata"`
}

// NewCiliumClusterwideNetworkPolicyList registers a new resource with the given unique name, arguments, and options.
func NewCiliumClusterwideNetworkPolicyList(ctx *pulumi.Context,
	name string, args *CiliumClusterwideNetworkPolicyListArgs, opts ...pulumi.ResourceOption) (*CiliumClusterwideNetworkPolicyList, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Items == nil {
		return nil, errors.New("invalid value for required argument 'Items'")
	}
	args.ApiVersion = pulumi.StringPtr("cilium.io/v2")
	args.Kind = pulumi.StringPtr("CiliumClusterwideNetworkPolicyList")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource CiliumClusterwideNetworkPolicyList
	err := ctx.RegisterResource("kubernetes:cilium.io/v2:CiliumClusterwideNetworkPolicyList", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCiliumClusterwideNetworkPolicyList gets an existing CiliumClusterwideNetworkPolicyList resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCiliumClusterwideNetworkPolicyList(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CiliumClusterwideNetworkPolicyListState, opts ...pulumi.ResourceOption) (*CiliumClusterwideNetworkPolicyList, error) {
	var resource CiliumClusterwideNetworkPolicyList
	err := ctx.ReadResource("kubernetes:cilium.io/v2:CiliumClusterwideNetworkPolicyList", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CiliumClusterwideNetworkPolicyList resources.
type ciliumClusterwideNetworkPolicyListState struct {
}

type CiliumClusterwideNetworkPolicyListState struct {
}

func (CiliumClusterwideNetworkPolicyListState) ElementType() reflect.Type {
	return reflect.TypeOf((*ciliumClusterwideNetworkPolicyListState)(nil)).Elem()
}

type ciliumClusterwideNetworkPolicyListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// List of ciliumclusterwidenetworkpolicies. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items []CiliumClusterwideNetworkPolicyType `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `pulumi:"metadata"`
}

// The set of arguments for constructing a CiliumClusterwideNetworkPolicyList resource.
type CiliumClusterwideNetworkPolicyListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// List of ciliumclusterwidenetworkpolicies. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items CiliumClusterwideNetworkPolicyTypeArrayInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaPtrInput
}

func (CiliumClusterwideNetworkPolicyListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ciliumClusterwideNetworkPolicyListArgs)(nil)).Elem()
}

type CiliumClusterwideNetworkPolicyListInput interface {
	pulumi.Input

	ToCiliumClusterwideNetworkPolicyListOutput() CiliumClusterwideNetworkPolicyListOutput
	ToCiliumClusterwideNetworkPolicyListOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyListOutput
}

func (*CiliumClusterwideNetworkPolicyList) ElementType() reflect.Type {
	return reflect.TypeOf((**CiliumClusterwideNetworkPolicyList)(nil)).Elem()
}

func (i *CiliumClusterwideNetworkPolicyList) ToCiliumClusterwideNetworkPolicyListOutput() CiliumClusterwideNetworkPolicyListOutput {
	return i.ToCiliumClusterwideNetworkPolicyListOutputWithContext(context.Background())
}

func (i *CiliumClusterwideNetworkPolicyList) ToCiliumClusterwideNetworkPolicyListOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CiliumClusterwideNetworkPolicyListOutput)
}

// CiliumClusterwideNetworkPolicyListArrayInput is an input type that accepts CiliumClusterwideNetworkPolicyListArray and CiliumClusterwideNetworkPolicyListArrayOutput values.
// You can construct a concrete instance of `CiliumClusterwideNetworkPolicyListArrayInput` via:
//
//	CiliumClusterwideNetworkPolicyListArray{ CiliumClusterwideNetworkPolicyListArgs{...} }
type CiliumClusterwideNetworkPolicyListArrayInput interface {
	pulumi.Input

	ToCiliumClusterwideNetworkPolicyListArrayOutput() CiliumClusterwideNetworkPolicyListArrayOutput
	ToCiliumClusterwideNetworkPolicyListArrayOutputWithContext(context.Context) CiliumClusterwideNetworkPolicyListArrayOutput
}

type CiliumClusterwideNetworkPolicyListArray []CiliumClusterwideNetworkPolicyListInput

func (CiliumClusterwideNetworkPolicyListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CiliumClusterwideNetworkPolicyList)(nil)).Elem()
}

func (i CiliumClusterwideNetworkPolicyListArray) ToCiliumClusterwideNetworkPolicyListArrayOutput() CiliumClusterwideNetworkPolicyListArrayOutput {
	return i.ToCiliumClusterwideNetworkPolicyListArrayOutputWithContext(context.Background())
}

func (i CiliumClusterwideNetworkPolicyListArray) ToCiliumClusterwideNetworkPolicyListArrayOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CiliumClusterwideNetworkPolicyListArrayOutput)
}

// CiliumClusterwideNetworkPolicyListMapInput is an input type that accepts CiliumClusterwideNetworkPolicyListMap and CiliumClusterwideNetworkPolicyListMapOutput values.
// You can construct a concrete instance of `CiliumClusterwideNetworkPolicyListMapInput` via:
//
//	CiliumClusterwideNetworkPolicyListMap{ "key": CiliumClusterwideNetworkPolicyListArgs{...} }
type CiliumClusterwideNetworkPolicyListMapInput interface {
	pulumi.Input

	ToCiliumClusterwideNetworkPolicyListMapOutput() CiliumClusterwideNetworkPolicyListMapOutput
	ToCiliumClusterwideNetworkPolicyListMapOutputWithContext(context.Context) CiliumClusterwideNetworkPolicyListMapOutput
}

type CiliumClusterwideNetworkPolicyListMap map[string]CiliumClusterwideNetworkPolicyListInput

func (CiliumClusterwideNetworkPolicyListMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CiliumClusterwideNetworkPolicyList)(nil)).Elem()
}

func (i CiliumClusterwideNetworkPolicyListMap) ToCiliumClusterwideNetworkPolicyListMapOutput() CiliumClusterwideNetworkPolicyListMapOutput {
	return i.ToCiliumClusterwideNetworkPolicyListMapOutputWithContext(context.Background())
}

func (i CiliumClusterwideNetworkPolicyListMap) ToCiliumClusterwideNetworkPolicyListMapOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyListMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CiliumClusterwideNetworkPolicyListMapOutput)
}

type CiliumClusterwideNetworkPolicyListOutput struct{ *pulumi.OutputState }

func (CiliumClusterwideNetworkPolicyListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CiliumClusterwideNetworkPolicyList)(nil)).Elem()
}

func (o CiliumClusterwideNetworkPolicyListOutput) ToCiliumClusterwideNetworkPolicyListOutput() CiliumClusterwideNetworkPolicyListOutput {
	return o
}

func (o CiliumClusterwideNetworkPolicyListOutput) ToCiliumClusterwideNetworkPolicyListOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyListOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o CiliumClusterwideNetworkPolicyListOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *CiliumClusterwideNetworkPolicyList) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// List of ciliumclusterwidenetworkpolicies. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
func (o CiliumClusterwideNetworkPolicyListOutput) Items() CiliumClusterwideNetworkPolicyTypeArrayOutput {
	return o.ApplyT(func(v *CiliumClusterwideNetworkPolicyList) CiliumClusterwideNetworkPolicyTypeArrayOutput {
		return v.Items
	}).(CiliumClusterwideNetworkPolicyTypeArrayOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o CiliumClusterwideNetworkPolicyListOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *CiliumClusterwideNetworkPolicyList) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o CiliumClusterwideNetworkPolicyListOutput) Metadata() metav1.ListMetaOutput {
	return o.ApplyT(func(v *CiliumClusterwideNetworkPolicyList) metav1.ListMetaOutput { return v.Metadata }).(metav1.ListMetaOutput)
}

type CiliumClusterwideNetworkPolicyListArrayOutput struct{ *pulumi.OutputState }

func (CiliumClusterwideNetworkPolicyListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CiliumClusterwideNetworkPolicyList)(nil)).Elem()
}

func (o CiliumClusterwideNetworkPolicyListArrayOutput) ToCiliumClusterwideNetworkPolicyListArrayOutput() CiliumClusterwideNetworkPolicyListArrayOutput {
	return o
}

func (o CiliumClusterwideNetworkPolicyListArrayOutput) ToCiliumClusterwideNetworkPolicyListArrayOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyListArrayOutput {
	return o
}

func (o CiliumClusterwideNetworkPolicyListArrayOutput) Index(i pulumi.IntInput) CiliumClusterwideNetworkPolicyListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CiliumClusterwideNetworkPolicyList {
		return vs[0].([]*CiliumClusterwideNetworkPolicyList)[vs[1].(int)]
	}).(CiliumClusterwideNetworkPolicyListOutput)
}

type CiliumClusterwideNetworkPolicyListMapOutput struct{ *pulumi.OutputState }

func (CiliumClusterwideNetworkPolicyListMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CiliumClusterwideNetworkPolicyList)(nil)).Elem()
}

func (o CiliumClusterwideNetworkPolicyListMapOutput) ToCiliumClusterwideNetworkPolicyListMapOutput() CiliumClusterwideNetworkPolicyListMapOutput {
	return o
}

func (o CiliumClusterwideNetworkPolicyListMapOutput) ToCiliumClusterwideNetworkPolicyListMapOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyListMapOutput {
	return o
}

func (o CiliumClusterwideNetworkPolicyListMapOutput) MapIndex(k pulumi.StringInput) CiliumClusterwideNetworkPolicyListOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CiliumClusterwideNetworkPolicyList {
		return vs[0].(map[string]*CiliumClusterwideNetworkPolicyList)[vs[1].(string)]
	}).(CiliumClusterwideNetworkPolicyListOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CiliumClusterwideNetworkPolicyListInput)(nil)).Elem(), &CiliumClusterwideNetworkPolicyList{})
	pulumi.RegisterInputType(reflect.TypeOf((*CiliumClusterwideNetworkPolicyListArrayInput)(nil)).Elem(), CiliumClusterwideNetworkPolicyListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CiliumClusterwideNetworkPolicyListMapInput)(nil)).Elem(), CiliumClusterwideNetworkPolicyListMap{})
	pulumi.RegisterOutputType(CiliumClusterwideNetworkPolicyListOutput{})
	pulumi.RegisterOutputType(CiliumClusterwideNetworkPolicyListArrayOutput{})
	pulumi.RegisterOutputType(CiliumClusterwideNetworkPolicyListMapOutput{})
}
