// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v2

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Patch resources are used to modify existing Kubernetes resources by using
// Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
// one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
// Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
// [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
// additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
// CiliumNetworkPolicy is a Kubernetes third-party resource with an extended
// version of NetworkPolicy.
type CiliumNetworkPolicyPatch struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrOutput       `pulumi:"metadata"`
	Spec     CiliumNetworkPolicySpecPatchPtrOutput `pulumi:"spec"`
	// Specs is a list of desired Cilium specific rule specification.
	Specs  CiliumNetworkPolicySpecsPatchArrayOutput `pulumi:"specs"`
	Status CiliumNetworkPolicyStatusPatchPtrOutput  `pulumi:"status"`
}

// NewCiliumNetworkPolicyPatch registers a new resource with the given unique name, arguments, and options.
func NewCiliumNetworkPolicyPatch(ctx *pulumi.Context,
	name string, args *CiliumNetworkPolicyPatchArgs, opts ...pulumi.ResourceOption) (*CiliumNetworkPolicyPatch, error) {
	if args == nil {
		args = &CiliumNetworkPolicyPatchArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("cilium.io/v2")
	args.Kind = pulumi.StringPtr("CiliumNetworkPolicy")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource CiliumNetworkPolicyPatch
	err := ctx.RegisterResource("kubernetes:cilium.io/v2:CiliumNetworkPolicyPatch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCiliumNetworkPolicyPatch gets an existing CiliumNetworkPolicyPatch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCiliumNetworkPolicyPatch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CiliumNetworkPolicyPatchState, opts ...pulumi.ResourceOption) (*CiliumNetworkPolicyPatch, error) {
	var resource CiliumNetworkPolicyPatch
	err := ctx.ReadResource("kubernetes:cilium.io/v2:CiliumNetworkPolicyPatch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CiliumNetworkPolicyPatch resources.
type ciliumNetworkPolicyPatchState struct {
}

type CiliumNetworkPolicyPatchState struct {
}

func (CiliumNetworkPolicyPatchState) ElementType() reflect.Type {
	return reflect.TypeOf((*ciliumNetworkPolicyPatchState)(nil)).Elem()
}

type ciliumNetworkPolicyPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMetaPatch       `pulumi:"metadata"`
	Spec     *CiliumNetworkPolicySpecPatch `pulumi:"spec"`
	// Specs is a list of desired Cilium specific rule specification.
	Specs []CiliumNetworkPolicySpecsPatch `pulumi:"specs"`
}

// The set of arguments for constructing a CiliumNetworkPolicyPatch resource.
type CiliumNetworkPolicyPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrInput
	Spec     CiliumNetworkPolicySpecPatchPtrInput
	// Specs is a list of desired Cilium specific rule specification.
	Specs CiliumNetworkPolicySpecsPatchArrayInput
}

func (CiliumNetworkPolicyPatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ciliumNetworkPolicyPatchArgs)(nil)).Elem()
}

type CiliumNetworkPolicyPatchInput interface {
	pulumi.Input

	ToCiliumNetworkPolicyPatchOutput() CiliumNetworkPolicyPatchOutput
	ToCiliumNetworkPolicyPatchOutputWithContext(ctx context.Context) CiliumNetworkPolicyPatchOutput
}

func (*CiliumNetworkPolicyPatch) ElementType() reflect.Type {
	return reflect.TypeOf((**CiliumNetworkPolicyPatch)(nil)).Elem()
}

func (i *CiliumNetworkPolicyPatch) ToCiliumNetworkPolicyPatchOutput() CiliumNetworkPolicyPatchOutput {
	return i.ToCiliumNetworkPolicyPatchOutputWithContext(context.Background())
}

func (i *CiliumNetworkPolicyPatch) ToCiliumNetworkPolicyPatchOutputWithContext(ctx context.Context) CiliumNetworkPolicyPatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CiliumNetworkPolicyPatchOutput)
}

// CiliumNetworkPolicyPatchArrayInput is an input type that accepts CiliumNetworkPolicyPatchArray and CiliumNetworkPolicyPatchArrayOutput values.
// You can construct a concrete instance of `CiliumNetworkPolicyPatchArrayInput` via:
//
//	CiliumNetworkPolicyPatchArray{ CiliumNetworkPolicyPatchArgs{...} }
type CiliumNetworkPolicyPatchArrayInput interface {
	pulumi.Input

	ToCiliumNetworkPolicyPatchArrayOutput() CiliumNetworkPolicyPatchArrayOutput
	ToCiliumNetworkPolicyPatchArrayOutputWithContext(context.Context) CiliumNetworkPolicyPatchArrayOutput
}

type CiliumNetworkPolicyPatchArray []CiliumNetworkPolicyPatchInput

func (CiliumNetworkPolicyPatchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CiliumNetworkPolicyPatch)(nil)).Elem()
}

func (i CiliumNetworkPolicyPatchArray) ToCiliumNetworkPolicyPatchArrayOutput() CiliumNetworkPolicyPatchArrayOutput {
	return i.ToCiliumNetworkPolicyPatchArrayOutputWithContext(context.Background())
}

func (i CiliumNetworkPolicyPatchArray) ToCiliumNetworkPolicyPatchArrayOutputWithContext(ctx context.Context) CiliumNetworkPolicyPatchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CiliumNetworkPolicyPatchArrayOutput)
}

// CiliumNetworkPolicyPatchMapInput is an input type that accepts CiliumNetworkPolicyPatchMap and CiliumNetworkPolicyPatchMapOutput values.
// You can construct a concrete instance of `CiliumNetworkPolicyPatchMapInput` via:
//
//	CiliumNetworkPolicyPatchMap{ "key": CiliumNetworkPolicyPatchArgs{...} }
type CiliumNetworkPolicyPatchMapInput interface {
	pulumi.Input

	ToCiliumNetworkPolicyPatchMapOutput() CiliumNetworkPolicyPatchMapOutput
	ToCiliumNetworkPolicyPatchMapOutputWithContext(context.Context) CiliumNetworkPolicyPatchMapOutput
}

type CiliumNetworkPolicyPatchMap map[string]CiliumNetworkPolicyPatchInput

func (CiliumNetworkPolicyPatchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CiliumNetworkPolicyPatch)(nil)).Elem()
}

func (i CiliumNetworkPolicyPatchMap) ToCiliumNetworkPolicyPatchMapOutput() CiliumNetworkPolicyPatchMapOutput {
	return i.ToCiliumNetworkPolicyPatchMapOutputWithContext(context.Background())
}

func (i CiliumNetworkPolicyPatchMap) ToCiliumNetworkPolicyPatchMapOutputWithContext(ctx context.Context) CiliumNetworkPolicyPatchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CiliumNetworkPolicyPatchMapOutput)
}

type CiliumNetworkPolicyPatchOutput struct{ *pulumi.OutputState }

func (CiliumNetworkPolicyPatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CiliumNetworkPolicyPatch)(nil)).Elem()
}

func (o CiliumNetworkPolicyPatchOutput) ToCiliumNetworkPolicyPatchOutput() CiliumNetworkPolicyPatchOutput {
	return o
}

func (o CiliumNetworkPolicyPatchOutput) ToCiliumNetworkPolicyPatchOutputWithContext(ctx context.Context) CiliumNetworkPolicyPatchOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o CiliumNetworkPolicyPatchOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CiliumNetworkPolicyPatch) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o CiliumNetworkPolicyPatchOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CiliumNetworkPolicyPatch) pulumi.StringPtrOutput { return v.Kind }).(pulumi.StringPtrOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o CiliumNetworkPolicyPatchOutput) Metadata() metav1.ObjectMetaPatchPtrOutput {
	return o.ApplyT(func(v *CiliumNetworkPolicyPatch) metav1.ObjectMetaPatchPtrOutput { return v.Metadata }).(metav1.ObjectMetaPatchPtrOutput)
}

func (o CiliumNetworkPolicyPatchOutput) Spec() CiliumNetworkPolicySpecPatchPtrOutput {
	return o.ApplyT(func(v *CiliumNetworkPolicyPatch) CiliumNetworkPolicySpecPatchPtrOutput { return v.Spec }).(CiliumNetworkPolicySpecPatchPtrOutput)
}

// Specs is a list of desired Cilium specific rule specification.
func (o CiliumNetworkPolicyPatchOutput) Specs() CiliumNetworkPolicySpecsPatchArrayOutput {
	return o.ApplyT(func(v *CiliumNetworkPolicyPatch) CiliumNetworkPolicySpecsPatchArrayOutput { return v.Specs }).(CiliumNetworkPolicySpecsPatchArrayOutput)
}

func (o CiliumNetworkPolicyPatchOutput) Status() CiliumNetworkPolicyStatusPatchPtrOutput {
	return o.ApplyT(func(v *CiliumNetworkPolicyPatch) CiliumNetworkPolicyStatusPatchPtrOutput { return v.Status }).(CiliumNetworkPolicyStatusPatchPtrOutput)
}

type CiliumNetworkPolicyPatchArrayOutput struct{ *pulumi.OutputState }

func (CiliumNetworkPolicyPatchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CiliumNetworkPolicyPatch)(nil)).Elem()
}

func (o CiliumNetworkPolicyPatchArrayOutput) ToCiliumNetworkPolicyPatchArrayOutput() CiliumNetworkPolicyPatchArrayOutput {
	return o
}

func (o CiliumNetworkPolicyPatchArrayOutput) ToCiliumNetworkPolicyPatchArrayOutputWithContext(ctx context.Context) CiliumNetworkPolicyPatchArrayOutput {
	return o
}

func (o CiliumNetworkPolicyPatchArrayOutput) Index(i pulumi.IntInput) CiliumNetworkPolicyPatchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CiliumNetworkPolicyPatch {
		return vs[0].([]*CiliumNetworkPolicyPatch)[vs[1].(int)]
	}).(CiliumNetworkPolicyPatchOutput)
}

type CiliumNetworkPolicyPatchMapOutput struct{ *pulumi.OutputState }

func (CiliumNetworkPolicyPatchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CiliumNetworkPolicyPatch)(nil)).Elem()
}

func (o CiliumNetworkPolicyPatchMapOutput) ToCiliumNetworkPolicyPatchMapOutput() CiliumNetworkPolicyPatchMapOutput {
	return o
}

func (o CiliumNetworkPolicyPatchMapOutput) ToCiliumNetworkPolicyPatchMapOutputWithContext(ctx context.Context) CiliumNetworkPolicyPatchMapOutput {
	return o
}

func (o CiliumNetworkPolicyPatchMapOutput) MapIndex(k pulumi.StringInput) CiliumNetworkPolicyPatchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CiliumNetworkPolicyPatch {
		return vs[0].(map[string]*CiliumNetworkPolicyPatch)[vs[1].(string)]
	}).(CiliumNetworkPolicyPatchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CiliumNetworkPolicyPatchInput)(nil)).Elem(), &CiliumNetworkPolicyPatch{})
	pulumi.RegisterInputType(reflect.TypeOf((*CiliumNetworkPolicyPatchArrayInput)(nil)).Elem(), CiliumNetworkPolicyPatchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CiliumNetworkPolicyPatchMapInput)(nil)).Elem(), CiliumNetworkPolicyPatchMap{})
	pulumi.RegisterOutputType(CiliumNetworkPolicyPatchOutput{})
	pulumi.RegisterOutputType(CiliumNetworkPolicyPatchArrayOutput{})
	pulumi.RegisterOutputType(CiliumNetworkPolicyPatchMapOutput{})
}
