// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v2

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// CiliumClusterwideNetworkPolicy is a Kubernetes third-party resource with an
// modified version of CiliumNetworkPolicy which is cluster scoped rather than
// namespace scoped.
type CiliumClusterwideNetworkPolicy struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaOutput                  `pulumi:"metadata"`
	Spec     CiliumClusterwideNetworkPolicySpecOutput `pulumi:"spec"`
	// Specs is a list of desired Cilium specific rule specification.
	Specs  CiliumClusterwideNetworkPolicySpecsArrayOutput `pulumi:"specs"`
	Status CiliumClusterwideNetworkPolicyStatusPtrOutput  `pulumi:"status"`
}

// NewCiliumClusterwideNetworkPolicy registers a new resource with the given unique name, arguments, and options.
func NewCiliumClusterwideNetworkPolicy(ctx *pulumi.Context,
	name string, args *CiliumClusterwideNetworkPolicyArgs, opts ...pulumi.ResourceOption) (*CiliumClusterwideNetworkPolicy, error) {
	if args == nil {
		args = &CiliumClusterwideNetworkPolicyArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("cilium.io/v2")
	args.Kind = pulumi.StringPtr("CiliumClusterwideNetworkPolicy")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource CiliumClusterwideNetworkPolicy
	err := ctx.RegisterResource("kubernetes:cilium.io/v2:CiliumClusterwideNetworkPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCiliumClusterwideNetworkPolicy gets an existing CiliumClusterwideNetworkPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCiliumClusterwideNetworkPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CiliumClusterwideNetworkPolicyState, opts ...pulumi.ResourceOption) (*CiliumClusterwideNetworkPolicy, error) {
	var resource CiliumClusterwideNetworkPolicy
	err := ctx.ReadResource("kubernetes:cilium.io/v2:CiliumClusterwideNetworkPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CiliumClusterwideNetworkPolicy resources.
type ciliumClusterwideNetworkPolicyState struct {
}

type CiliumClusterwideNetworkPolicyState struct {
}

func (CiliumClusterwideNetworkPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*ciliumClusterwideNetworkPolicyState)(nil)).Elem()
}

type ciliumClusterwideNetworkPolicyArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta                  `pulumi:"metadata"`
	Spec     *CiliumClusterwideNetworkPolicySpec `pulumi:"spec"`
	// Specs is a list of desired Cilium specific rule specification.
	Specs []CiliumClusterwideNetworkPolicySpecs `pulumi:"specs"`
}

// The set of arguments for constructing a CiliumClusterwideNetworkPolicy resource.
type CiliumClusterwideNetworkPolicyArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPtrInput
	Spec     CiliumClusterwideNetworkPolicySpecPtrInput
	// Specs is a list of desired Cilium specific rule specification.
	Specs CiliumClusterwideNetworkPolicySpecsArrayInput
}

func (CiliumClusterwideNetworkPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ciliumClusterwideNetworkPolicyArgs)(nil)).Elem()
}

type CiliumClusterwideNetworkPolicyInput interface {
	pulumi.Input

	ToCiliumClusterwideNetworkPolicyOutput() CiliumClusterwideNetworkPolicyOutput
	ToCiliumClusterwideNetworkPolicyOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyOutput
}

func (*CiliumClusterwideNetworkPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**CiliumClusterwideNetworkPolicy)(nil)).Elem()
}

func (i *CiliumClusterwideNetworkPolicy) ToCiliumClusterwideNetworkPolicyOutput() CiliumClusterwideNetworkPolicyOutput {
	return i.ToCiliumClusterwideNetworkPolicyOutputWithContext(context.Background())
}

func (i *CiliumClusterwideNetworkPolicy) ToCiliumClusterwideNetworkPolicyOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CiliumClusterwideNetworkPolicyOutput)
}

// CiliumClusterwideNetworkPolicyArrayInput is an input type that accepts CiliumClusterwideNetworkPolicyArray and CiliumClusterwideNetworkPolicyArrayOutput values.
// You can construct a concrete instance of `CiliumClusterwideNetworkPolicyArrayInput` via:
//
//	CiliumClusterwideNetworkPolicyArray{ CiliumClusterwideNetworkPolicyArgs{...} }
type CiliumClusterwideNetworkPolicyArrayInput interface {
	pulumi.Input

	ToCiliumClusterwideNetworkPolicyArrayOutput() CiliumClusterwideNetworkPolicyArrayOutput
	ToCiliumClusterwideNetworkPolicyArrayOutputWithContext(context.Context) CiliumClusterwideNetworkPolicyArrayOutput
}

type CiliumClusterwideNetworkPolicyArray []CiliumClusterwideNetworkPolicyInput

func (CiliumClusterwideNetworkPolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CiliumClusterwideNetworkPolicy)(nil)).Elem()
}

func (i CiliumClusterwideNetworkPolicyArray) ToCiliumClusterwideNetworkPolicyArrayOutput() CiliumClusterwideNetworkPolicyArrayOutput {
	return i.ToCiliumClusterwideNetworkPolicyArrayOutputWithContext(context.Background())
}

func (i CiliumClusterwideNetworkPolicyArray) ToCiliumClusterwideNetworkPolicyArrayOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CiliumClusterwideNetworkPolicyArrayOutput)
}

// CiliumClusterwideNetworkPolicyMapInput is an input type that accepts CiliumClusterwideNetworkPolicyMap and CiliumClusterwideNetworkPolicyMapOutput values.
// You can construct a concrete instance of `CiliumClusterwideNetworkPolicyMapInput` via:
//
//	CiliumClusterwideNetworkPolicyMap{ "key": CiliumClusterwideNetworkPolicyArgs{...} }
type CiliumClusterwideNetworkPolicyMapInput interface {
	pulumi.Input

	ToCiliumClusterwideNetworkPolicyMapOutput() CiliumClusterwideNetworkPolicyMapOutput
	ToCiliumClusterwideNetworkPolicyMapOutputWithContext(context.Context) CiliumClusterwideNetworkPolicyMapOutput
}

type CiliumClusterwideNetworkPolicyMap map[string]CiliumClusterwideNetworkPolicyInput

func (CiliumClusterwideNetworkPolicyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CiliumClusterwideNetworkPolicy)(nil)).Elem()
}

func (i CiliumClusterwideNetworkPolicyMap) ToCiliumClusterwideNetworkPolicyMapOutput() CiliumClusterwideNetworkPolicyMapOutput {
	return i.ToCiliumClusterwideNetworkPolicyMapOutputWithContext(context.Background())
}

func (i CiliumClusterwideNetworkPolicyMap) ToCiliumClusterwideNetworkPolicyMapOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CiliumClusterwideNetworkPolicyMapOutput)
}

type CiliumClusterwideNetworkPolicyOutput struct{ *pulumi.OutputState }

func (CiliumClusterwideNetworkPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CiliumClusterwideNetworkPolicy)(nil)).Elem()
}

func (o CiliumClusterwideNetworkPolicyOutput) ToCiliumClusterwideNetworkPolicyOutput() CiliumClusterwideNetworkPolicyOutput {
	return o
}

func (o CiliumClusterwideNetworkPolicyOutput) ToCiliumClusterwideNetworkPolicyOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o CiliumClusterwideNetworkPolicyOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *CiliumClusterwideNetworkPolicy) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o CiliumClusterwideNetworkPolicyOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *CiliumClusterwideNetworkPolicy) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o CiliumClusterwideNetworkPolicyOutput) Metadata() metav1.ObjectMetaOutput {
	return o.ApplyT(func(v *CiliumClusterwideNetworkPolicy) metav1.ObjectMetaOutput { return v.Metadata }).(metav1.ObjectMetaOutput)
}

func (o CiliumClusterwideNetworkPolicyOutput) Spec() CiliumClusterwideNetworkPolicySpecOutput {
	return o.ApplyT(func(v *CiliumClusterwideNetworkPolicy) CiliumClusterwideNetworkPolicySpecOutput { return v.Spec }).(CiliumClusterwideNetworkPolicySpecOutput)
}

// Specs is a list of desired Cilium specific rule specification.
func (o CiliumClusterwideNetworkPolicyOutput) Specs() CiliumClusterwideNetworkPolicySpecsArrayOutput {
	return o.ApplyT(func(v *CiliumClusterwideNetworkPolicy) CiliumClusterwideNetworkPolicySpecsArrayOutput { return v.Specs }).(CiliumClusterwideNetworkPolicySpecsArrayOutput)
}

func (o CiliumClusterwideNetworkPolicyOutput) Status() CiliumClusterwideNetworkPolicyStatusPtrOutput {
	return o.ApplyT(func(v *CiliumClusterwideNetworkPolicy) CiliumClusterwideNetworkPolicyStatusPtrOutput { return v.Status }).(CiliumClusterwideNetworkPolicyStatusPtrOutput)
}

type CiliumClusterwideNetworkPolicyArrayOutput struct{ *pulumi.OutputState }

func (CiliumClusterwideNetworkPolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CiliumClusterwideNetworkPolicy)(nil)).Elem()
}

func (o CiliumClusterwideNetworkPolicyArrayOutput) ToCiliumClusterwideNetworkPolicyArrayOutput() CiliumClusterwideNetworkPolicyArrayOutput {
	return o
}

func (o CiliumClusterwideNetworkPolicyArrayOutput) ToCiliumClusterwideNetworkPolicyArrayOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyArrayOutput {
	return o
}

func (o CiliumClusterwideNetworkPolicyArrayOutput) Index(i pulumi.IntInput) CiliumClusterwideNetworkPolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CiliumClusterwideNetworkPolicy {
		return vs[0].([]*CiliumClusterwideNetworkPolicy)[vs[1].(int)]
	}).(CiliumClusterwideNetworkPolicyOutput)
}

type CiliumClusterwideNetworkPolicyMapOutput struct{ *pulumi.OutputState }

func (CiliumClusterwideNetworkPolicyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CiliumClusterwideNetworkPolicy)(nil)).Elem()
}

func (o CiliumClusterwideNetworkPolicyMapOutput) ToCiliumClusterwideNetworkPolicyMapOutput() CiliumClusterwideNetworkPolicyMapOutput {
	return o
}

func (o CiliumClusterwideNetworkPolicyMapOutput) ToCiliumClusterwideNetworkPolicyMapOutputWithContext(ctx context.Context) CiliumClusterwideNetworkPolicyMapOutput {
	return o
}

func (o CiliumClusterwideNetworkPolicyMapOutput) MapIndex(k pulumi.StringInput) CiliumClusterwideNetworkPolicyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CiliumClusterwideNetworkPolicy {
		return vs[0].(map[string]*CiliumClusterwideNetworkPolicy)[vs[1].(string)]
	}).(CiliumClusterwideNetworkPolicyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CiliumClusterwideNetworkPolicyInput)(nil)).Elem(), &CiliumClusterwideNetworkPolicy{})
	pulumi.RegisterInputType(reflect.TypeOf((*CiliumClusterwideNetworkPolicyArrayInput)(nil)).Elem(), CiliumClusterwideNetworkPolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CiliumClusterwideNetworkPolicyMapInput)(nil)).Elem(), CiliumClusterwideNetworkPolicyMap{})
	pulumi.RegisterOutputType(CiliumClusterwideNetworkPolicyOutput{})
	pulumi.RegisterOutputType(CiliumClusterwideNetworkPolicyArrayOutput{})
	pulumi.RegisterOutputType(CiliumClusterwideNetworkPolicyMapOutput{})
}
