// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateOneOffItem(ctx context.Context, arg CreateOneOffItemParams) (OneOffItem, error)
	DeleteOneOffItem(ctx context.Context, id string) (int64, error)
	ListOneOffItems(ctx context.Context) ([]OneOffItem, error)
}

var _ Querier = (*Queries)(nil)
