// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
)

const createOneOffItem = `-- name: CreateOneOffItem :one
INSERT INTO one_off_items (id, title, created_at) VALUES (?, ?, ?) RETURNING id, title, created_at
`

type CreateOneOffItemParams struct {
	ID        string
	Title     string
	CreatedAt string
}

func (q *Queries) CreateOneOffItem(ctx context.Context, arg CreateOneOffItemParams) (OneOffItem, error) {
	row := q.db.QueryRowContext(ctx, createOneOffItem, arg.ID, arg.Title, arg.CreatedAt)
	var i OneOffItem
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const deleteOneOffItem = `-- name: DeleteOneOffItem :execrows
DELETE FROM one_off_items WHERE id = ?
`

func (q *Queries) DeleteOneOffItem(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOneOffItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listOneOffItems = `-- name: ListOneOffItems :many
SELECT id, title, created_at FROM one_off_items ORDER BY created_at ASC
`

func (q *Queries) ListOneOffItems(ctx context.Context) ([]OneOffItem, error) {
	rows, err := q.db.QueryContext(ctx, listOneOffItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OneOffItem
	for rows.Next() {
		var i OneOffItem
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
