// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Patch resources are used to modify existing Kubernetes resources by using
// Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
// one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
// Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
// [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
// additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
// CircadianSchedule is a user-named, continuous lighting curve for all of
// a Group's lights, anchored to sun position. Cluster scoped, user-chosen
// name (e.g. "living-space-circadian"), same reasoning as Scene/Group - a
// CircadianSchedule has no Hue-side identity of its own.
type CircadianSchedulePatch struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrOutput       `pulumi:"metadata"`
	Spec     CircadianScheduleSpecPatchPtrOutput   `pulumi:"spec"`
	Status   CircadianScheduleStatusPatchPtrOutput `pulumi:"status"`
}

// NewCircadianSchedulePatch registers a new resource with the given unique name, arguments, and options.
func NewCircadianSchedulePatch(ctx *pulumi.Context,
	name string, args *CircadianSchedulePatchArgs, opts ...pulumi.ResourceOption) (*CircadianSchedulePatch, error) {
	if args == nil {
		args = &CircadianSchedulePatchArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("lumenetes.io/v1alpha1")
	args.Kind = pulumi.StringPtr("CircadianSchedule")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource CircadianSchedulePatch
	err := ctx.RegisterResource("kubernetes:lumenetes.io/v1alpha1:CircadianSchedulePatch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCircadianSchedulePatch gets an existing CircadianSchedulePatch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCircadianSchedulePatch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CircadianSchedulePatchState, opts ...pulumi.ResourceOption) (*CircadianSchedulePatch, error) {
	var resource CircadianSchedulePatch
	err := ctx.ReadResource("kubernetes:lumenetes.io/v1alpha1:CircadianSchedulePatch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CircadianSchedulePatch resources.
type circadianSchedulePatchState struct {
}

type CircadianSchedulePatchState struct {
}

func (CircadianSchedulePatchState) ElementType() reflect.Type {
	return reflect.TypeOf((*circadianSchedulePatchState)(nil)).Elem()
}

type circadianSchedulePatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMetaPatch     `pulumi:"metadata"`
	Spec     *CircadianScheduleSpecPatch `pulumi:"spec"`
}

// The set of arguments for constructing a CircadianSchedulePatch resource.
type CircadianSchedulePatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrInput
	Spec     CircadianScheduleSpecPatchPtrInput
}

func (CircadianSchedulePatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*circadianSchedulePatchArgs)(nil)).Elem()
}

type CircadianSchedulePatchInput interface {
	pulumi.Input

	ToCircadianSchedulePatchOutput() CircadianSchedulePatchOutput
	ToCircadianSchedulePatchOutputWithContext(ctx context.Context) CircadianSchedulePatchOutput
}

func (*CircadianSchedulePatch) ElementType() reflect.Type {
	return reflect.TypeOf((**CircadianSchedulePatch)(nil)).Elem()
}

func (i *CircadianSchedulePatch) ToCircadianSchedulePatchOutput() CircadianSchedulePatchOutput {
	return i.ToCircadianSchedulePatchOutputWithContext(context.Background())
}

func (i *CircadianSchedulePatch) ToCircadianSchedulePatchOutputWithContext(ctx context.Context) CircadianSchedulePatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CircadianSchedulePatchOutput)
}

// CircadianSchedulePatchArrayInput is an input type that accepts CircadianSchedulePatchArray and CircadianSchedulePatchArrayOutput values.
// You can construct a concrete instance of `CircadianSchedulePatchArrayInput` via:
//
//	CircadianSchedulePatchArray{ CircadianSchedulePatchArgs{...} }
type CircadianSchedulePatchArrayInput interface {
	pulumi.Input

	ToCircadianSchedulePatchArrayOutput() CircadianSchedulePatchArrayOutput
	ToCircadianSchedulePatchArrayOutputWithContext(context.Context) CircadianSchedulePatchArrayOutput
}

type CircadianSchedulePatchArray []CircadianSchedulePatchInput

func (CircadianSchedulePatchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CircadianSchedulePatch)(nil)).Elem()
}

func (i CircadianSchedulePatchArray) ToCircadianSchedulePatchArrayOutput() CircadianSchedulePatchArrayOutput {
	return i.ToCircadianSchedulePatchArrayOutputWithContext(context.Background())
}

func (i CircadianSchedulePatchArray) ToCircadianSchedulePatchArrayOutputWithContext(ctx context.Context) CircadianSchedulePatchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CircadianSchedulePatchArrayOutput)
}

// CircadianSchedulePatchMapInput is an input type that accepts CircadianSchedulePatchMap and CircadianSchedulePatchMapOutput values.
// You can construct a concrete instance of `CircadianSchedulePatchMapInput` via:
//
//	CircadianSchedulePatchMap{ "key": CircadianSchedulePatchArgs{...} }
type CircadianSchedulePatchMapInput interface {
	pulumi.Input

	ToCircadianSchedulePatchMapOutput() CircadianSchedulePatchMapOutput
	ToCircadianSchedulePatchMapOutputWithContext(context.Context) CircadianSchedulePatchMapOutput
}

type CircadianSchedulePatchMap map[string]CircadianSchedulePatchInput

func (CircadianSchedulePatchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CircadianSchedulePatch)(nil)).Elem()
}

func (i CircadianSchedulePatchMap) ToCircadianSchedulePatchMapOutput() CircadianSchedulePatchMapOutput {
	return i.ToCircadianSchedulePatchMapOutputWithContext(context.Background())
}

func (i CircadianSchedulePatchMap) ToCircadianSchedulePatchMapOutputWithContext(ctx context.Context) CircadianSchedulePatchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CircadianSchedulePatchMapOutput)
}

type CircadianSchedulePatchOutput struct{ *pulumi.OutputState }

func (CircadianSchedulePatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CircadianSchedulePatch)(nil)).Elem()
}

func (o CircadianSchedulePatchOutput) ToCircadianSchedulePatchOutput() CircadianSchedulePatchOutput {
	return o
}

func (o CircadianSchedulePatchOutput) ToCircadianSchedulePatchOutputWithContext(ctx context.Context) CircadianSchedulePatchOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o CircadianSchedulePatchOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CircadianSchedulePatch) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o CircadianSchedulePatchOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CircadianSchedulePatch) pulumi.StringPtrOutput { return v.Kind }).(pulumi.StringPtrOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o CircadianSchedulePatchOutput) Metadata() metav1.ObjectMetaPatchPtrOutput {
	return o.ApplyT(func(v *CircadianSchedulePatch) metav1.ObjectMetaPatchPtrOutput { return v.Metadata }).(metav1.ObjectMetaPatchPtrOutput)
}

func (o CircadianSchedulePatchOutput) Spec() CircadianScheduleSpecPatchPtrOutput {
	return o.ApplyT(func(v *CircadianSchedulePatch) CircadianScheduleSpecPatchPtrOutput { return v.Spec }).(CircadianScheduleSpecPatchPtrOutput)
}

func (o CircadianSchedulePatchOutput) Status() CircadianScheduleStatusPatchPtrOutput {
	return o.ApplyT(func(v *CircadianSchedulePatch) CircadianScheduleStatusPatchPtrOutput { return v.Status }).(CircadianScheduleStatusPatchPtrOutput)
}

type CircadianSchedulePatchArrayOutput struct{ *pulumi.OutputState }

func (CircadianSchedulePatchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CircadianSchedulePatch)(nil)).Elem()
}

func (o CircadianSchedulePatchArrayOutput) ToCircadianSchedulePatchArrayOutput() CircadianSchedulePatchArrayOutput {
	return o
}

func (o CircadianSchedulePatchArrayOutput) ToCircadianSchedulePatchArrayOutputWithContext(ctx context.Context) CircadianSchedulePatchArrayOutput {
	return o
}

func (o CircadianSchedulePatchArrayOutput) Index(i pulumi.IntInput) CircadianSchedulePatchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CircadianSchedulePatch {
		return vs[0].([]*CircadianSchedulePatch)[vs[1].(int)]
	}).(CircadianSchedulePatchOutput)
}

type CircadianSchedulePatchMapOutput struct{ *pulumi.OutputState }

func (CircadianSchedulePatchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CircadianSchedulePatch)(nil)).Elem()
}

func (o CircadianSchedulePatchMapOutput) ToCircadianSchedulePatchMapOutput() CircadianSchedulePatchMapOutput {
	return o
}

func (o CircadianSchedulePatchMapOutput) ToCircadianSchedulePatchMapOutputWithContext(ctx context.Context) CircadianSchedulePatchMapOutput {
	return o
}

func (o CircadianSchedulePatchMapOutput) MapIndex(k pulumi.StringInput) CircadianSchedulePatchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CircadianSchedulePatch {
		return vs[0].(map[string]*CircadianSchedulePatch)[vs[1].(string)]
	}).(CircadianSchedulePatchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CircadianSchedulePatchInput)(nil)).Elem(), &CircadianSchedulePatch{})
	pulumi.RegisterInputType(reflect.TypeOf((*CircadianSchedulePatchArrayInput)(nil)).Elem(), CircadianSchedulePatchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CircadianSchedulePatchMapInput)(nil)).Elem(), CircadianSchedulePatchMap{})
	pulumi.RegisterOutputType(CircadianSchedulePatchOutput{})
	pulumi.RegisterOutputType(CircadianSchedulePatchArrayOutput{})
	pulumi.RegisterOutputType(CircadianSchedulePatchMapOutput{})
}
