// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// CircadianSchedule is a user-named, continuous lighting curve for all of
// a Group's lights, anchored to sun position. Cluster scoped, user-chosen
// name (e.g. "living-space-circadian"), same reasoning as Scene/Group - a
// CircadianSchedule has no Hue-side identity of its own.
type CircadianSchedule struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaOutput          `pulumi:"metadata"`
	Spec     CircadianScheduleSpecOutput      `pulumi:"spec"`
	Status   CircadianScheduleStatusPtrOutput `pulumi:"status"`
}

// NewCircadianSchedule registers a new resource with the given unique name, arguments, and options.
func NewCircadianSchedule(ctx *pulumi.Context,
	name string, args *CircadianScheduleArgs, opts ...pulumi.ResourceOption) (*CircadianSchedule, error) {
	if args == nil {
		args = &CircadianScheduleArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("lumenetes.io/v1alpha1")
	args.Kind = pulumi.StringPtr("CircadianSchedule")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource CircadianSchedule
	err := ctx.RegisterResource("kubernetes:lumenetes.io/v1alpha1:CircadianSchedule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCircadianSchedule gets an existing CircadianSchedule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCircadianSchedule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CircadianScheduleState, opts ...pulumi.ResourceOption) (*CircadianSchedule, error) {
	var resource CircadianSchedule
	err := ctx.ReadResource("kubernetes:lumenetes.io/v1alpha1:CircadianSchedule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CircadianSchedule resources.
type circadianScheduleState struct {
}

type CircadianScheduleState struct {
}

func (CircadianScheduleState) ElementType() reflect.Type {
	return reflect.TypeOf((*circadianScheduleState)(nil)).Elem()
}

type circadianScheduleArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta     `pulumi:"metadata"`
	Spec     *CircadianScheduleSpec `pulumi:"spec"`
}

// The set of arguments for constructing a CircadianSchedule resource.
type CircadianScheduleArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPtrInput
	Spec     CircadianScheduleSpecPtrInput
}

func (CircadianScheduleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*circadianScheduleArgs)(nil)).Elem()
}

type CircadianScheduleInput interface {
	pulumi.Input

	ToCircadianScheduleOutput() CircadianScheduleOutput
	ToCircadianScheduleOutputWithContext(ctx context.Context) CircadianScheduleOutput
}

func (*CircadianSchedule) ElementType() reflect.Type {
	return reflect.TypeOf((**CircadianSchedule)(nil)).Elem()
}

func (i *CircadianSchedule) ToCircadianScheduleOutput() CircadianScheduleOutput {
	return i.ToCircadianScheduleOutputWithContext(context.Background())
}

func (i *CircadianSchedule) ToCircadianScheduleOutputWithContext(ctx context.Context) CircadianScheduleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CircadianScheduleOutput)
}

// CircadianScheduleArrayInput is an input type that accepts CircadianScheduleArray and CircadianScheduleArrayOutput values.
// You can construct a concrete instance of `CircadianScheduleArrayInput` via:
//
//	CircadianScheduleArray{ CircadianScheduleArgs{...} }
type CircadianScheduleArrayInput interface {
	pulumi.Input

	ToCircadianScheduleArrayOutput() CircadianScheduleArrayOutput
	ToCircadianScheduleArrayOutputWithContext(context.Context) CircadianScheduleArrayOutput
}

type CircadianScheduleArray []CircadianScheduleInput

func (CircadianScheduleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CircadianSchedule)(nil)).Elem()
}

func (i CircadianScheduleArray) ToCircadianScheduleArrayOutput() CircadianScheduleArrayOutput {
	return i.ToCircadianScheduleArrayOutputWithContext(context.Background())
}

func (i CircadianScheduleArray) ToCircadianScheduleArrayOutputWithContext(ctx context.Context) CircadianScheduleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CircadianScheduleArrayOutput)
}

// CircadianScheduleMapInput is an input type that accepts CircadianScheduleMap and CircadianScheduleMapOutput values.
// You can construct a concrete instance of `CircadianScheduleMapInput` via:
//
//	CircadianScheduleMap{ "key": CircadianScheduleArgs{...} }
type CircadianScheduleMapInput interface {
	pulumi.Input

	ToCircadianScheduleMapOutput() CircadianScheduleMapOutput
	ToCircadianScheduleMapOutputWithContext(context.Context) CircadianScheduleMapOutput
}

type CircadianScheduleMap map[string]CircadianScheduleInput

func (CircadianScheduleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CircadianSchedule)(nil)).Elem()
}

func (i CircadianScheduleMap) ToCircadianScheduleMapOutput() CircadianScheduleMapOutput {
	return i.ToCircadianScheduleMapOutputWithContext(context.Background())
}

func (i CircadianScheduleMap) ToCircadianScheduleMapOutputWithContext(ctx context.Context) CircadianScheduleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CircadianScheduleMapOutput)
}

type CircadianScheduleOutput struct{ *pulumi.OutputState }

func (CircadianScheduleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CircadianSchedule)(nil)).Elem()
}

func (o CircadianScheduleOutput) ToCircadianScheduleOutput() CircadianScheduleOutput {
	return o
}

func (o CircadianScheduleOutput) ToCircadianScheduleOutputWithContext(ctx context.Context) CircadianScheduleOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o CircadianScheduleOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *CircadianSchedule) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o CircadianScheduleOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *CircadianSchedule) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o CircadianScheduleOutput) Metadata() metav1.ObjectMetaOutput {
	return o.ApplyT(func(v *CircadianSchedule) metav1.ObjectMetaOutput { return v.Metadata }).(metav1.ObjectMetaOutput)
}

func (o CircadianScheduleOutput) Spec() CircadianScheduleSpecOutput {
	return o.ApplyT(func(v *CircadianSchedule) CircadianScheduleSpecOutput { return v.Spec }).(CircadianScheduleSpecOutput)
}

func (o CircadianScheduleOutput) Status() CircadianScheduleStatusPtrOutput {
	return o.ApplyT(func(v *CircadianSchedule) CircadianScheduleStatusPtrOutput { return v.Status }).(CircadianScheduleStatusPtrOutput)
}

type CircadianScheduleArrayOutput struct{ *pulumi.OutputState }

func (CircadianScheduleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CircadianSchedule)(nil)).Elem()
}

func (o CircadianScheduleArrayOutput) ToCircadianScheduleArrayOutput() CircadianScheduleArrayOutput {
	return o
}

func (o CircadianScheduleArrayOutput) ToCircadianScheduleArrayOutputWithContext(ctx context.Context) CircadianScheduleArrayOutput {
	return o
}

func (o CircadianScheduleArrayOutput) Index(i pulumi.IntInput) CircadianScheduleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CircadianSchedule {
		return vs[0].([]*CircadianSchedule)[vs[1].(int)]
	}).(CircadianScheduleOutput)
}

type CircadianScheduleMapOutput struct{ *pulumi.OutputState }

func (CircadianScheduleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CircadianSchedule)(nil)).Elem()
}

func (o CircadianScheduleMapOutput) ToCircadianScheduleMapOutput() CircadianScheduleMapOutput {
	return o
}

func (o CircadianScheduleMapOutput) ToCircadianScheduleMapOutputWithContext(ctx context.Context) CircadianScheduleMapOutput {
	return o
}

func (o CircadianScheduleMapOutput) MapIndex(k pulumi.StringInput) CircadianScheduleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CircadianSchedule {
		return vs[0].(map[string]*CircadianSchedule)[vs[1].(string)]
	}).(CircadianScheduleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CircadianScheduleInput)(nil)).Elem(), &CircadianSchedule{})
	pulumi.RegisterInputType(reflect.TypeOf((*CircadianScheduleArrayInput)(nil)).Elem(), CircadianScheduleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CircadianScheduleMapInput)(nil)).Elem(), CircadianScheduleMap{})
	pulumi.RegisterOutputType(CircadianScheduleOutput{})
	pulumi.RegisterOutputType(CircadianScheduleArrayOutput{})
	pulumi.RegisterOutputType(CircadianScheduleMapOutput{})
}
