// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	"errors"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// CircadianScheduleList is a list of CircadianSchedule
type CircadianScheduleList struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// List of circadianschedules. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items CircadianScheduleTypeArrayOutput `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaOutput `pulumi:"metadata"`
}

// NewCircadianScheduleList registers a new resource with the given unique name, arguments, and options.
func NewCircadianScheduleList(ctx *pulumi.Context,
	name string, args *CircadianScheduleListArgs, opts ...pulumi.ResourceOption) (*CircadianScheduleList, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Items == nil {
		return nil, errors.New("invalid value for required argument 'Items'")
	}
	args.ApiVersion = pulumi.StringPtr("lumenetes.io/v1alpha1")
	args.Kind = pulumi.StringPtr("CircadianScheduleList")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource CircadianScheduleList
	err := ctx.RegisterResource("kubernetes:lumenetes.io/v1alpha1:CircadianScheduleList", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCircadianScheduleList gets an existing CircadianScheduleList resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCircadianScheduleList(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CircadianScheduleListState, opts ...pulumi.ResourceOption) (*CircadianScheduleList, error) {
	var resource CircadianScheduleList
	err := ctx.ReadResource("kubernetes:lumenetes.io/v1alpha1:CircadianScheduleList", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CircadianScheduleList resources.
type circadianScheduleListState struct {
}

type CircadianScheduleListState struct {
}

func (CircadianScheduleListState) ElementType() reflect.Type {
	return reflect.TypeOf((*circadianScheduleListState)(nil)).Elem()
}

type circadianScheduleListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// List of circadianschedules. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items []CircadianScheduleType `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `pulumi:"metadata"`
}

// The set of arguments for constructing a CircadianScheduleList resource.
type CircadianScheduleListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// List of circadianschedules. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items CircadianScheduleTypeArrayInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaPtrInput
}

func (CircadianScheduleListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*circadianScheduleListArgs)(nil)).Elem()
}

type CircadianScheduleListInput interface {
	pulumi.Input

	ToCircadianScheduleListOutput() CircadianScheduleListOutput
	ToCircadianScheduleListOutputWithContext(ctx context.Context) CircadianScheduleListOutput
}

func (*CircadianScheduleList) ElementType() reflect.Type {
	return reflect.TypeOf((**CircadianScheduleList)(nil)).Elem()
}

func (i *CircadianScheduleList) ToCircadianScheduleListOutput() CircadianScheduleListOutput {
	return i.ToCircadianScheduleListOutputWithContext(context.Background())
}

func (i *CircadianScheduleList) ToCircadianScheduleListOutputWithContext(ctx context.Context) CircadianScheduleListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CircadianScheduleListOutput)
}

// CircadianScheduleListArrayInput is an input type that accepts CircadianScheduleListArray and CircadianScheduleListArrayOutput values.
// You can construct a concrete instance of `CircadianScheduleListArrayInput` via:
//
//	CircadianScheduleListArray{ CircadianScheduleListArgs{...} }
type CircadianScheduleListArrayInput interface {
	pulumi.Input

	ToCircadianScheduleListArrayOutput() CircadianScheduleListArrayOutput
	ToCircadianScheduleListArrayOutputWithContext(context.Context) CircadianScheduleListArrayOutput
}

type CircadianScheduleListArray []CircadianScheduleListInput

func (CircadianScheduleListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CircadianScheduleList)(nil)).Elem()
}

func (i CircadianScheduleListArray) ToCircadianScheduleListArrayOutput() CircadianScheduleListArrayOutput {
	return i.ToCircadianScheduleListArrayOutputWithContext(context.Background())
}

func (i CircadianScheduleListArray) ToCircadianScheduleListArrayOutputWithContext(ctx context.Context) CircadianScheduleListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CircadianScheduleListArrayOutput)
}

// CircadianScheduleListMapInput is an input type that accepts CircadianScheduleListMap and CircadianScheduleListMapOutput values.
// You can construct a concrete instance of `CircadianScheduleListMapInput` via:
//
//	CircadianScheduleListMap{ "key": CircadianScheduleListArgs{...} }
type CircadianScheduleListMapInput interface {
	pulumi.Input

	ToCircadianScheduleListMapOutput() CircadianScheduleListMapOutput
	ToCircadianScheduleListMapOutputWithContext(context.Context) CircadianScheduleListMapOutput
}

type CircadianScheduleListMap map[string]CircadianScheduleListInput

func (CircadianScheduleListMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CircadianScheduleList)(nil)).Elem()
}

func (i CircadianScheduleListMap) ToCircadianScheduleListMapOutput() CircadianScheduleListMapOutput {
	return i.ToCircadianScheduleListMapOutputWithContext(context.Background())
}

func (i CircadianScheduleListMap) ToCircadianScheduleListMapOutputWithContext(ctx context.Context) CircadianScheduleListMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CircadianScheduleListMapOutput)
}

type CircadianScheduleListOutput struct{ *pulumi.OutputState }

func (CircadianScheduleListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CircadianScheduleList)(nil)).Elem()
}

func (o CircadianScheduleListOutput) ToCircadianScheduleListOutput() CircadianScheduleListOutput {
	return o
}

func (o CircadianScheduleListOutput) ToCircadianScheduleListOutputWithContext(ctx context.Context) CircadianScheduleListOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o CircadianScheduleListOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *CircadianScheduleList) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// List of circadianschedules. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
func (o CircadianScheduleListOutput) Items() CircadianScheduleTypeArrayOutput {
	return o.ApplyT(func(v *CircadianScheduleList) CircadianScheduleTypeArrayOutput { return v.Items }).(CircadianScheduleTypeArrayOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o CircadianScheduleListOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *CircadianScheduleList) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o CircadianScheduleListOutput) Metadata() metav1.ListMetaOutput {
	return o.ApplyT(func(v *CircadianScheduleList) metav1.ListMetaOutput { return v.Metadata }).(metav1.ListMetaOutput)
}

type CircadianScheduleListArrayOutput struct{ *pulumi.OutputState }

func (CircadianScheduleListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CircadianScheduleList)(nil)).Elem()
}

func (o CircadianScheduleListArrayOutput) ToCircadianScheduleListArrayOutput() CircadianScheduleListArrayOutput {
	return o
}

func (o CircadianScheduleListArrayOutput) ToCircadianScheduleListArrayOutputWithContext(ctx context.Context) CircadianScheduleListArrayOutput {
	return o
}

func (o CircadianScheduleListArrayOutput) Index(i pulumi.IntInput) CircadianScheduleListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CircadianScheduleList {
		return vs[0].([]*CircadianScheduleList)[vs[1].(int)]
	}).(CircadianScheduleListOutput)
}

type CircadianScheduleListMapOutput struct{ *pulumi.OutputState }

func (CircadianScheduleListMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CircadianScheduleList)(nil)).Elem()
}

func (o CircadianScheduleListMapOutput) ToCircadianScheduleListMapOutput() CircadianScheduleListMapOutput {
	return o
}

func (o CircadianScheduleListMapOutput) ToCircadianScheduleListMapOutputWithContext(ctx context.Context) CircadianScheduleListMapOutput {
	return o
}

func (o CircadianScheduleListMapOutput) MapIndex(k pulumi.StringInput) CircadianScheduleListOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CircadianScheduleList {
		return vs[0].(map[string]*CircadianScheduleList)[vs[1].(string)]
	}).(CircadianScheduleListOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CircadianScheduleListInput)(nil)).Elem(), &CircadianScheduleList{})
	pulumi.RegisterInputType(reflect.TypeOf((*CircadianScheduleListArrayInput)(nil)).Elem(), CircadianScheduleListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CircadianScheduleListMapInput)(nil)).Elem(), CircadianScheduleListMap{})
	pulumi.RegisterOutputType(CircadianScheduleListOutput{})
	pulumi.RegisterOutputType(CircadianScheduleListArrayOutput{})
	pulumi.RegisterOutputType(CircadianScheduleListMapOutput{})
}
