// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	"errors"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// SceneList is a list of Scene
type SceneList struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// List of scenes. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items SceneTypeArrayOutput `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaOutput `pulumi:"metadata"`
}

// NewSceneList registers a new resource with the given unique name, arguments, and options.
func NewSceneList(ctx *pulumi.Context,
	name string, args *SceneListArgs, opts ...pulumi.ResourceOption) (*SceneList, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Items == nil {
		return nil, errors.New("invalid value for required argument 'Items'")
	}
	args.ApiVersion = pulumi.StringPtr("lumenetes.io/v1alpha1")
	args.Kind = pulumi.StringPtr("SceneList")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource SceneList
	err := ctx.RegisterResource("kubernetes:lumenetes.io/v1alpha1:SceneList", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSceneList gets an existing SceneList resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSceneList(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SceneListState, opts ...pulumi.ResourceOption) (*SceneList, error) {
	var resource SceneList
	err := ctx.ReadResource("kubernetes:lumenetes.io/v1alpha1:SceneList", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SceneList resources.
type sceneListState struct {
}

type SceneListState struct {
}

func (SceneListState) ElementType() reflect.Type {
	return reflect.TypeOf((*sceneListState)(nil)).Elem()
}

type sceneListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// List of scenes. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items []SceneType `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `pulumi:"metadata"`
}

// The set of arguments for constructing a SceneList resource.
type SceneListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// List of scenes. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items SceneTypeArrayInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaPtrInput
}

func (SceneListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*sceneListArgs)(nil)).Elem()
}

type SceneListInput interface {
	pulumi.Input

	ToSceneListOutput() SceneListOutput
	ToSceneListOutputWithContext(ctx context.Context) SceneListOutput
}

func (*SceneList) ElementType() reflect.Type {
	return reflect.TypeOf((**SceneList)(nil)).Elem()
}

func (i *SceneList) ToSceneListOutput() SceneListOutput {
	return i.ToSceneListOutputWithContext(context.Background())
}

func (i *SceneList) ToSceneListOutputWithContext(ctx context.Context) SceneListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SceneListOutput)
}

// SceneListArrayInput is an input type that accepts SceneListArray and SceneListArrayOutput values.
// You can construct a concrete instance of `SceneListArrayInput` via:
//
//	SceneListArray{ SceneListArgs{...} }
type SceneListArrayInput interface {
	pulumi.Input

	ToSceneListArrayOutput() SceneListArrayOutput
	ToSceneListArrayOutputWithContext(context.Context) SceneListArrayOutput
}

type SceneListArray []SceneListInput

func (SceneListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SceneList)(nil)).Elem()
}

func (i SceneListArray) ToSceneListArrayOutput() SceneListArrayOutput {
	return i.ToSceneListArrayOutputWithContext(context.Background())
}

func (i SceneListArray) ToSceneListArrayOutputWithContext(ctx context.Context) SceneListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SceneListArrayOutput)
}

// SceneListMapInput is an input type that accepts SceneListMap and SceneListMapOutput values.
// You can construct a concrete instance of `SceneListMapInput` via:
//
//	SceneListMap{ "key": SceneListArgs{...} }
type SceneListMapInput interface {
	pulumi.Input

	ToSceneListMapOutput() SceneListMapOutput
	ToSceneListMapOutputWithContext(context.Context) SceneListMapOutput
}

type SceneListMap map[string]SceneListInput

func (SceneListMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SceneList)(nil)).Elem()
}

func (i SceneListMap) ToSceneListMapOutput() SceneListMapOutput {
	return i.ToSceneListMapOutputWithContext(context.Background())
}

func (i SceneListMap) ToSceneListMapOutputWithContext(ctx context.Context) SceneListMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SceneListMapOutput)
}

type SceneListOutput struct{ *pulumi.OutputState }

func (SceneListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SceneList)(nil)).Elem()
}

func (o SceneListOutput) ToSceneListOutput() SceneListOutput {
	return o
}

func (o SceneListOutput) ToSceneListOutputWithContext(ctx context.Context) SceneListOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o SceneListOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *SceneList) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// List of scenes. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
func (o SceneListOutput) Items() SceneTypeArrayOutput {
	return o.ApplyT(func(v *SceneList) SceneTypeArrayOutput { return v.Items }).(SceneTypeArrayOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o SceneListOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *SceneList) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o SceneListOutput) Metadata() metav1.ListMetaOutput {
	return o.ApplyT(func(v *SceneList) metav1.ListMetaOutput { return v.Metadata }).(metav1.ListMetaOutput)
}

type SceneListArrayOutput struct{ *pulumi.OutputState }

func (SceneListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SceneList)(nil)).Elem()
}

func (o SceneListArrayOutput) ToSceneListArrayOutput() SceneListArrayOutput {
	return o
}

func (o SceneListArrayOutput) ToSceneListArrayOutputWithContext(ctx context.Context) SceneListArrayOutput {
	return o
}

func (o SceneListArrayOutput) Index(i pulumi.IntInput) SceneListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SceneList {
		return vs[0].([]*SceneList)[vs[1].(int)]
	}).(SceneListOutput)
}

type SceneListMapOutput struct{ *pulumi.OutputState }

func (SceneListMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SceneList)(nil)).Elem()
}

func (o SceneListMapOutput) ToSceneListMapOutput() SceneListMapOutput {
	return o
}

func (o SceneListMapOutput) ToSceneListMapOutputWithContext(ctx context.Context) SceneListMapOutput {
	return o
}

func (o SceneListMapOutput) MapIndex(k pulumi.StringInput) SceneListOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SceneList {
		return vs[0].(map[string]*SceneList)[vs[1].(string)]
	}).(SceneListOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SceneListInput)(nil)).Elem(), &SceneList{})
	pulumi.RegisterInputType(reflect.TypeOf((*SceneListArrayInput)(nil)).Elem(), SceneListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SceneListMapInput)(nil)).Elem(), SceneListMap{})
	pulumi.RegisterOutputType(SceneListOutput{})
	pulumi.RegisterOutputType(SceneListArrayOutput{})
	pulumi.RegisterOutputType(SceneListMapOutput{})
}
