// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Block struct {
	ID        string
	CycleID   string
	Name      string
	Position  int64
	CreatedAt string
}

type Cycle struct {
	ID        string
	UserID    string
	Name      string
	CreatedAt string
}

type CycleExercise struct {
	ID         string
	CycleID    string
	ExerciseID string
	Position   int64
	CreatedAt  string
}

type Exercise struct {
	ID        string
	Name      string
	Category  string
	Archived  int64
	CreatedAt string
	Equipment string
}

type ExerciseSet struct {
	ID              string
	CycleExerciseID string
	BlockID         string
	Position        int64
	Reps            int64
	PercentageOfTm  sql.NullFloat64
	CreatedAt       string
}

type TrainingMax struct {
	ID          string
	UserID      string
	ExerciseID  string
	Weight      float64
	Unit        string
	EffectiveAt string
	CreatedAt   string
}

type User struct {
	ID        string
	Name      string
	CreatedAt string
}
