// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Patch resources are used to modify existing Kubernetes resources by using
// Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
// one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
// Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
// [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
// additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
// DNSConfig can be deployed to cluster to make a subset of Tailscale MagicDNS
// names resolvable by cluster workloads. Use this if: A) you need to refer to
// tailnet services, exposed to cluster via Tailscale Kubernetes operator egress
// proxies by the MagicDNS names of those tailnet services (usually because the
// services run over HTTPS)
// B) you have exposed a cluster workload to the tailnet using Tailscale Ingress
// and you also want to refer to the workload from within the cluster over the
// Ingress's MagicDNS name (usually because you have some callback component
// that needs to use the same URL as that used by a non-cluster client on
// tailnet).
// When a DNSConfig is applied to a cluster, Tailscale Kubernetes operator will
// deploy a nameserver for ts.net DNS names and automatically populate it with records
// for any Tailscale egress or Ingress proxies deployed to that cluster.
// Currently you must manually update your cluster DNS configuration to add the
// IP address of the deployed nameserver as a ts.net stub nameserver.
// Instructions for how to do it:
// https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configuration-of-stub-domain-and-upstream-nameserver-using-coredns (for CoreDNS),
// https://cloud.google.com/kubernetes-engine/docs/how-to/kube-dns (for kube-dns).
// Tailscale Kubernetes operator will write the address of a Service fronting
// the nameserver to dsnconfig.status.nameserver.ip.
// DNSConfig is a singleton - you must not create more than one.
// NB: if you want cluster workloads to be able to refer to Tailscale Ingress
// using its MagicDNS name, you must also annotate the Ingress resource with
// tailscale.com/experimental-forward-cluster-traffic-via-ingress annotation to
// ensure that the proxy created for the Ingress listens on its Pod IP address.
type DNSConfigPatch struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrOutput `pulumi:"metadata"`
	Spec     DNSConfigSpecPatchPtrOutput     `pulumi:"spec"`
	Status   DNSConfigStatusPatchPtrOutput   `pulumi:"status"`
}

// NewDNSConfigPatch registers a new resource with the given unique name, arguments, and options.
func NewDNSConfigPatch(ctx *pulumi.Context,
	name string, args *DNSConfigPatchArgs, opts ...pulumi.ResourceOption) (*DNSConfigPatch, error) {
	if args == nil {
		args = &DNSConfigPatchArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("tailscale.com/v1alpha1")
	args.Kind = pulumi.StringPtr("DNSConfig")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource DNSConfigPatch
	err := ctx.RegisterResource("kubernetes:tailscale.com/v1alpha1:DNSConfigPatch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDNSConfigPatch gets an existing DNSConfigPatch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDNSConfigPatch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DNSConfigPatchState, opts ...pulumi.ResourceOption) (*DNSConfigPatch, error) {
	var resource DNSConfigPatch
	err := ctx.ReadResource("kubernetes:tailscale.com/v1alpha1:DNSConfigPatch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DNSConfigPatch resources.
type dnsconfigPatchState struct {
}

type DNSConfigPatchState struct {
}

func (DNSConfigPatchState) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsconfigPatchState)(nil)).Elem()
}

type dnsconfigPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMetaPatch `pulumi:"metadata"`
	Spec     *DNSConfigSpecPatch     `pulumi:"spec"`
}

// The set of arguments for constructing a DNSConfigPatch resource.
type DNSConfigPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrInput
	Spec     DNSConfigSpecPatchPtrInput
}

func (DNSConfigPatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsconfigPatchArgs)(nil)).Elem()
}

type DNSConfigPatchInput interface {
	pulumi.Input

	ToDNSConfigPatchOutput() DNSConfigPatchOutput
	ToDNSConfigPatchOutputWithContext(ctx context.Context) DNSConfigPatchOutput
}

func (*DNSConfigPatch) ElementType() reflect.Type {
	return reflect.TypeOf((**DNSConfigPatch)(nil)).Elem()
}

func (i *DNSConfigPatch) ToDNSConfigPatchOutput() DNSConfigPatchOutput {
	return i.ToDNSConfigPatchOutputWithContext(context.Background())
}

func (i *DNSConfigPatch) ToDNSConfigPatchOutputWithContext(ctx context.Context) DNSConfigPatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSConfigPatchOutput)
}

// DNSConfigPatchArrayInput is an input type that accepts DNSConfigPatchArray and DNSConfigPatchArrayOutput values.
// You can construct a concrete instance of `DNSConfigPatchArrayInput` via:
//
//	DNSConfigPatchArray{ DNSConfigPatchArgs{...} }
type DNSConfigPatchArrayInput interface {
	pulumi.Input

	ToDNSConfigPatchArrayOutput() DNSConfigPatchArrayOutput
	ToDNSConfigPatchArrayOutputWithContext(context.Context) DNSConfigPatchArrayOutput
}

type DNSConfigPatchArray []DNSConfigPatchInput

func (DNSConfigPatchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DNSConfigPatch)(nil)).Elem()
}

func (i DNSConfigPatchArray) ToDNSConfigPatchArrayOutput() DNSConfigPatchArrayOutput {
	return i.ToDNSConfigPatchArrayOutputWithContext(context.Background())
}

func (i DNSConfigPatchArray) ToDNSConfigPatchArrayOutputWithContext(ctx context.Context) DNSConfigPatchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSConfigPatchArrayOutput)
}

// DNSConfigPatchMapInput is an input type that accepts DNSConfigPatchMap and DNSConfigPatchMapOutput values.
// You can construct a concrete instance of `DNSConfigPatchMapInput` via:
//
//	DNSConfigPatchMap{ "key": DNSConfigPatchArgs{...} }
type DNSConfigPatchMapInput interface {
	pulumi.Input

	ToDNSConfigPatchMapOutput() DNSConfigPatchMapOutput
	ToDNSConfigPatchMapOutputWithContext(context.Context) DNSConfigPatchMapOutput
}

type DNSConfigPatchMap map[string]DNSConfigPatchInput

func (DNSConfigPatchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DNSConfigPatch)(nil)).Elem()
}

func (i DNSConfigPatchMap) ToDNSConfigPatchMapOutput() DNSConfigPatchMapOutput {
	return i.ToDNSConfigPatchMapOutputWithContext(context.Background())
}

func (i DNSConfigPatchMap) ToDNSConfigPatchMapOutputWithContext(ctx context.Context) DNSConfigPatchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSConfigPatchMapOutput)
}

type DNSConfigPatchOutput struct{ *pulumi.OutputState }

func (DNSConfigPatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DNSConfigPatch)(nil)).Elem()
}

func (o DNSConfigPatchOutput) ToDNSConfigPatchOutput() DNSConfigPatchOutput {
	return o
}

func (o DNSConfigPatchOutput) ToDNSConfigPatchOutputWithContext(ctx context.Context) DNSConfigPatchOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o DNSConfigPatchOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DNSConfigPatch) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o DNSConfigPatchOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DNSConfigPatch) pulumi.StringPtrOutput { return v.Kind }).(pulumi.StringPtrOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o DNSConfigPatchOutput) Metadata() metav1.ObjectMetaPatchPtrOutput {
	return o.ApplyT(func(v *DNSConfigPatch) metav1.ObjectMetaPatchPtrOutput { return v.Metadata }).(metav1.ObjectMetaPatchPtrOutput)
}

func (o DNSConfigPatchOutput) Spec() DNSConfigSpecPatchPtrOutput {
	return o.ApplyT(func(v *DNSConfigPatch) DNSConfigSpecPatchPtrOutput { return v.Spec }).(DNSConfigSpecPatchPtrOutput)
}

func (o DNSConfigPatchOutput) Status() DNSConfigStatusPatchPtrOutput {
	return o.ApplyT(func(v *DNSConfigPatch) DNSConfigStatusPatchPtrOutput { return v.Status }).(DNSConfigStatusPatchPtrOutput)
}

type DNSConfigPatchArrayOutput struct{ *pulumi.OutputState }

func (DNSConfigPatchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DNSConfigPatch)(nil)).Elem()
}

func (o DNSConfigPatchArrayOutput) ToDNSConfigPatchArrayOutput() DNSConfigPatchArrayOutput {
	return o
}

func (o DNSConfigPatchArrayOutput) ToDNSConfigPatchArrayOutputWithContext(ctx context.Context) DNSConfigPatchArrayOutput {
	return o
}

func (o DNSConfigPatchArrayOutput) Index(i pulumi.IntInput) DNSConfigPatchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DNSConfigPatch {
		return vs[0].([]*DNSConfigPatch)[vs[1].(int)]
	}).(DNSConfigPatchOutput)
}

type DNSConfigPatchMapOutput struct{ *pulumi.OutputState }

func (DNSConfigPatchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DNSConfigPatch)(nil)).Elem()
}

func (o DNSConfigPatchMapOutput) ToDNSConfigPatchMapOutput() DNSConfigPatchMapOutput {
	return o
}

func (o DNSConfigPatchMapOutput) ToDNSConfigPatchMapOutputWithContext(ctx context.Context) DNSConfigPatchMapOutput {
	return o
}

func (o DNSConfigPatchMapOutput) MapIndex(k pulumi.StringInput) DNSConfigPatchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DNSConfigPatch {
		return vs[0].(map[string]*DNSConfigPatch)[vs[1].(string)]
	}).(DNSConfigPatchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DNSConfigPatchInput)(nil)).Elem(), &DNSConfigPatch{})
	pulumi.RegisterInputType(reflect.TypeOf((*DNSConfigPatchArrayInput)(nil)).Elem(), DNSConfigPatchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DNSConfigPatchMapInput)(nil)).Elem(), DNSConfigPatchMap{})
	pulumi.RegisterOutputType(DNSConfigPatchOutput{})
	pulumi.RegisterOutputType(DNSConfigPatchArrayOutput{})
	pulumi.RegisterOutputType(DNSConfigPatchMapOutput{})
}
