// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// DNSConfig can be deployed to cluster to make a subset of Tailscale MagicDNS
// names resolvable by cluster workloads. Use this if: A) you need to refer to
// tailnet services, exposed to cluster via Tailscale Kubernetes operator egress
// proxies by the MagicDNS names of those tailnet services (usually because the
// services run over HTTPS)
// B) you have exposed a cluster workload to the tailnet using Tailscale Ingress
// and you also want to refer to the workload from within the cluster over the
// Ingress's MagicDNS name (usually because you have some callback component
// that needs to use the same URL as that used by a non-cluster client on
// tailnet).
// When a DNSConfig is applied to a cluster, Tailscale Kubernetes operator will
// deploy a nameserver for ts.net DNS names and automatically populate it with records
// for any Tailscale egress or Ingress proxies deployed to that cluster.
// Currently you must manually update your cluster DNS configuration to add the
// IP address of the deployed nameserver as a ts.net stub nameserver.
// Instructions for how to do it:
// https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configuration-of-stub-domain-and-upstream-nameserver-using-coredns (for CoreDNS),
// https://cloud.google.com/kubernetes-engine/docs/how-to/kube-dns (for kube-dns).
// Tailscale Kubernetes operator will write the address of a Service fronting
// the nameserver to dsnconfig.status.nameserver.ip.
// DNSConfig is a singleton - you must not create more than one.
// NB: if you want cluster workloads to be able to refer to Tailscale Ingress
// using its MagicDNS name, you must also annotate the Ingress resource with
// tailscale.com/experimental-forward-cluster-traffic-via-ingress annotation to
// ensure that the proxy created for the Ingress listens on its Pod IP address.
type DNSConfig struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaOutput  `pulumi:"metadata"`
	Spec     DNSConfigSpecOutput      `pulumi:"spec"`
	Status   DNSConfigStatusPtrOutput `pulumi:"status"`
}

// NewDNSConfig registers a new resource with the given unique name, arguments, and options.
func NewDNSConfig(ctx *pulumi.Context,
	name string, args *DNSConfigArgs, opts ...pulumi.ResourceOption) (*DNSConfig, error) {
	if args == nil {
		args = &DNSConfigArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("tailscale.com/v1alpha1")
	args.Kind = pulumi.StringPtr("DNSConfig")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource DNSConfig
	err := ctx.RegisterResource("kubernetes:tailscale.com/v1alpha1:DNSConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDNSConfig gets an existing DNSConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDNSConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DNSConfigState, opts ...pulumi.ResourceOption) (*DNSConfig, error) {
	var resource DNSConfig
	err := ctx.ReadResource("kubernetes:tailscale.com/v1alpha1:DNSConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DNSConfig resources.
type dnsconfigState struct {
}

type DNSConfigState struct {
}

func (DNSConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsconfigState)(nil)).Elem()
}

type dnsconfigArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `pulumi:"metadata"`
	Spec     *DNSConfigSpec     `pulumi:"spec"`
}

// The set of arguments for constructing a DNSConfig resource.
type DNSConfigArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPtrInput
	Spec     DNSConfigSpecPtrInput
}

func (DNSConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsconfigArgs)(nil)).Elem()
}

type DNSConfigInput interface {
	pulumi.Input

	ToDNSConfigOutput() DNSConfigOutput
	ToDNSConfigOutputWithContext(ctx context.Context) DNSConfigOutput
}

func (*DNSConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**DNSConfig)(nil)).Elem()
}

func (i *DNSConfig) ToDNSConfigOutput() DNSConfigOutput {
	return i.ToDNSConfigOutputWithContext(context.Background())
}

func (i *DNSConfig) ToDNSConfigOutputWithContext(ctx context.Context) DNSConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSConfigOutput)
}

// DNSConfigArrayInput is an input type that accepts DNSConfigArray and DNSConfigArrayOutput values.
// You can construct a concrete instance of `DNSConfigArrayInput` via:
//
//	DNSConfigArray{ DNSConfigArgs{...} }
type DNSConfigArrayInput interface {
	pulumi.Input

	ToDNSConfigArrayOutput() DNSConfigArrayOutput
	ToDNSConfigArrayOutputWithContext(context.Context) DNSConfigArrayOutput
}

type DNSConfigArray []DNSConfigInput

func (DNSConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DNSConfig)(nil)).Elem()
}

func (i DNSConfigArray) ToDNSConfigArrayOutput() DNSConfigArrayOutput {
	return i.ToDNSConfigArrayOutputWithContext(context.Background())
}

func (i DNSConfigArray) ToDNSConfigArrayOutputWithContext(ctx context.Context) DNSConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSConfigArrayOutput)
}

// DNSConfigMapInput is an input type that accepts DNSConfigMap and DNSConfigMapOutput values.
// You can construct a concrete instance of `DNSConfigMapInput` via:
//
//	DNSConfigMap{ "key": DNSConfigArgs{...} }
type DNSConfigMapInput interface {
	pulumi.Input

	ToDNSConfigMapOutput() DNSConfigMapOutput
	ToDNSConfigMapOutputWithContext(context.Context) DNSConfigMapOutput
}

type DNSConfigMap map[string]DNSConfigInput

func (DNSConfigMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DNSConfig)(nil)).Elem()
}

func (i DNSConfigMap) ToDNSConfigMapOutput() DNSConfigMapOutput {
	return i.ToDNSConfigMapOutputWithContext(context.Background())
}

func (i DNSConfigMap) ToDNSConfigMapOutputWithContext(ctx context.Context) DNSConfigMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSConfigMapOutput)
}

type DNSConfigOutput struct{ *pulumi.OutputState }

func (DNSConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DNSConfig)(nil)).Elem()
}

func (o DNSConfigOutput) ToDNSConfigOutput() DNSConfigOutput {
	return o
}

func (o DNSConfigOutput) ToDNSConfigOutputWithContext(ctx context.Context) DNSConfigOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o DNSConfigOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *DNSConfig) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o DNSConfigOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *DNSConfig) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o DNSConfigOutput) Metadata() metav1.ObjectMetaOutput {
	return o.ApplyT(func(v *DNSConfig) metav1.ObjectMetaOutput { return v.Metadata }).(metav1.ObjectMetaOutput)
}

func (o DNSConfigOutput) Spec() DNSConfigSpecOutput {
	return o.ApplyT(func(v *DNSConfig) DNSConfigSpecOutput { return v.Spec }).(DNSConfigSpecOutput)
}

func (o DNSConfigOutput) Status() DNSConfigStatusPtrOutput {
	return o.ApplyT(func(v *DNSConfig) DNSConfigStatusPtrOutput { return v.Status }).(DNSConfigStatusPtrOutput)
}

type DNSConfigArrayOutput struct{ *pulumi.OutputState }

func (DNSConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DNSConfig)(nil)).Elem()
}

func (o DNSConfigArrayOutput) ToDNSConfigArrayOutput() DNSConfigArrayOutput {
	return o
}

func (o DNSConfigArrayOutput) ToDNSConfigArrayOutputWithContext(ctx context.Context) DNSConfigArrayOutput {
	return o
}

func (o DNSConfigArrayOutput) Index(i pulumi.IntInput) DNSConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DNSConfig {
		return vs[0].([]*DNSConfig)[vs[1].(int)]
	}).(DNSConfigOutput)
}

type DNSConfigMapOutput struct{ *pulumi.OutputState }

func (DNSConfigMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DNSConfig)(nil)).Elem()
}

func (o DNSConfigMapOutput) ToDNSConfigMapOutput() DNSConfigMapOutput {
	return o
}

func (o DNSConfigMapOutput) ToDNSConfigMapOutputWithContext(ctx context.Context) DNSConfigMapOutput {
	return o
}

func (o DNSConfigMapOutput) MapIndex(k pulumi.StringInput) DNSConfigOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DNSConfig {
		return vs[0].(map[string]*DNSConfig)[vs[1].(string)]
	}).(DNSConfigOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DNSConfigInput)(nil)).Elem(), &DNSConfig{})
	pulumi.RegisterInputType(reflect.TypeOf((*DNSConfigArrayInput)(nil)).Elem(), DNSConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DNSConfigMapInput)(nil)).Elem(), DNSConfigMap{})
	pulumi.RegisterOutputType(DNSConfigOutput{})
	pulumi.RegisterOutputType(DNSConfigArrayOutput{})
	pulumi.RegisterOutputType(DNSConfigMapOutput{})
}
