// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "kubernetes:tailscale.com/v1alpha1:Connector":
		r = &Connector{}
	case "kubernetes:tailscale.com/v1alpha1:ConnectorList":
		r = &ConnectorList{}
	case "kubernetes:tailscale.com/v1alpha1:ConnectorPatch":
		r = &ConnectorPatch{}
	case "kubernetes:tailscale.com/v1alpha1:DNSConfig":
		r = &DNSConfig{}
	case "kubernetes:tailscale.com/v1alpha1:DNSConfigList":
		r = &DNSConfigList{}
	case "kubernetes:tailscale.com/v1alpha1:DNSConfigPatch":
		r = &DNSConfigPatch{}
	case "kubernetes:tailscale.com/v1alpha1:ProxyClass":
		r = &ProxyClass{}
	case "kubernetes:tailscale.com/v1alpha1:ProxyClassList":
		r = &ProxyClassList{}
	case "kubernetes:tailscale.com/v1alpha1:ProxyClassPatch":
		r = &ProxyClassPatch{}
	case "kubernetes:tailscale.com/v1alpha1:ProxyGroup":
		r = &ProxyGroup{}
	case "kubernetes:tailscale.com/v1alpha1:ProxyGroupList":
		r = &ProxyGroupList{}
	case "kubernetes:tailscale.com/v1alpha1:ProxyGroupPatch":
		r = &ProxyGroupPatch{}
	case "kubernetes:tailscale.com/v1alpha1:ProxyGroupPolicy":
		r = &ProxyGroupPolicy{}
	case "kubernetes:tailscale.com/v1alpha1:ProxyGroupPolicyList":
		r = &ProxyGroupPolicyList{}
	case "kubernetes:tailscale.com/v1alpha1:ProxyGroupPolicyPatch":
		r = &ProxyGroupPolicyPatch{}
	case "kubernetes:tailscale.com/v1alpha1:Recorder":
		r = &Recorder{}
	case "kubernetes:tailscale.com/v1alpha1:RecorderList":
		r = &RecorderList{}
	case "kubernetes:tailscale.com/v1alpha1:RecorderPatch":
		r = &RecorderPatch{}
	case "kubernetes:tailscale.com/v1alpha1:Tailnet":
		r = &Tailnet{}
	case "kubernetes:tailscale.com/v1alpha1:TailnetList":
		r = &TailnetList{}
	case "kubernetes:tailscale.com/v1alpha1:TailnetPatch":
		r = &TailnetPatch{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := utilities.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"crds",
		"tailscale.com/v1alpha1",
		&module{version},
	)
}
