// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ProxyClass describes a set of configuration parameters that can be applied to
// proxy resources created by the Tailscale Kubernetes operator.
// To apply a given ProxyClass to resources created for a tailscale Ingress or
// Service, use tailscale.com/proxy-class=<proxyclass-name> label. To apply a
// given ProxyClass to resources created for a Connector, use
// connector.spec.proxyClass field.
// ProxyClass is a cluster scoped resource.
// More info:
// https://tailscale.com/kb/1445/kubernetes-operator-customization#cluster-resource-customization-using-proxyclass-custom-resource
type ProxyClass struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaOutput   `pulumi:"metadata"`
	Spec     ProxyClassSpecOutput      `pulumi:"spec"`
	Status   ProxyClassStatusPtrOutput `pulumi:"status"`
}

// NewProxyClass registers a new resource with the given unique name, arguments, and options.
func NewProxyClass(ctx *pulumi.Context,
	name string, args *ProxyClassArgs, opts ...pulumi.ResourceOption) (*ProxyClass, error) {
	if args == nil {
		args = &ProxyClassArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("tailscale.com/v1alpha1")
	args.Kind = pulumi.StringPtr("ProxyClass")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource ProxyClass
	err := ctx.RegisterResource("kubernetes:tailscale.com/v1alpha1:ProxyClass", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProxyClass gets an existing ProxyClass resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProxyClass(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProxyClassState, opts ...pulumi.ResourceOption) (*ProxyClass, error) {
	var resource ProxyClass
	err := ctx.ReadResource("kubernetes:tailscale.com/v1alpha1:ProxyClass", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ProxyClass resources.
type proxyClassState struct {
}

type ProxyClassState struct {
}

func (ProxyClassState) ElementType() reflect.Type {
	return reflect.TypeOf((*proxyClassState)(nil)).Elem()
}

type proxyClassArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `pulumi:"metadata"`
	Spec     *ProxyClassSpec    `pulumi:"spec"`
}

// The set of arguments for constructing a ProxyClass resource.
type ProxyClassArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPtrInput
	Spec     ProxyClassSpecPtrInput
}

func (ProxyClassArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*proxyClassArgs)(nil)).Elem()
}

type ProxyClassInput interface {
	pulumi.Input

	ToProxyClassOutput() ProxyClassOutput
	ToProxyClassOutputWithContext(ctx context.Context) ProxyClassOutput
}

func (*ProxyClass) ElementType() reflect.Type {
	return reflect.TypeOf((**ProxyClass)(nil)).Elem()
}

func (i *ProxyClass) ToProxyClassOutput() ProxyClassOutput {
	return i.ToProxyClassOutputWithContext(context.Background())
}

func (i *ProxyClass) ToProxyClassOutputWithContext(ctx context.Context) ProxyClassOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyClassOutput)
}

// ProxyClassArrayInput is an input type that accepts ProxyClassArray and ProxyClassArrayOutput values.
// You can construct a concrete instance of `ProxyClassArrayInput` via:
//
//	ProxyClassArray{ ProxyClassArgs{...} }
type ProxyClassArrayInput interface {
	pulumi.Input

	ToProxyClassArrayOutput() ProxyClassArrayOutput
	ToProxyClassArrayOutputWithContext(context.Context) ProxyClassArrayOutput
}

type ProxyClassArray []ProxyClassInput

func (ProxyClassArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProxyClass)(nil)).Elem()
}

func (i ProxyClassArray) ToProxyClassArrayOutput() ProxyClassArrayOutput {
	return i.ToProxyClassArrayOutputWithContext(context.Background())
}

func (i ProxyClassArray) ToProxyClassArrayOutputWithContext(ctx context.Context) ProxyClassArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyClassArrayOutput)
}

// ProxyClassMapInput is an input type that accepts ProxyClassMap and ProxyClassMapOutput values.
// You can construct a concrete instance of `ProxyClassMapInput` via:
//
//	ProxyClassMap{ "key": ProxyClassArgs{...} }
type ProxyClassMapInput interface {
	pulumi.Input

	ToProxyClassMapOutput() ProxyClassMapOutput
	ToProxyClassMapOutputWithContext(context.Context) ProxyClassMapOutput
}

type ProxyClassMap map[string]ProxyClassInput

func (ProxyClassMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProxyClass)(nil)).Elem()
}

func (i ProxyClassMap) ToProxyClassMapOutput() ProxyClassMapOutput {
	return i.ToProxyClassMapOutputWithContext(context.Background())
}

func (i ProxyClassMap) ToProxyClassMapOutputWithContext(ctx context.Context) ProxyClassMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyClassMapOutput)
}

type ProxyClassOutput struct{ *pulumi.OutputState }

func (ProxyClassOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProxyClass)(nil)).Elem()
}

func (o ProxyClassOutput) ToProxyClassOutput() ProxyClassOutput {
	return o
}

func (o ProxyClassOutput) ToProxyClassOutputWithContext(ctx context.Context) ProxyClassOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o ProxyClassOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ProxyClass) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o ProxyClassOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *ProxyClass) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o ProxyClassOutput) Metadata() metav1.ObjectMetaOutput {
	return o.ApplyT(func(v *ProxyClass) metav1.ObjectMetaOutput { return v.Metadata }).(metav1.ObjectMetaOutput)
}

func (o ProxyClassOutput) Spec() ProxyClassSpecOutput {
	return o.ApplyT(func(v *ProxyClass) ProxyClassSpecOutput { return v.Spec }).(ProxyClassSpecOutput)
}

func (o ProxyClassOutput) Status() ProxyClassStatusPtrOutput {
	return o.ApplyT(func(v *ProxyClass) ProxyClassStatusPtrOutput { return v.Status }).(ProxyClassStatusPtrOutput)
}

type ProxyClassArrayOutput struct{ *pulumi.OutputState }

func (ProxyClassArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProxyClass)(nil)).Elem()
}

func (o ProxyClassArrayOutput) ToProxyClassArrayOutput() ProxyClassArrayOutput {
	return o
}

func (o ProxyClassArrayOutput) ToProxyClassArrayOutputWithContext(ctx context.Context) ProxyClassArrayOutput {
	return o
}

func (o ProxyClassArrayOutput) Index(i pulumi.IntInput) ProxyClassOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ProxyClass {
		return vs[0].([]*ProxyClass)[vs[1].(int)]
	}).(ProxyClassOutput)
}

type ProxyClassMapOutput struct{ *pulumi.OutputState }

func (ProxyClassMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProxyClass)(nil)).Elem()
}

func (o ProxyClassMapOutput) ToProxyClassMapOutput() ProxyClassMapOutput {
	return o
}

func (o ProxyClassMapOutput) ToProxyClassMapOutputWithContext(ctx context.Context) ProxyClassMapOutput {
	return o
}

func (o ProxyClassMapOutput) MapIndex(k pulumi.StringInput) ProxyClassOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ProxyClass {
		return vs[0].(map[string]*ProxyClass)[vs[1].(string)]
	}).(ProxyClassOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyClassInput)(nil)).Elem(), &ProxyClass{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyClassArrayInput)(nil)).Elem(), ProxyClassArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyClassMapInput)(nil)).Elem(), ProxyClassMap{})
	pulumi.RegisterOutputType(ProxyClassOutput{})
	pulumi.RegisterOutputType(ProxyClassArrayOutput{})
	pulumi.RegisterOutputType(ProxyClassMapOutput{})
}
