// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ProxyGroupPolicy struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaOutput         `pulumi:"metadata"`
	Spec     ProxyGroupPolicySpecOutput      `pulumi:"spec"`
	Status   ProxyGroupPolicyStatusPtrOutput `pulumi:"status"`
}

// NewProxyGroupPolicy registers a new resource with the given unique name, arguments, and options.
func NewProxyGroupPolicy(ctx *pulumi.Context,
	name string, args *ProxyGroupPolicyArgs, opts ...pulumi.ResourceOption) (*ProxyGroupPolicy, error) {
	if args == nil {
		args = &ProxyGroupPolicyArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("tailscale.com/v1alpha1")
	args.Kind = pulumi.StringPtr("ProxyGroupPolicy")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource ProxyGroupPolicy
	err := ctx.RegisterResource("kubernetes:tailscale.com/v1alpha1:ProxyGroupPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProxyGroupPolicy gets an existing ProxyGroupPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProxyGroupPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProxyGroupPolicyState, opts ...pulumi.ResourceOption) (*ProxyGroupPolicy, error) {
	var resource ProxyGroupPolicy
	err := ctx.ReadResource("kubernetes:tailscale.com/v1alpha1:ProxyGroupPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ProxyGroupPolicy resources.
type proxyGroupPolicyState struct {
}

type ProxyGroupPolicyState struct {
}

func (ProxyGroupPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*proxyGroupPolicyState)(nil)).Elem()
}

type proxyGroupPolicyArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta    `pulumi:"metadata"`
	Spec     *ProxyGroupPolicySpec `pulumi:"spec"`
}

// The set of arguments for constructing a ProxyGroupPolicy resource.
type ProxyGroupPolicyArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPtrInput
	Spec     ProxyGroupPolicySpecPtrInput
}

func (ProxyGroupPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*proxyGroupPolicyArgs)(nil)).Elem()
}

type ProxyGroupPolicyInput interface {
	pulumi.Input

	ToProxyGroupPolicyOutput() ProxyGroupPolicyOutput
	ToProxyGroupPolicyOutputWithContext(ctx context.Context) ProxyGroupPolicyOutput
}

func (*ProxyGroupPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**ProxyGroupPolicy)(nil)).Elem()
}

func (i *ProxyGroupPolicy) ToProxyGroupPolicyOutput() ProxyGroupPolicyOutput {
	return i.ToProxyGroupPolicyOutputWithContext(context.Background())
}

func (i *ProxyGroupPolicy) ToProxyGroupPolicyOutputWithContext(ctx context.Context) ProxyGroupPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyGroupPolicyOutput)
}

// ProxyGroupPolicyArrayInput is an input type that accepts ProxyGroupPolicyArray and ProxyGroupPolicyArrayOutput values.
// You can construct a concrete instance of `ProxyGroupPolicyArrayInput` via:
//
//	ProxyGroupPolicyArray{ ProxyGroupPolicyArgs{...} }
type ProxyGroupPolicyArrayInput interface {
	pulumi.Input

	ToProxyGroupPolicyArrayOutput() ProxyGroupPolicyArrayOutput
	ToProxyGroupPolicyArrayOutputWithContext(context.Context) ProxyGroupPolicyArrayOutput
}

type ProxyGroupPolicyArray []ProxyGroupPolicyInput

func (ProxyGroupPolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProxyGroupPolicy)(nil)).Elem()
}

func (i ProxyGroupPolicyArray) ToProxyGroupPolicyArrayOutput() ProxyGroupPolicyArrayOutput {
	return i.ToProxyGroupPolicyArrayOutputWithContext(context.Background())
}

func (i ProxyGroupPolicyArray) ToProxyGroupPolicyArrayOutputWithContext(ctx context.Context) ProxyGroupPolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyGroupPolicyArrayOutput)
}

// ProxyGroupPolicyMapInput is an input type that accepts ProxyGroupPolicyMap and ProxyGroupPolicyMapOutput values.
// You can construct a concrete instance of `ProxyGroupPolicyMapInput` via:
//
//	ProxyGroupPolicyMap{ "key": ProxyGroupPolicyArgs{...} }
type ProxyGroupPolicyMapInput interface {
	pulumi.Input

	ToProxyGroupPolicyMapOutput() ProxyGroupPolicyMapOutput
	ToProxyGroupPolicyMapOutputWithContext(context.Context) ProxyGroupPolicyMapOutput
}

type ProxyGroupPolicyMap map[string]ProxyGroupPolicyInput

func (ProxyGroupPolicyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProxyGroupPolicy)(nil)).Elem()
}

func (i ProxyGroupPolicyMap) ToProxyGroupPolicyMapOutput() ProxyGroupPolicyMapOutput {
	return i.ToProxyGroupPolicyMapOutputWithContext(context.Background())
}

func (i ProxyGroupPolicyMap) ToProxyGroupPolicyMapOutputWithContext(ctx context.Context) ProxyGroupPolicyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyGroupPolicyMapOutput)
}

type ProxyGroupPolicyOutput struct{ *pulumi.OutputState }

func (ProxyGroupPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProxyGroupPolicy)(nil)).Elem()
}

func (o ProxyGroupPolicyOutput) ToProxyGroupPolicyOutput() ProxyGroupPolicyOutput {
	return o
}

func (o ProxyGroupPolicyOutput) ToProxyGroupPolicyOutputWithContext(ctx context.Context) ProxyGroupPolicyOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o ProxyGroupPolicyOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ProxyGroupPolicy) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o ProxyGroupPolicyOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *ProxyGroupPolicy) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o ProxyGroupPolicyOutput) Metadata() metav1.ObjectMetaOutput {
	return o.ApplyT(func(v *ProxyGroupPolicy) metav1.ObjectMetaOutput { return v.Metadata }).(metav1.ObjectMetaOutput)
}

func (o ProxyGroupPolicyOutput) Spec() ProxyGroupPolicySpecOutput {
	return o.ApplyT(func(v *ProxyGroupPolicy) ProxyGroupPolicySpecOutput { return v.Spec }).(ProxyGroupPolicySpecOutput)
}

func (o ProxyGroupPolicyOutput) Status() ProxyGroupPolicyStatusPtrOutput {
	return o.ApplyT(func(v *ProxyGroupPolicy) ProxyGroupPolicyStatusPtrOutput { return v.Status }).(ProxyGroupPolicyStatusPtrOutput)
}

type ProxyGroupPolicyArrayOutput struct{ *pulumi.OutputState }

func (ProxyGroupPolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProxyGroupPolicy)(nil)).Elem()
}

func (o ProxyGroupPolicyArrayOutput) ToProxyGroupPolicyArrayOutput() ProxyGroupPolicyArrayOutput {
	return o
}

func (o ProxyGroupPolicyArrayOutput) ToProxyGroupPolicyArrayOutputWithContext(ctx context.Context) ProxyGroupPolicyArrayOutput {
	return o
}

func (o ProxyGroupPolicyArrayOutput) Index(i pulumi.IntInput) ProxyGroupPolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ProxyGroupPolicy {
		return vs[0].([]*ProxyGroupPolicy)[vs[1].(int)]
	}).(ProxyGroupPolicyOutput)
}

type ProxyGroupPolicyMapOutput struct{ *pulumi.OutputState }

func (ProxyGroupPolicyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProxyGroupPolicy)(nil)).Elem()
}

func (o ProxyGroupPolicyMapOutput) ToProxyGroupPolicyMapOutput() ProxyGroupPolicyMapOutput {
	return o
}

func (o ProxyGroupPolicyMapOutput) ToProxyGroupPolicyMapOutputWithContext(ctx context.Context) ProxyGroupPolicyMapOutput {
	return o
}

func (o ProxyGroupPolicyMapOutput) MapIndex(k pulumi.StringInput) ProxyGroupPolicyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ProxyGroupPolicy {
		return vs[0].(map[string]*ProxyGroupPolicy)[vs[1].(string)]
	}).(ProxyGroupPolicyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyGroupPolicyInput)(nil)).Elem(), &ProxyGroupPolicy{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyGroupPolicyArrayInput)(nil)).Elem(), ProxyGroupPolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyGroupPolicyMapInput)(nil)).Elem(), ProxyGroupPolicyMap{})
	pulumi.RegisterOutputType(ProxyGroupPolicyOutput{})
	pulumi.RegisterOutputType(ProxyGroupPolicyArrayOutput{})
	pulumi.RegisterOutputType(ProxyGroupPolicyMapOutput{})
}
