// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Patch resources are used to modify existing Kubernetes resources by using
// Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
// one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
// Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
// [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
// additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
type ProxyGroupPolicyPatch struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrOutput      `pulumi:"metadata"`
	Spec     ProxyGroupPolicySpecPatchPtrOutput   `pulumi:"spec"`
	Status   ProxyGroupPolicyStatusPatchPtrOutput `pulumi:"status"`
}

// NewProxyGroupPolicyPatch registers a new resource with the given unique name, arguments, and options.
func NewProxyGroupPolicyPatch(ctx *pulumi.Context,
	name string, args *ProxyGroupPolicyPatchArgs, opts ...pulumi.ResourceOption) (*ProxyGroupPolicyPatch, error) {
	if args == nil {
		args = &ProxyGroupPolicyPatchArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("tailscale.com/v1alpha1")
	args.Kind = pulumi.StringPtr("ProxyGroupPolicy")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource ProxyGroupPolicyPatch
	err := ctx.RegisterResource("kubernetes:tailscale.com/v1alpha1:ProxyGroupPolicyPatch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProxyGroupPolicyPatch gets an existing ProxyGroupPolicyPatch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProxyGroupPolicyPatch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProxyGroupPolicyPatchState, opts ...pulumi.ResourceOption) (*ProxyGroupPolicyPatch, error) {
	var resource ProxyGroupPolicyPatch
	err := ctx.ReadResource("kubernetes:tailscale.com/v1alpha1:ProxyGroupPolicyPatch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ProxyGroupPolicyPatch resources.
type proxyGroupPolicyPatchState struct {
}

type ProxyGroupPolicyPatchState struct {
}

func (ProxyGroupPolicyPatchState) ElementType() reflect.Type {
	return reflect.TypeOf((*proxyGroupPolicyPatchState)(nil)).Elem()
}

type proxyGroupPolicyPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMetaPatch    `pulumi:"metadata"`
	Spec     *ProxyGroupPolicySpecPatch `pulumi:"spec"`
}

// The set of arguments for constructing a ProxyGroupPolicyPatch resource.
type ProxyGroupPolicyPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrInput
	Spec     ProxyGroupPolicySpecPatchPtrInput
}

func (ProxyGroupPolicyPatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*proxyGroupPolicyPatchArgs)(nil)).Elem()
}

type ProxyGroupPolicyPatchInput interface {
	pulumi.Input

	ToProxyGroupPolicyPatchOutput() ProxyGroupPolicyPatchOutput
	ToProxyGroupPolicyPatchOutputWithContext(ctx context.Context) ProxyGroupPolicyPatchOutput
}

func (*ProxyGroupPolicyPatch) ElementType() reflect.Type {
	return reflect.TypeOf((**ProxyGroupPolicyPatch)(nil)).Elem()
}

func (i *ProxyGroupPolicyPatch) ToProxyGroupPolicyPatchOutput() ProxyGroupPolicyPatchOutput {
	return i.ToProxyGroupPolicyPatchOutputWithContext(context.Background())
}

func (i *ProxyGroupPolicyPatch) ToProxyGroupPolicyPatchOutputWithContext(ctx context.Context) ProxyGroupPolicyPatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyGroupPolicyPatchOutput)
}

// ProxyGroupPolicyPatchArrayInput is an input type that accepts ProxyGroupPolicyPatchArray and ProxyGroupPolicyPatchArrayOutput values.
// You can construct a concrete instance of `ProxyGroupPolicyPatchArrayInput` via:
//
//	ProxyGroupPolicyPatchArray{ ProxyGroupPolicyPatchArgs{...} }
type ProxyGroupPolicyPatchArrayInput interface {
	pulumi.Input

	ToProxyGroupPolicyPatchArrayOutput() ProxyGroupPolicyPatchArrayOutput
	ToProxyGroupPolicyPatchArrayOutputWithContext(context.Context) ProxyGroupPolicyPatchArrayOutput
}

type ProxyGroupPolicyPatchArray []ProxyGroupPolicyPatchInput

func (ProxyGroupPolicyPatchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProxyGroupPolicyPatch)(nil)).Elem()
}

func (i ProxyGroupPolicyPatchArray) ToProxyGroupPolicyPatchArrayOutput() ProxyGroupPolicyPatchArrayOutput {
	return i.ToProxyGroupPolicyPatchArrayOutputWithContext(context.Background())
}

func (i ProxyGroupPolicyPatchArray) ToProxyGroupPolicyPatchArrayOutputWithContext(ctx context.Context) ProxyGroupPolicyPatchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyGroupPolicyPatchArrayOutput)
}

// ProxyGroupPolicyPatchMapInput is an input type that accepts ProxyGroupPolicyPatchMap and ProxyGroupPolicyPatchMapOutput values.
// You can construct a concrete instance of `ProxyGroupPolicyPatchMapInput` via:
//
//	ProxyGroupPolicyPatchMap{ "key": ProxyGroupPolicyPatchArgs{...} }
type ProxyGroupPolicyPatchMapInput interface {
	pulumi.Input

	ToProxyGroupPolicyPatchMapOutput() ProxyGroupPolicyPatchMapOutput
	ToProxyGroupPolicyPatchMapOutputWithContext(context.Context) ProxyGroupPolicyPatchMapOutput
}

type ProxyGroupPolicyPatchMap map[string]ProxyGroupPolicyPatchInput

func (ProxyGroupPolicyPatchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProxyGroupPolicyPatch)(nil)).Elem()
}

func (i ProxyGroupPolicyPatchMap) ToProxyGroupPolicyPatchMapOutput() ProxyGroupPolicyPatchMapOutput {
	return i.ToProxyGroupPolicyPatchMapOutputWithContext(context.Background())
}

func (i ProxyGroupPolicyPatchMap) ToProxyGroupPolicyPatchMapOutputWithContext(ctx context.Context) ProxyGroupPolicyPatchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyGroupPolicyPatchMapOutput)
}

type ProxyGroupPolicyPatchOutput struct{ *pulumi.OutputState }

func (ProxyGroupPolicyPatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProxyGroupPolicyPatch)(nil)).Elem()
}

func (o ProxyGroupPolicyPatchOutput) ToProxyGroupPolicyPatchOutput() ProxyGroupPolicyPatchOutput {
	return o
}

func (o ProxyGroupPolicyPatchOutput) ToProxyGroupPolicyPatchOutputWithContext(ctx context.Context) ProxyGroupPolicyPatchOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o ProxyGroupPolicyPatchOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProxyGroupPolicyPatch) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o ProxyGroupPolicyPatchOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProxyGroupPolicyPatch) pulumi.StringPtrOutput { return v.Kind }).(pulumi.StringPtrOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o ProxyGroupPolicyPatchOutput) Metadata() metav1.ObjectMetaPatchPtrOutput {
	return o.ApplyT(func(v *ProxyGroupPolicyPatch) metav1.ObjectMetaPatchPtrOutput { return v.Metadata }).(metav1.ObjectMetaPatchPtrOutput)
}

func (o ProxyGroupPolicyPatchOutput) Spec() ProxyGroupPolicySpecPatchPtrOutput {
	return o.ApplyT(func(v *ProxyGroupPolicyPatch) ProxyGroupPolicySpecPatchPtrOutput { return v.Spec }).(ProxyGroupPolicySpecPatchPtrOutput)
}

func (o ProxyGroupPolicyPatchOutput) Status() ProxyGroupPolicyStatusPatchPtrOutput {
	return o.ApplyT(func(v *ProxyGroupPolicyPatch) ProxyGroupPolicyStatusPatchPtrOutput { return v.Status }).(ProxyGroupPolicyStatusPatchPtrOutput)
}

type ProxyGroupPolicyPatchArrayOutput struct{ *pulumi.OutputState }

func (ProxyGroupPolicyPatchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProxyGroupPolicyPatch)(nil)).Elem()
}

func (o ProxyGroupPolicyPatchArrayOutput) ToProxyGroupPolicyPatchArrayOutput() ProxyGroupPolicyPatchArrayOutput {
	return o
}

func (o ProxyGroupPolicyPatchArrayOutput) ToProxyGroupPolicyPatchArrayOutputWithContext(ctx context.Context) ProxyGroupPolicyPatchArrayOutput {
	return o
}

func (o ProxyGroupPolicyPatchArrayOutput) Index(i pulumi.IntInput) ProxyGroupPolicyPatchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ProxyGroupPolicyPatch {
		return vs[0].([]*ProxyGroupPolicyPatch)[vs[1].(int)]
	}).(ProxyGroupPolicyPatchOutput)
}

type ProxyGroupPolicyPatchMapOutput struct{ *pulumi.OutputState }

func (ProxyGroupPolicyPatchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProxyGroupPolicyPatch)(nil)).Elem()
}

func (o ProxyGroupPolicyPatchMapOutput) ToProxyGroupPolicyPatchMapOutput() ProxyGroupPolicyPatchMapOutput {
	return o
}

func (o ProxyGroupPolicyPatchMapOutput) ToProxyGroupPolicyPatchMapOutputWithContext(ctx context.Context) ProxyGroupPolicyPatchMapOutput {
	return o
}

func (o ProxyGroupPolicyPatchMapOutput) MapIndex(k pulumi.StringInput) ProxyGroupPolicyPatchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ProxyGroupPolicyPatch {
		return vs[0].(map[string]*ProxyGroupPolicyPatch)[vs[1].(string)]
	}).(ProxyGroupPolicyPatchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyGroupPolicyPatchInput)(nil)).Elem(), &ProxyGroupPolicyPatch{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyGroupPolicyPatchArrayInput)(nil)).Elem(), ProxyGroupPolicyPatchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyGroupPolicyPatchMapInput)(nil)).Elem(), ProxyGroupPolicyPatchMap{})
	pulumi.RegisterOutputType(ProxyGroupPolicyPatchOutput{})
	pulumi.RegisterOutputType(ProxyGroupPolicyPatchArrayOutput{})
	pulumi.RegisterOutputType(ProxyGroupPolicyPatchMapOutput{})
}
