// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Patch resources are used to modify existing Kubernetes resources by using
// Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
// one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
// Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
// [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
// additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
// ProxyGroup defines a set of Tailscale devices that will act as proxies.
// Depending on spec.Type, it can be a group of egress, ingress, or kube-apiserver
// proxies. In addition to running a highly available set of proxies, ingress
// and egress ProxyGroups also allow for serving many annotated Services from a
// single set of proxies to minimise resource consumption.
//
// For ingress and egress, use the tailscale.com/proxy-group annotation on a
// Service to specify that the proxy should be implemented by a ProxyGroup
// instead of a single dedicated proxy.
//
// More info:
// * https://tailscale.com/kb/1438/kubernetes-operator-cluster-egress
// * https://tailscale.com/kb/1439/kubernetes-operator-cluster-ingress
//
// For kube-apiserver, the ProxyGroup is a standalone resource. Use the
// spec.kubeAPIServer field to configure options specific to the kube-apiserver
// ProxyGroup type.
type ProxyGroupPatch struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrOutput `pulumi:"metadata"`
	Spec     ProxyGroupSpecPatchPtrOutput    `pulumi:"spec"`
	Status   ProxyGroupStatusPatchPtrOutput  `pulumi:"status"`
}

// NewProxyGroupPatch registers a new resource with the given unique name, arguments, and options.
func NewProxyGroupPatch(ctx *pulumi.Context,
	name string, args *ProxyGroupPatchArgs, opts ...pulumi.ResourceOption) (*ProxyGroupPatch, error) {
	if args == nil {
		args = &ProxyGroupPatchArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("tailscale.com/v1alpha1")
	args.Kind = pulumi.StringPtr("ProxyGroup")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource ProxyGroupPatch
	err := ctx.RegisterResource("kubernetes:tailscale.com/v1alpha1:ProxyGroupPatch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProxyGroupPatch gets an existing ProxyGroupPatch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProxyGroupPatch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProxyGroupPatchState, opts ...pulumi.ResourceOption) (*ProxyGroupPatch, error) {
	var resource ProxyGroupPatch
	err := ctx.ReadResource("kubernetes:tailscale.com/v1alpha1:ProxyGroupPatch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ProxyGroupPatch resources.
type proxyGroupPatchState struct {
}

type ProxyGroupPatchState struct {
}

func (ProxyGroupPatchState) ElementType() reflect.Type {
	return reflect.TypeOf((*proxyGroupPatchState)(nil)).Elem()
}

type proxyGroupPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMetaPatch `pulumi:"metadata"`
	Spec     *ProxyGroupSpecPatch    `pulumi:"spec"`
}

// The set of arguments for constructing a ProxyGroupPatch resource.
type ProxyGroupPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrInput
	Spec     ProxyGroupSpecPatchPtrInput
}

func (ProxyGroupPatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*proxyGroupPatchArgs)(nil)).Elem()
}

type ProxyGroupPatchInput interface {
	pulumi.Input

	ToProxyGroupPatchOutput() ProxyGroupPatchOutput
	ToProxyGroupPatchOutputWithContext(ctx context.Context) ProxyGroupPatchOutput
}

func (*ProxyGroupPatch) ElementType() reflect.Type {
	return reflect.TypeOf((**ProxyGroupPatch)(nil)).Elem()
}

func (i *ProxyGroupPatch) ToProxyGroupPatchOutput() ProxyGroupPatchOutput {
	return i.ToProxyGroupPatchOutputWithContext(context.Background())
}

func (i *ProxyGroupPatch) ToProxyGroupPatchOutputWithContext(ctx context.Context) ProxyGroupPatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyGroupPatchOutput)
}

// ProxyGroupPatchArrayInput is an input type that accepts ProxyGroupPatchArray and ProxyGroupPatchArrayOutput values.
// You can construct a concrete instance of `ProxyGroupPatchArrayInput` via:
//
//	ProxyGroupPatchArray{ ProxyGroupPatchArgs{...} }
type ProxyGroupPatchArrayInput interface {
	pulumi.Input

	ToProxyGroupPatchArrayOutput() ProxyGroupPatchArrayOutput
	ToProxyGroupPatchArrayOutputWithContext(context.Context) ProxyGroupPatchArrayOutput
}

type ProxyGroupPatchArray []ProxyGroupPatchInput

func (ProxyGroupPatchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProxyGroupPatch)(nil)).Elem()
}

func (i ProxyGroupPatchArray) ToProxyGroupPatchArrayOutput() ProxyGroupPatchArrayOutput {
	return i.ToProxyGroupPatchArrayOutputWithContext(context.Background())
}

func (i ProxyGroupPatchArray) ToProxyGroupPatchArrayOutputWithContext(ctx context.Context) ProxyGroupPatchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyGroupPatchArrayOutput)
}

// ProxyGroupPatchMapInput is an input type that accepts ProxyGroupPatchMap and ProxyGroupPatchMapOutput values.
// You can construct a concrete instance of `ProxyGroupPatchMapInput` via:
//
//	ProxyGroupPatchMap{ "key": ProxyGroupPatchArgs{...} }
type ProxyGroupPatchMapInput interface {
	pulumi.Input

	ToProxyGroupPatchMapOutput() ProxyGroupPatchMapOutput
	ToProxyGroupPatchMapOutputWithContext(context.Context) ProxyGroupPatchMapOutput
}

type ProxyGroupPatchMap map[string]ProxyGroupPatchInput

func (ProxyGroupPatchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProxyGroupPatch)(nil)).Elem()
}

func (i ProxyGroupPatchMap) ToProxyGroupPatchMapOutput() ProxyGroupPatchMapOutput {
	return i.ToProxyGroupPatchMapOutputWithContext(context.Background())
}

func (i ProxyGroupPatchMap) ToProxyGroupPatchMapOutputWithContext(ctx context.Context) ProxyGroupPatchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyGroupPatchMapOutput)
}

type ProxyGroupPatchOutput struct{ *pulumi.OutputState }

func (ProxyGroupPatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProxyGroupPatch)(nil)).Elem()
}

func (o ProxyGroupPatchOutput) ToProxyGroupPatchOutput() ProxyGroupPatchOutput {
	return o
}

func (o ProxyGroupPatchOutput) ToProxyGroupPatchOutputWithContext(ctx context.Context) ProxyGroupPatchOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o ProxyGroupPatchOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProxyGroupPatch) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o ProxyGroupPatchOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProxyGroupPatch) pulumi.StringPtrOutput { return v.Kind }).(pulumi.StringPtrOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o ProxyGroupPatchOutput) Metadata() metav1.ObjectMetaPatchPtrOutput {
	return o.ApplyT(func(v *ProxyGroupPatch) metav1.ObjectMetaPatchPtrOutput { return v.Metadata }).(metav1.ObjectMetaPatchPtrOutput)
}

func (o ProxyGroupPatchOutput) Spec() ProxyGroupSpecPatchPtrOutput {
	return o.ApplyT(func(v *ProxyGroupPatch) ProxyGroupSpecPatchPtrOutput { return v.Spec }).(ProxyGroupSpecPatchPtrOutput)
}

func (o ProxyGroupPatchOutput) Status() ProxyGroupStatusPatchPtrOutput {
	return o.ApplyT(func(v *ProxyGroupPatch) ProxyGroupStatusPatchPtrOutput { return v.Status }).(ProxyGroupStatusPatchPtrOutput)
}

type ProxyGroupPatchArrayOutput struct{ *pulumi.OutputState }

func (ProxyGroupPatchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProxyGroupPatch)(nil)).Elem()
}

func (o ProxyGroupPatchArrayOutput) ToProxyGroupPatchArrayOutput() ProxyGroupPatchArrayOutput {
	return o
}

func (o ProxyGroupPatchArrayOutput) ToProxyGroupPatchArrayOutputWithContext(ctx context.Context) ProxyGroupPatchArrayOutput {
	return o
}

func (o ProxyGroupPatchArrayOutput) Index(i pulumi.IntInput) ProxyGroupPatchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ProxyGroupPatch {
		return vs[0].([]*ProxyGroupPatch)[vs[1].(int)]
	}).(ProxyGroupPatchOutput)
}

type ProxyGroupPatchMapOutput struct{ *pulumi.OutputState }

func (ProxyGroupPatchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProxyGroupPatch)(nil)).Elem()
}

func (o ProxyGroupPatchMapOutput) ToProxyGroupPatchMapOutput() ProxyGroupPatchMapOutput {
	return o
}

func (o ProxyGroupPatchMapOutput) ToProxyGroupPatchMapOutputWithContext(ctx context.Context) ProxyGroupPatchMapOutput {
	return o
}

func (o ProxyGroupPatchMapOutput) MapIndex(k pulumi.StringInput) ProxyGroupPatchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ProxyGroupPatch {
		return vs[0].(map[string]*ProxyGroupPatch)[vs[1].(string)]
	}).(ProxyGroupPatchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyGroupPatchInput)(nil)).Elem(), &ProxyGroupPatch{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyGroupPatchArrayInput)(nil)).Elem(), ProxyGroupPatchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyGroupPatchMapInput)(nil)).Elem(), ProxyGroupPatchMap{})
	pulumi.RegisterOutputType(ProxyGroupPatchOutput{})
	pulumi.RegisterOutputType(ProxyGroupPatchArrayOutput{})
	pulumi.RegisterOutputType(ProxyGroupPatchMapOutput{})
}
