// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	"errors"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ProxyGroupList is a list of ProxyGroup
type ProxyGroupList struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// List of proxygroups. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items ProxyGroupTypeArrayOutput `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaOutput `pulumi:"metadata"`
}

// NewProxyGroupList registers a new resource with the given unique name, arguments, and options.
func NewProxyGroupList(ctx *pulumi.Context,
	name string, args *ProxyGroupListArgs, opts ...pulumi.ResourceOption) (*ProxyGroupList, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Items == nil {
		return nil, errors.New("invalid value for required argument 'Items'")
	}
	args.ApiVersion = pulumi.StringPtr("tailscale.com/v1alpha1")
	args.Kind = pulumi.StringPtr("ProxyGroupList")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource ProxyGroupList
	err := ctx.RegisterResource("kubernetes:tailscale.com/v1alpha1:ProxyGroupList", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProxyGroupList gets an existing ProxyGroupList resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProxyGroupList(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProxyGroupListState, opts ...pulumi.ResourceOption) (*ProxyGroupList, error) {
	var resource ProxyGroupList
	err := ctx.ReadResource("kubernetes:tailscale.com/v1alpha1:ProxyGroupList", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ProxyGroupList resources.
type proxyGroupListState struct {
}

type ProxyGroupListState struct {
}

func (ProxyGroupListState) ElementType() reflect.Type {
	return reflect.TypeOf((*proxyGroupListState)(nil)).Elem()
}

type proxyGroupListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// List of proxygroups. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items []ProxyGroupType `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `pulumi:"metadata"`
}

// The set of arguments for constructing a ProxyGroupList resource.
type ProxyGroupListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// List of proxygroups. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items ProxyGroupTypeArrayInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaPtrInput
}

func (ProxyGroupListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*proxyGroupListArgs)(nil)).Elem()
}

type ProxyGroupListInput interface {
	pulumi.Input

	ToProxyGroupListOutput() ProxyGroupListOutput
	ToProxyGroupListOutputWithContext(ctx context.Context) ProxyGroupListOutput
}

func (*ProxyGroupList) ElementType() reflect.Type {
	return reflect.TypeOf((**ProxyGroupList)(nil)).Elem()
}

func (i *ProxyGroupList) ToProxyGroupListOutput() ProxyGroupListOutput {
	return i.ToProxyGroupListOutputWithContext(context.Background())
}

func (i *ProxyGroupList) ToProxyGroupListOutputWithContext(ctx context.Context) ProxyGroupListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyGroupListOutput)
}

// ProxyGroupListArrayInput is an input type that accepts ProxyGroupListArray and ProxyGroupListArrayOutput values.
// You can construct a concrete instance of `ProxyGroupListArrayInput` via:
//
//	ProxyGroupListArray{ ProxyGroupListArgs{...} }
type ProxyGroupListArrayInput interface {
	pulumi.Input

	ToProxyGroupListArrayOutput() ProxyGroupListArrayOutput
	ToProxyGroupListArrayOutputWithContext(context.Context) ProxyGroupListArrayOutput
}

type ProxyGroupListArray []ProxyGroupListInput

func (ProxyGroupListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProxyGroupList)(nil)).Elem()
}

func (i ProxyGroupListArray) ToProxyGroupListArrayOutput() ProxyGroupListArrayOutput {
	return i.ToProxyGroupListArrayOutputWithContext(context.Background())
}

func (i ProxyGroupListArray) ToProxyGroupListArrayOutputWithContext(ctx context.Context) ProxyGroupListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyGroupListArrayOutput)
}

// ProxyGroupListMapInput is an input type that accepts ProxyGroupListMap and ProxyGroupListMapOutput values.
// You can construct a concrete instance of `ProxyGroupListMapInput` via:
//
//	ProxyGroupListMap{ "key": ProxyGroupListArgs{...} }
type ProxyGroupListMapInput interface {
	pulumi.Input

	ToProxyGroupListMapOutput() ProxyGroupListMapOutput
	ToProxyGroupListMapOutputWithContext(context.Context) ProxyGroupListMapOutput
}

type ProxyGroupListMap map[string]ProxyGroupListInput

func (ProxyGroupListMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProxyGroupList)(nil)).Elem()
}

func (i ProxyGroupListMap) ToProxyGroupListMapOutput() ProxyGroupListMapOutput {
	return i.ToProxyGroupListMapOutputWithContext(context.Background())
}

func (i ProxyGroupListMap) ToProxyGroupListMapOutputWithContext(ctx context.Context) ProxyGroupListMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProxyGroupListMapOutput)
}

type ProxyGroupListOutput struct{ *pulumi.OutputState }

func (ProxyGroupListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProxyGroupList)(nil)).Elem()
}

func (o ProxyGroupListOutput) ToProxyGroupListOutput() ProxyGroupListOutput {
	return o
}

func (o ProxyGroupListOutput) ToProxyGroupListOutputWithContext(ctx context.Context) ProxyGroupListOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o ProxyGroupListOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ProxyGroupList) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// List of proxygroups. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
func (o ProxyGroupListOutput) Items() ProxyGroupTypeArrayOutput {
	return o.ApplyT(func(v *ProxyGroupList) ProxyGroupTypeArrayOutput { return v.Items }).(ProxyGroupTypeArrayOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o ProxyGroupListOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *ProxyGroupList) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o ProxyGroupListOutput) Metadata() metav1.ListMetaOutput {
	return o.ApplyT(func(v *ProxyGroupList) metav1.ListMetaOutput { return v.Metadata }).(metav1.ListMetaOutput)
}

type ProxyGroupListArrayOutput struct{ *pulumi.OutputState }

func (ProxyGroupListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProxyGroupList)(nil)).Elem()
}

func (o ProxyGroupListArrayOutput) ToProxyGroupListArrayOutput() ProxyGroupListArrayOutput {
	return o
}

func (o ProxyGroupListArrayOutput) ToProxyGroupListArrayOutputWithContext(ctx context.Context) ProxyGroupListArrayOutput {
	return o
}

func (o ProxyGroupListArrayOutput) Index(i pulumi.IntInput) ProxyGroupListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ProxyGroupList {
		return vs[0].([]*ProxyGroupList)[vs[1].(int)]
	}).(ProxyGroupListOutput)
}

type ProxyGroupListMapOutput struct{ *pulumi.OutputState }

func (ProxyGroupListMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProxyGroupList)(nil)).Elem()
}

func (o ProxyGroupListMapOutput) ToProxyGroupListMapOutput() ProxyGroupListMapOutput {
	return o
}

func (o ProxyGroupListMapOutput) ToProxyGroupListMapOutputWithContext(ctx context.Context) ProxyGroupListMapOutput {
	return o
}

func (o ProxyGroupListMapOutput) MapIndex(k pulumi.StringInput) ProxyGroupListOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ProxyGroupList {
		return vs[0].(map[string]*ProxyGroupList)[vs[1].(string)]
	}).(ProxyGroupListOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyGroupListInput)(nil)).Elem(), &ProxyGroupList{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyGroupListArrayInput)(nil)).Elem(), ProxyGroupListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProxyGroupListMapInput)(nil)).Elem(), ProxyGroupListMap{})
	pulumi.RegisterOutputType(ProxyGroupListOutput{})
	pulumi.RegisterOutputType(ProxyGroupListArrayOutput{})
	pulumi.RegisterOutputType(ProxyGroupListMapOutput{})
}
