// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Recorder defines a tsrecorder device for recording SSH sessions. By default,
// it will store recordings in a local ephemeral volume. If you want to persist
// recordings, you can configure an S3-compatible API for storage.
//
// More info: https://tailscale.com/kb/1484/kubernetes-operator-deploying-tsrecorder
type Recorder struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaOutput `pulumi:"metadata"`
	Spec     RecorderSpecOutput      `pulumi:"spec"`
	Status   RecorderStatusPtrOutput `pulumi:"status"`
}

// NewRecorder registers a new resource with the given unique name, arguments, and options.
func NewRecorder(ctx *pulumi.Context,
	name string, args *RecorderArgs, opts ...pulumi.ResourceOption) (*Recorder, error) {
	if args == nil {
		args = &RecorderArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("tailscale.com/v1alpha1")
	args.Kind = pulumi.StringPtr("Recorder")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource Recorder
	err := ctx.RegisterResource("kubernetes:tailscale.com/v1alpha1:Recorder", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRecorder gets an existing Recorder resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRecorder(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RecorderState, opts ...pulumi.ResourceOption) (*Recorder, error) {
	var resource Recorder
	err := ctx.ReadResource("kubernetes:tailscale.com/v1alpha1:Recorder", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Recorder resources.
type recorderState struct {
}

type RecorderState struct {
}

func (RecorderState) ElementType() reflect.Type {
	return reflect.TypeOf((*recorderState)(nil)).Elem()
}

type recorderArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `pulumi:"metadata"`
	Spec     *RecorderSpec      `pulumi:"spec"`
}

// The set of arguments for constructing a Recorder resource.
type RecorderArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPtrInput
	Spec     RecorderSpecPtrInput
}

func (RecorderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*recorderArgs)(nil)).Elem()
}

type RecorderInput interface {
	pulumi.Input

	ToRecorderOutput() RecorderOutput
	ToRecorderOutputWithContext(ctx context.Context) RecorderOutput
}

func (*Recorder) ElementType() reflect.Type {
	return reflect.TypeOf((**Recorder)(nil)).Elem()
}

func (i *Recorder) ToRecorderOutput() RecorderOutput {
	return i.ToRecorderOutputWithContext(context.Background())
}

func (i *Recorder) ToRecorderOutputWithContext(ctx context.Context) RecorderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecorderOutput)
}

// RecorderArrayInput is an input type that accepts RecorderArray and RecorderArrayOutput values.
// You can construct a concrete instance of `RecorderArrayInput` via:
//
//	RecorderArray{ RecorderArgs{...} }
type RecorderArrayInput interface {
	pulumi.Input

	ToRecorderArrayOutput() RecorderArrayOutput
	ToRecorderArrayOutputWithContext(context.Context) RecorderArrayOutput
}

type RecorderArray []RecorderInput

func (RecorderArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Recorder)(nil)).Elem()
}

func (i RecorderArray) ToRecorderArrayOutput() RecorderArrayOutput {
	return i.ToRecorderArrayOutputWithContext(context.Background())
}

func (i RecorderArray) ToRecorderArrayOutputWithContext(ctx context.Context) RecorderArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecorderArrayOutput)
}

// RecorderMapInput is an input type that accepts RecorderMap and RecorderMapOutput values.
// You can construct a concrete instance of `RecorderMapInput` via:
//
//	RecorderMap{ "key": RecorderArgs{...} }
type RecorderMapInput interface {
	pulumi.Input

	ToRecorderMapOutput() RecorderMapOutput
	ToRecorderMapOutputWithContext(context.Context) RecorderMapOutput
}

type RecorderMap map[string]RecorderInput

func (RecorderMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Recorder)(nil)).Elem()
}

func (i RecorderMap) ToRecorderMapOutput() RecorderMapOutput {
	return i.ToRecorderMapOutputWithContext(context.Background())
}

func (i RecorderMap) ToRecorderMapOutputWithContext(ctx context.Context) RecorderMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecorderMapOutput)
}

type RecorderOutput struct{ *pulumi.OutputState }

func (RecorderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Recorder)(nil)).Elem()
}

func (o RecorderOutput) ToRecorderOutput() RecorderOutput {
	return o
}

func (o RecorderOutput) ToRecorderOutputWithContext(ctx context.Context) RecorderOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o RecorderOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *Recorder) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o RecorderOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *Recorder) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o RecorderOutput) Metadata() metav1.ObjectMetaOutput {
	return o.ApplyT(func(v *Recorder) metav1.ObjectMetaOutput { return v.Metadata }).(metav1.ObjectMetaOutput)
}

func (o RecorderOutput) Spec() RecorderSpecOutput {
	return o.ApplyT(func(v *Recorder) RecorderSpecOutput { return v.Spec }).(RecorderSpecOutput)
}

func (o RecorderOutput) Status() RecorderStatusPtrOutput {
	return o.ApplyT(func(v *Recorder) RecorderStatusPtrOutput { return v.Status }).(RecorderStatusPtrOutput)
}

type RecorderArrayOutput struct{ *pulumi.OutputState }

func (RecorderArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Recorder)(nil)).Elem()
}

func (o RecorderArrayOutput) ToRecorderArrayOutput() RecorderArrayOutput {
	return o
}

func (o RecorderArrayOutput) ToRecorderArrayOutputWithContext(ctx context.Context) RecorderArrayOutput {
	return o
}

func (o RecorderArrayOutput) Index(i pulumi.IntInput) RecorderOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Recorder {
		return vs[0].([]*Recorder)[vs[1].(int)]
	}).(RecorderOutput)
}

type RecorderMapOutput struct{ *pulumi.OutputState }

func (RecorderMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Recorder)(nil)).Elem()
}

func (o RecorderMapOutput) ToRecorderMapOutput() RecorderMapOutput {
	return o
}

func (o RecorderMapOutput) ToRecorderMapOutputWithContext(ctx context.Context) RecorderMapOutput {
	return o
}

func (o RecorderMapOutput) MapIndex(k pulumi.StringInput) RecorderOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Recorder {
		return vs[0].(map[string]*Recorder)[vs[1].(string)]
	}).(RecorderOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RecorderInput)(nil)).Elem(), &Recorder{})
	pulumi.RegisterInputType(reflect.TypeOf((*RecorderArrayInput)(nil)).Elem(), RecorderArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RecorderMapInput)(nil)).Elem(), RecorderMap{})
	pulumi.RegisterOutputType(RecorderOutput{})
	pulumi.RegisterOutputType(RecorderArrayOutput{})
	pulumi.RegisterOutputType(RecorderMapOutput{})
}
