// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	"errors"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// RecorderList is a list of Recorder
type RecorderList struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// List of recorders. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items RecorderTypeArrayOutput `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaOutput `pulumi:"metadata"`
}

// NewRecorderList registers a new resource with the given unique name, arguments, and options.
func NewRecorderList(ctx *pulumi.Context,
	name string, args *RecorderListArgs, opts ...pulumi.ResourceOption) (*RecorderList, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Items == nil {
		return nil, errors.New("invalid value for required argument 'Items'")
	}
	args.ApiVersion = pulumi.StringPtr("tailscale.com/v1alpha1")
	args.Kind = pulumi.StringPtr("RecorderList")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource RecorderList
	err := ctx.RegisterResource("kubernetes:tailscale.com/v1alpha1:RecorderList", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRecorderList gets an existing RecorderList resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRecorderList(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RecorderListState, opts ...pulumi.ResourceOption) (*RecorderList, error) {
	var resource RecorderList
	err := ctx.ReadResource("kubernetes:tailscale.com/v1alpha1:RecorderList", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RecorderList resources.
type recorderListState struct {
}

type RecorderListState struct {
}

func (RecorderListState) ElementType() reflect.Type {
	return reflect.TypeOf((*recorderListState)(nil)).Elem()
}

type recorderListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// List of recorders. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items []RecorderType `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `pulumi:"metadata"`
}

// The set of arguments for constructing a RecorderList resource.
type RecorderListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// List of recorders. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items RecorderTypeArrayInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaPtrInput
}

func (RecorderListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*recorderListArgs)(nil)).Elem()
}

type RecorderListInput interface {
	pulumi.Input

	ToRecorderListOutput() RecorderListOutput
	ToRecorderListOutputWithContext(ctx context.Context) RecorderListOutput
}

func (*RecorderList) ElementType() reflect.Type {
	return reflect.TypeOf((**RecorderList)(nil)).Elem()
}

func (i *RecorderList) ToRecorderListOutput() RecorderListOutput {
	return i.ToRecorderListOutputWithContext(context.Background())
}

func (i *RecorderList) ToRecorderListOutputWithContext(ctx context.Context) RecorderListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecorderListOutput)
}

// RecorderListArrayInput is an input type that accepts RecorderListArray and RecorderListArrayOutput values.
// You can construct a concrete instance of `RecorderListArrayInput` via:
//
//	RecorderListArray{ RecorderListArgs{...} }
type RecorderListArrayInput interface {
	pulumi.Input

	ToRecorderListArrayOutput() RecorderListArrayOutput
	ToRecorderListArrayOutputWithContext(context.Context) RecorderListArrayOutput
}

type RecorderListArray []RecorderListInput

func (RecorderListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RecorderList)(nil)).Elem()
}

func (i RecorderListArray) ToRecorderListArrayOutput() RecorderListArrayOutput {
	return i.ToRecorderListArrayOutputWithContext(context.Background())
}

func (i RecorderListArray) ToRecorderListArrayOutputWithContext(ctx context.Context) RecorderListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecorderListArrayOutput)
}

// RecorderListMapInput is an input type that accepts RecorderListMap and RecorderListMapOutput values.
// You can construct a concrete instance of `RecorderListMapInput` via:
//
//	RecorderListMap{ "key": RecorderListArgs{...} }
type RecorderListMapInput interface {
	pulumi.Input

	ToRecorderListMapOutput() RecorderListMapOutput
	ToRecorderListMapOutputWithContext(context.Context) RecorderListMapOutput
}

type RecorderListMap map[string]RecorderListInput

func (RecorderListMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RecorderList)(nil)).Elem()
}

func (i RecorderListMap) ToRecorderListMapOutput() RecorderListMapOutput {
	return i.ToRecorderListMapOutputWithContext(context.Background())
}

func (i RecorderListMap) ToRecorderListMapOutputWithContext(ctx context.Context) RecorderListMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecorderListMapOutput)
}

type RecorderListOutput struct{ *pulumi.OutputState }

func (RecorderListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RecorderList)(nil)).Elem()
}

func (o RecorderListOutput) ToRecorderListOutput() RecorderListOutput {
	return o
}

func (o RecorderListOutput) ToRecorderListOutputWithContext(ctx context.Context) RecorderListOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o RecorderListOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *RecorderList) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// List of recorders. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
func (o RecorderListOutput) Items() RecorderTypeArrayOutput {
	return o.ApplyT(func(v *RecorderList) RecorderTypeArrayOutput { return v.Items }).(RecorderTypeArrayOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o RecorderListOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *RecorderList) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o RecorderListOutput) Metadata() metav1.ListMetaOutput {
	return o.ApplyT(func(v *RecorderList) metav1.ListMetaOutput { return v.Metadata }).(metav1.ListMetaOutput)
}

type RecorderListArrayOutput struct{ *pulumi.OutputState }

func (RecorderListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RecorderList)(nil)).Elem()
}

func (o RecorderListArrayOutput) ToRecorderListArrayOutput() RecorderListArrayOutput {
	return o
}

func (o RecorderListArrayOutput) ToRecorderListArrayOutputWithContext(ctx context.Context) RecorderListArrayOutput {
	return o
}

func (o RecorderListArrayOutput) Index(i pulumi.IntInput) RecorderListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RecorderList {
		return vs[0].([]*RecorderList)[vs[1].(int)]
	}).(RecorderListOutput)
}

type RecorderListMapOutput struct{ *pulumi.OutputState }

func (RecorderListMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RecorderList)(nil)).Elem()
}

func (o RecorderListMapOutput) ToRecorderListMapOutput() RecorderListMapOutput {
	return o
}

func (o RecorderListMapOutput) ToRecorderListMapOutputWithContext(ctx context.Context) RecorderListMapOutput {
	return o
}

func (o RecorderListMapOutput) MapIndex(k pulumi.StringInput) RecorderListOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RecorderList {
		return vs[0].(map[string]*RecorderList)[vs[1].(string)]
	}).(RecorderListOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RecorderListInput)(nil)).Elem(), &RecorderList{})
	pulumi.RegisterInputType(reflect.TypeOf((*RecorderListArrayInput)(nil)).Elem(), RecorderListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RecorderListMapInput)(nil)).Elem(), RecorderListMap{})
	pulumi.RegisterOutputType(RecorderListOutput{})
	pulumi.RegisterOutputType(RecorderListArrayOutput{})
	pulumi.RegisterOutputType(RecorderListMapOutput{})
}
