// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Patch resources are used to modify existing Kubernetes resources by using
// Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
// one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
// Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
// [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
// additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
// Recorder defines a tsrecorder device for recording SSH sessions. By default,
// it will store recordings in a local ephemeral volume. If you want to persist
// recordings, you can configure an S3-compatible API for storage.
//
// More info: https://tailscale.com/kb/1484/kubernetes-operator-deploying-tsrecorder
type RecorderPatch struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrOutput `pulumi:"metadata"`
	Spec     RecorderSpecPatchPtrOutput      `pulumi:"spec"`
	Status   RecorderStatusPatchPtrOutput    `pulumi:"status"`
}

// NewRecorderPatch registers a new resource with the given unique name, arguments, and options.
func NewRecorderPatch(ctx *pulumi.Context,
	name string, args *RecorderPatchArgs, opts ...pulumi.ResourceOption) (*RecorderPatch, error) {
	if args == nil {
		args = &RecorderPatchArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("tailscale.com/v1alpha1")
	args.Kind = pulumi.StringPtr("Recorder")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource RecorderPatch
	err := ctx.RegisterResource("kubernetes:tailscale.com/v1alpha1:RecorderPatch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRecorderPatch gets an existing RecorderPatch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRecorderPatch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RecorderPatchState, opts ...pulumi.ResourceOption) (*RecorderPatch, error) {
	var resource RecorderPatch
	err := ctx.ReadResource("kubernetes:tailscale.com/v1alpha1:RecorderPatch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RecorderPatch resources.
type recorderPatchState struct {
}

type RecorderPatchState struct {
}

func (RecorderPatchState) ElementType() reflect.Type {
	return reflect.TypeOf((*recorderPatchState)(nil)).Elem()
}

type recorderPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMetaPatch `pulumi:"metadata"`
	Spec     *RecorderSpecPatch      `pulumi:"spec"`
}

// The set of arguments for constructing a RecorderPatch resource.
type RecorderPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrInput
	Spec     RecorderSpecPatchPtrInput
}

func (RecorderPatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*recorderPatchArgs)(nil)).Elem()
}

type RecorderPatchInput interface {
	pulumi.Input

	ToRecorderPatchOutput() RecorderPatchOutput
	ToRecorderPatchOutputWithContext(ctx context.Context) RecorderPatchOutput
}

func (*RecorderPatch) ElementType() reflect.Type {
	return reflect.TypeOf((**RecorderPatch)(nil)).Elem()
}

func (i *RecorderPatch) ToRecorderPatchOutput() RecorderPatchOutput {
	return i.ToRecorderPatchOutputWithContext(context.Background())
}

func (i *RecorderPatch) ToRecorderPatchOutputWithContext(ctx context.Context) RecorderPatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecorderPatchOutput)
}

// RecorderPatchArrayInput is an input type that accepts RecorderPatchArray and RecorderPatchArrayOutput values.
// You can construct a concrete instance of `RecorderPatchArrayInput` via:
//
//	RecorderPatchArray{ RecorderPatchArgs{...} }
type RecorderPatchArrayInput interface {
	pulumi.Input

	ToRecorderPatchArrayOutput() RecorderPatchArrayOutput
	ToRecorderPatchArrayOutputWithContext(context.Context) RecorderPatchArrayOutput
}

type RecorderPatchArray []RecorderPatchInput

func (RecorderPatchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RecorderPatch)(nil)).Elem()
}

func (i RecorderPatchArray) ToRecorderPatchArrayOutput() RecorderPatchArrayOutput {
	return i.ToRecorderPatchArrayOutputWithContext(context.Background())
}

func (i RecorderPatchArray) ToRecorderPatchArrayOutputWithContext(ctx context.Context) RecorderPatchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecorderPatchArrayOutput)
}

// RecorderPatchMapInput is an input type that accepts RecorderPatchMap and RecorderPatchMapOutput values.
// You can construct a concrete instance of `RecorderPatchMapInput` via:
//
//	RecorderPatchMap{ "key": RecorderPatchArgs{...} }
type RecorderPatchMapInput interface {
	pulumi.Input

	ToRecorderPatchMapOutput() RecorderPatchMapOutput
	ToRecorderPatchMapOutputWithContext(context.Context) RecorderPatchMapOutput
}

type RecorderPatchMap map[string]RecorderPatchInput

func (RecorderPatchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RecorderPatch)(nil)).Elem()
}

func (i RecorderPatchMap) ToRecorderPatchMapOutput() RecorderPatchMapOutput {
	return i.ToRecorderPatchMapOutputWithContext(context.Background())
}

func (i RecorderPatchMap) ToRecorderPatchMapOutputWithContext(ctx context.Context) RecorderPatchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecorderPatchMapOutput)
}

type RecorderPatchOutput struct{ *pulumi.OutputState }

func (RecorderPatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RecorderPatch)(nil)).Elem()
}

func (o RecorderPatchOutput) ToRecorderPatchOutput() RecorderPatchOutput {
	return o
}

func (o RecorderPatchOutput) ToRecorderPatchOutputWithContext(ctx context.Context) RecorderPatchOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o RecorderPatchOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RecorderPatch) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o RecorderPatchOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RecorderPatch) pulumi.StringPtrOutput { return v.Kind }).(pulumi.StringPtrOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o RecorderPatchOutput) Metadata() metav1.ObjectMetaPatchPtrOutput {
	return o.ApplyT(func(v *RecorderPatch) metav1.ObjectMetaPatchPtrOutput { return v.Metadata }).(metav1.ObjectMetaPatchPtrOutput)
}

func (o RecorderPatchOutput) Spec() RecorderSpecPatchPtrOutput {
	return o.ApplyT(func(v *RecorderPatch) RecorderSpecPatchPtrOutput { return v.Spec }).(RecorderSpecPatchPtrOutput)
}

func (o RecorderPatchOutput) Status() RecorderStatusPatchPtrOutput {
	return o.ApplyT(func(v *RecorderPatch) RecorderStatusPatchPtrOutput { return v.Status }).(RecorderStatusPatchPtrOutput)
}

type RecorderPatchArrayOutput struct{ *pulumi.OutputState }

func (RecorderPatchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RecorderPatch)(nil)).Elem()
}

func (o RecorderPatchArrayOutput) ToRecorderPatchArrayOutput() RecorderPatchArrayOutput {
	return o
}

func (o RecorderPatchArrayOutput) ToRecorderPatchArrayOutputWithContext(ctx context.Context) RecorderPatchArrayOutput {
	return o
}

func (o RecorderPatchArrayOutput) Index(i pulumi.IntInput) RecorderPatchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RecorderPatch {
		return vs[0].([]*RecorderPatch)[vs[1].(int)]
	}).(RecorderPatchOutput)
}

type RecorderPatchMapOutput struct{ *pulumi.OutputState }

func (RecorderPatchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RecorderPatch)(nil)).Elem()
}

func (o RecorderPatchMapOutput) ToRecorderPatchMapOutput() RecorderPatchMapOutput {
	return o
}

func (o RecorderPatchMapOutput) ToRecorderPatchMapOutputWithContext(ctx context.Context) RecorderPatchMapOutput {
	return o
}

func (o RecorderPatchMapOutput) MapIndex(k pulumi.StringInput) RecorderPatchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RecorderPatch {
		return vs[0].(map[string]*RecorderPatch)[vs[1].(string)]
	}).(RecorderPatchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RecorderPatchInput)(nil)).Elem(), &RecorderPatch{})
	pulumi.RegisterInputType(reflect.TypeOf((*RecorderPatchArrayInput)(nil)).Elem(), RecorderPatchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RecorderPatchMapInput)(nil)).Elem(), RecorderPatchMap{})
	pulumi.RegisterOutputType(RecorderPatchOutput{})
	pulumi.RegisterOutputType(RecorderPatchArrayOutput{})
	pulumi.RegisterOutputType(RecorderPatchMapOutput{})
}
