// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Patch resources are used to modify existing Kubernetes resources by using
// Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
// one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
// Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
// [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
// additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
type TailnetPatch struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrOutput `pulumi:"metadata"`
	Spec     TailnetSpecPatchPtrOutput       `pulumi:"spec"`
	Status   TailnetStatusPatchPtrOutput     `pulumi:"status"`
}

// NewTailnetPatch registers a new resource with the given unique name, arguments, and options.
func NewTailnetPatch(ctx *pulumi.Context,
	name string, args *TailnetPatchArgs, opts ...pulumi.ResourceOption) (*TailnetPatch, error) {
	if args == nil {
		args = &TailnetPatchArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("tailscale.com/v1alpha1")
	args.Kind = pulumi.StringPtr("Tailnet")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource TailnetPatch
	err := ctx.RegisterResource("kubernetes:tailscale.com/v1alpha1:TailnetPatch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTailnetPatch gets an existing TailnetPatch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTailnetPatch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TailnetPatchState, opts ...pulumi.ResourceOption) (*TailnetPatch, error) {
	var resource TailnetPatch
	err := ctx.ReadResource("kubernetes:tailscale.com/v1alpha1:TailnetPatch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TailnetPatch resources.
type tailnetPatchState struct {
}

type TailnetPatchState struct {
}

func (TailnetPatchState) ElementType() reflect.Type {
	return reflect.TypeOf((*tailnetPatchState)(nil)).Elem()
}

type tailnetPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMetaPatch `pulumi:"metadata"`
	Spec     *TailnetSpecPatch       `pulumi:"spec"`
}

// The set of arguments for constructing a TailnetPatch resource.
type TailnetPatchArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPatchPtrInput
	Spec     TailnetSpecPatchPtrInput
}

func (TailnetPatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*tailnetPatchArgs)(nil)).Elem()
}

type TailnetPatchInput interface {
	pulumi.Input

	ToTailnetPatchOutput() TailnetPatchOutput
	ToTailnetPatchOutputWithContext(ctx context.Context) TailnetPatchOutput
}

func (*TailnetPatch) ElementType() reflect.Type {
	return reflect.TypeOf((**TailnetPatch)(nil)).Elem()
}

func (i *TailnetPatch) ToTailnetPatchOutput() TailnetPatchOutput {
	return i.ToTailnetPatchOutputWithContext(context.Background())
}

func (i *TailnetPatch) ToTailnetPatchOutputWithContext(ctx context.Context) TailnetPatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TailnetPatchOutput)
}

// TailnetPatchArrayInput is an input type that accepts TailnetPatchArray and TailnetPatchArrayOutput values.
// You can construct a concrete instance of `TailnetPatchArrayInput` via:
//
//	TailnetPatchArray{ TailnetPatchArgs{...} }
type TailnetPatchArrayInput interface {
	pulumi.Input

	ToTailnetPatchArrayOutput() TailnetPatchArrayOutput
	ToTailnetPatchArrayOutputWithContext(context.Context) TailnetPatchArrayOutput
}

type TailnetPatchArray []TailnetPatchInput

func (TailnetPatchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TailnetPatch)(nil)).Elem()
}

func (i TailnetPatchArray) ToTailnetPatchArrayOutput() TailnetPatchArrayOutput {
	return i.ToTailnetPatchArrayOutputWithContext(context.Background())
}

func (i TailnetPatchArray) ToTailnetPatchArrayOutputWithContext(ctx context.Context) TailnetPatchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TailnetPatchArrayOutput)
}

// TailnetPatchMapInput is an input type that accepts TailnetPatchMap and TailnetPatchMapOutput values.
// You can construct a concrete instance of `TailnetPatchMapInput` via:
//
//	TailnetPatchMap{ "key": TailnetPatchArgs{...} }
type TailnetPatchMapInput interface {
	pulumi.Input

	ToTailnetPatchMapOutput() TailnetPatchMapOutput
	ToTailnetPatchMapOutputWithContext(context.Context) TailnetPatchMapOutput
}

type TailnetPatchMap map[string]TailnetPatchInput

func (TailnetPatchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TailnetPatch)(nil)).Elem()
}

func (i TailnetPatchMap) ToTailnetPatchMapOutput() TailnetPatchMapOutput {
	return i.ToTailnetPatchMapOutputWithContext(context.Background())
}

func (i TailnetPatchMap) ToTailnetPatchMapOutputWithContext(ctx context.Context) TailnetPatchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TailnetPatchMapOutput)
}

type TailnetPatchOutput struct{ *pulumi.OutputState }

func (TailnetPatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TailnetPatch)(nil)).Elem()
}

func (o TailnetPatchOutput) ToTailnetPatchOutput() TailnetPatchOutput {
	return o
}

func (o TailnetPatchOutput) ToTailnetPatchOutputWithContext(ctx context.Context) TailnetPatchOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o TailnetPatchOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TailnetPatch) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o TailnetPatchOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TailnetPatch) pulumi.StringPtrOutput { return v.Kind }).(pulumi.StringPtrOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o TailnetPatchOutput) Metadata() metav1.ObjectMetaPatchPtrOutput {
	return o.ApplyT(func(v *TailnetPatch) metav1.ObjectMetaPatchPtrOutput { return v.Metadata }).(metav1.ObjectMetaPatchPtrOutput)
}

func (o TailnetPatchOutput) Spec() TailnetSpecPatchPtrOutput {
	return o.ApplyT(func(v *TailnetPatch) TailnetSpecPatchPtrOutput { return v.Spec }).(TailnetSpecPatchPtrOutput)
}

func (o TailnetPatchOutput) Status() TailnetStatusPatchPtrOutput {
	return o.ApplyT(func(v *TailnetPatch) TailnetStatusPatchPtrOutput { return v.Status }).(TailnetStatusPatchPtrOutput)
}

type TailnetPatchArrayOutput struct{ *pulumi.OutputState }

func (TailnetPatchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TailnetPatch)(nil)).Elem()
}

func (o TailnetPatchArrayOutput) ToTailnetPatchArrayOutput() TailnetPatchArrayOutput {
	return o
}

func (o TailnetPatchArrayOutput) ToTailnetPatchArrayOutputWithContext(ctx context.Context) TailnetPatchArrayOutput {
	return o
}

func (o TailnetPatchArrayOutput) Index(i pulumi.IntInput) TailnetPatchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *TailnetPatch {
		return vs[0].([]*TailnetPatch)[vs[1].(int)]
	}).(TailnetPatchOutput)
}

type TailnetPatchMapOutput struct{ *pulumi.OutputState }

func (TailnetPatchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TailnetPatch)(nil)).Elem()
}

func (o TailnetPatchMapOutput) ToTailnetPatchMapOutput() TailnetPatchMapOutput {
	return o
}

func (o TailnetPatchMapOutput) ToTailnetPatchMapOutputWithContext(ctx context.Context) TailnetPatchMapOutput {
	return o
}

func (o TailnetPatchMapOutput) MapIndex(k pulumi.StringInput) TailnetPatchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *TailnetPatch {
		return vs[0].(map[string]*TailnetPatch)[vs[1].(string)]
	}).(TailnetPatchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TailnetPatchInput)(nil)).Elem(), &TailnetPatch{})
	pulumi.RegisterInputType(reflect.TypeOf((*TailnetPatchArrayInput)(nil)).Elem(), TailnetPatchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TailnetPatchMapInput)(nil)).Elem(), TailnetPatchMap{})
	pulumi.RegisterOutputType(TailnetPatchOutput{})
	pulumi.RegisterOutputType(TailnetPatchArrayOutput{})
	pulumi.RegisterOutputType(TailnetPatchMapOutput{})
}
