// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Tailnet struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaOutput `pulumi:"metadata"`
	Spec     TailnetSpecOutput       `pulumi:"spec"`
	Status   TailnetStatusPtrOutput  `pulumi:"status"`
}

// NewTailnet registers a new resource with the given unique name, arguments, and options.
func NewTailnet(ctx *pulumi.Context,
	name string, args *TailnetArgs, opts ...pulumi.ResourceOption) (*Tailnet, error) {
	if args == nil {
		args = &TailnetArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("tailscale.com/v1alpha1")
	args.Kind = pulumi.StringPtr("Tailnet")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource Tailnet
	err := ctx.RegisterResource("kubernetes:tailscale.com/v1alpha1:Tailnet", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTailnet gets an existing Tailnet resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTailnet(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TailnetState, opts ...pulumi.ResourceOption) (*Tailnet, error) {
	var resource Tailnet
	err := ctx.ReadResource("kubernetes:tailscale.com/v1alpha1:Tailnet", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Tailnet resources.
type tailnetState struct {
}

type TailnetState struct {
}

func (TailnetState) ElementType() reflect.Type {
	return reflect.TypeOf((*tailnetState)(nil)).Elem()
}

type tailnetArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `pulumi:"metadata"`
	Spec     *TailnetSpec       `pulumi:"spec"`
}

// The set of arguments for constructing a Tailnet resource.
type TailnetArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata metav1.ObjectMetaPtrInput
	Spec     TailnetSpecPtrInput
}

func (TailnetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*tailnetArgs)(nil)).Elem()
}

type TailnetInput interface {
	pulumi.Input

	ToTailnetOutput() TailnetOutput
	ToTailnetOutputWithContext(ctx context.Context) TailnetOutput
}

func (*Tailnet) ElementType() reflect.Type {
	return reflect.TypeOf((**Tailnet)(nil)).Elem()
}

func (i *Tailnet) ToTailnetOutput() TailnetOutput {
	return i.ToTailnetOutputWithContext(context.Background())
}

func (i *Tailnet) ToTailnetOutputWithContext(ctx context.Context) TailnetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TailnetOutput)
}

// TailnetArrayInput is an input type that accepts TailnetArray and TailnetArrayOutput values.
// You can construct a concrete instance of `TailnetArrayInput` via:
//
//	TailnetArray{ TailnetArgs{...} }
type TailnetArrayInput interface {
	pulumi.Input

	ToTailnetArrayOutput() TailnetArrayOutput
	ToTailnetArrayOutputWithContext(context.Context) TailnetArrayOutput
}

type TailnetArray []TailnetInput

func (TailnetArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Tailnet)(nil)).Elem()
}

func (i TailnetArray) ToTailnetArrayOutput() TailnetArrayOutput {
	return i.ToTailnetArrayOutputWithContext(context.Background())
}

func (i TailnetArray) ToTailnetArrayOutputWithContext(ctx context.Context) TailnetArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TailnetArrayOutput)
}

// TailnetMapInput is an input type that accepts TailnetMap and TailnetMapOutput values.
// You can construct a concrete instance of `TailnetMapInput` via:
//
//	TailnetMap{ "key": TailnetArgs{...} }
type TailnetMapInput interface {
	pulumi.Input

	ToTailnetMapOutput() TailnetMapOutput
	ToTailnetMapOutputWithContext(context.Context) TailnetMapOutput
}

type TailnetMap map[string]TailnetInput

func (TailnetMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Tailnet)(nil)).Elem()
}

func (i TailnetMap) ToTailnetMapOutput() TailnetMapOutput {
	return i.ToTailnetMapOutputWithContext(context.Background())
}

func (i TailnetMap) ToTailnetMapOutputWithContext(ctx context.Context) TailnetMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TailnetMapOutput)
}

type TailnetOutput struct{ *pulumi.OutputState }

func (TailnetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Tailnet)(nil)).Elem()
}

func (o TailnetOutput) ToTailnetOutput() TailnetOutput {
	return o
}

func (o TailnetOutput) ToTailnetOutputWithContext(ctx context.Context) TailnetOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o TailnetOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *Tailnet) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o TailnetOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *Tailnet) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o TailnetOutput) Metadata() metav1.ObjectMetaOutput {
	return o.ApplyT(func(v *Tailnet) metav1.ObjectMetaOutput { return v.Metadata }).(metav1.ObjectMetaOutput)
}

func (o TailnetOutput) Spec() TailnetSpecOutput {
	return o.ApplyT(func(v *Tailnet) TailnetSpecOutput { return v.Spec }).(TailnetSpecOutput)
}

func (o TailnetOutput) Status() TailnetStatusPtrOutput {
	return o.ApplyT(func(v *Tailnet) TailnetStatusPtrOutput { return v.Status }).(TailnetStatusPtrOutput)
}

type TailnetArrayOutput struct{ *pulumi.OutputState }

func (TailnetArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Tailnet)(nil)).Elem()
}

func (o TailnetArrayOutput) ToTailnetArrayOutput() TailnetArrayOutput {
	return o
}

func (o TailnetArrayOutput) ToTailnetArrayOutputWithContext(ctx context.Context) TailnetArrayOutput {
	return o
}

func (o TailnetArrayOutput) Index(i pulumi.IntInput) TailnetOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Tailnet {
		return vs[0].([]*Tailnet)[vs[1].(int)]
	}).(TailnetOutput)
}

type TailnetMapOutput struct{ *pulumi.OutputState }

func (TailnetMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Tailnet)(nil)).Elem()
}

func (o TailnetMapOutput) ToTailnetMapOutput() TailnetMapOutput {
	return o
}

func (o TailnetMapOutput) ToTailnetMapOutputWithContext(ctx context.Context) TailnetMapOutput {
	return o
}

func (o TailnetMapOutput) MapIndex(k pulumi.StringInput) TailnetOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Tailnet {
		return vs[0].(map[string]*Tailnet)[vs[1].(string)]
	}).(TailnetOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TailnetInput)(nil)).Elem(), &Tailnet{})
	pulumi.RegisterInputType(reflect.TypeOf((*TailnetArrayInput)(nil)).Elem(), TailnetArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TailnetMapInput)(nil)).Elem(), TailnetMap{})
	pulumi.RegisterOutputType(TailnetOutput{})
	pulumi.RegisterOutputType(TailnetArrayOutput{})
	pulumi.RegisterOutputType(TailnetMapOutput{})
}
