name: images

on:
    push:
        branches: [main]
    workflow_dispatch:

env:
    REGISTRY: ghcr.io

jobs:
    publish:
        runs-on: ubuntu-24.04-arm
        permissions:
            contents: read
            packages: write
        strategy:
            matrix:
                app: [coredns, homeassistant]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Nix
              uses: cachix/install-nix-action@v27
              with:
                  github_access_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push ${{ matrix.app }} Docker image
              working-directory: ./applications/${{ matrix.app }}
              run: make docker-push
              env:
                  IMAGE_NAME: ${{ env.REGISTRY }}/liamawhite/${{ matrix.app }}
                  TAG: ${{ github.sha }}
