// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Accommodation struct {
	ID        string
	TripID    string
	Name      string
	Location  string
	CheckIn   string
	CheckOut  string
	CreatedAt string
}

type Flight struct {
	ID                 string
	TripID             string
	FlightNumber       string
	FlightDate         string
	DepartureAirport   string
	ArrivalAirport     string
	ScheduledDeparture sql.NullString
	ScheduledArrival   sql.NullString
	ActualDeparture    sql.NullString
	ActualArrival      sql.NullString
	Status             string
	LastSyncedAt       sql.NullString
	SyncError          string
	CreatedAt          string
	DepartureTimezone  string
	ArrivalTimezone    string
}

type Trip struct {
	ID        string
	Name      string
	CreatedAt string
}
